### ISSUE TITLE
Double Check No Rounding/Precision Error

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#100]
Based on this discussion (_Originally posted by @nlordell in https://github.com/gnosis/gp-v2-services/pull/1225#discussion_r739033527_), it remains to verify that the non-deterministic ordering 
of the Balance array returned by the method `upscale_balances_with_token_indices` cannot give rise to any undesired
rounding/precision errors in the functions which operate on this. 

Specifically, the internal methods
- calculate_invariant and
- get_token_balance_given_invariant_and_all_other_balances

which perform balancer-arithmetic on the balances array from inside `calc_X_given_Y`

> Original issue https://github.com/gnosis/gp-v2-services/issues/1332 by @bh2smith

**Comment by MartinquaXD** [comment]
This issue is ancient and AFAIK never happened (or at least not enough to be a known problem).
