### ISSUE TITLE
`driver` solution verification

### ISSUE THREAD

**Issue by fcked** [cowprotocol/services#1009]
The driver should never publish an illegal solution. Therefore, during the solving process process, the following points need to be verified:

- The settlement transaction passes simulation, both with and without respecting the `internalize` flags of the solution.
- The sum of tokens into and out of our settlement contract should be non-negative, i.e. the solver doesn't take any tokens out of the contract.
- Internalized interactions use trusted tokens. This requires checking the internalized interactions in the solution against the trusted tokens in the auction to make sure there's no foul play.

The first prevents the driver from burning gas and paying what would have been their rewards to the protocol. The other two are illegal and if the solvers were to publish such settlements, their rewards would be slashed as punishment, so the driver prevents that from happening.

Idea for implementation: `solution::Verified` as a newtype for `Solution`. `execute` expects a `solution::Verified`.

**Comment by nlordell** [comment]
For additional extra context, the checks besides the "the settlement transaction passes simulation" are for checking off-chain rules that aren't verified on-chain.

**Comment by nlordell** [comment]
Also important to note that the "the settlement transaction passes simulation" check should be done on **both** the "full" settlement (i.e. the settlement including internalized interactions) and the "actual" settlement (i.e. the settlement that only includes non-internalized interactions).

**Comment by nlordell** [comment]
> Why isn't it enough to just check the "actual" settlement?

So, if you 100% trust your settlement, it is enough. However, not being able to provide valid call data for an internalized interaction is a slash-able offense. I think it makes sense for the reference `driver` implementation to check this.

**Comment by nlordell** [comment]
I think this should be:

> Therefore, during ~~both~~ the solving process ~~and the quoting process~~, the following points need to be verified:

Specifically, simulating quotes is not really possible/well defined as there are no orders. In theory you could do some more complex trade simulation (like we do in the `shared::price_estimation::trade_finder` module), but I think this **should** be done in the core protocol services (i.e. `autopilot` and `orderbook`) as quotes are untrusted and need to be verified there anyway.

The reason we want to do these checks specifically for the solving process is to prevent solver engine footguns that lead to slashing.

**Comment by nlordell** [comment]
This should be:

> The first prevents the driver from burning gas **and paying what would have been their rewards to the protocol**.

This is also illegal under the new solver rewards scheme. Drivers would submit the score to the `autopilot` and, if they win and choose to execute the settlement, would need to mine the transaction within a block limit. Failure to do so would make you pay what you would have gotten as rewards to the protocol.
