### ISSUE TITLE
Max price deviation check makes some orders unfillable

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1013]
From Haris:
The Raven solver, currently in shadow, pointed out that there was a solution they submitted (auction id 4944054 in shadow) that was rejected due to a max price violation error on the WETH/USDC pair. The order that triggered [this](https://explorer.cow.fi/orders/0xf11e363cc75c346ed8b8e745b131e90c50ed090e412b3d49381c06c895570098626a7976d5256d12b4e503c053b043eccc674ddf63bfc72d) was this one. Raven's solution included a raw interaction where the amounts were indeed ok and it was returning even some small surplus to the order. The point here being that the order itself, even if matched with zero surplus, would necessarily violate the max price deviation condition. This made the order unfillable. Assuming we want to keep these price deviation tests, I think we should filter such orders (the Raven team already suggested we should do it).

**Comment by fleupold** [comment]
Price deviation check no longer exists.
