### ISSUE TITLE
Fix "economic viability" for the Gnosis_0x solver

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1021]
The 0x solver is one of the worst solvers in terms of settling non viable trades, often picking on so-called arbitrage stable-to-stable trades.  (see also discussion [here](https://cowservices.slack.com/archives/C036JAGRQ04/p1672679574673589?thread_ts=1672154090.388719&cid=C036JAGRQ04)).

We propose that we modify the solver by forcing it to not submit any solution that has non-positive objective value.

**Comment by MartinquaXD** [comment]
If this approach is correct for 0x it's probably the right thing to do in general. In that case this fix should be done for all solvers (even if they might not run into that problem frequently).

**Comment by harisang** [comment]
> If this approach is correct for 0x it's probably the right thing to do in general. In that case this fix should be done for all solvers (even if they might not run into that problem frequently).

We are still a bit undecided on this, as we don't have a clear idea how much this would impact the user experience. The thing is that in times of high volatility, we still want to maintain a good throughput, and by enforcing this for multiple solvers we might risk low settlement rates.

It might sound contradictory to an extent, but I specifically targeted the 0x solver as it seems to be lagging a bit, picking consistently on arbitrage opportunities even under low gas costs, that by the time it attempts to extract those, these opportunities are gone. This is not so much the case with 1inch or Paraswap, that's why I propose to first start only with 0x to see how it goes.
