### ISSUE TITLE
EthFlow Orders Missing From Order Creation Metrics

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1033]
It appears that created EthFlow orders are not being tracked with metrics, this is causing our order creation metrics to report incorrect data.

This issue captures the work to:
- Start tracking **created** EthFlow orders (or, more generally speaking on-chain orders) with Prometheus metrics
- Update existing Grafana dashboards to account for on-chain orders.

**Comment by josojo** [comment]
@fedgiac Could you tackle this issue this week?

**Comment by fedgiac** [comment]
We will be changing how eth-flow orders are handled and orders are counted. This task will be handled there.

**Comment by fedgiac** [comment]
As far as I know, metrics are still missing. However, we want to revisit how the ETH flow works, so this would be included in the refactor.
