### ISSUE TITLE
Autopilot traces are not being logged

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#1035]
In the autopilot, there are some tracing:trace logs that are not being logged in kibana:

One example of a log is here:
https://github.com/cowprotocol/services/blob/795128a72e8eeaa0fc96f63301f42f9883f66a20/crates/autopilot/src/auction_transaction.rs#L66

but the autopilot has only this setup for the log_filter
```
- name: LOG_FILTER
              value: "warn,autopilot=debug,shared=debug,shared::ethrpc=trace"
```

Was this only forgotten to update, or was there a reason behind not including it? It looks quite intentional from the config.
I am asking since I needed that linked trace for debugging a case. Maybe I should just switch for that particular line from trace to debug?

**Comment by vkgnosis** [comment]
The true log config is in the kubernetes file. The default values in the rust code are just defaults. Our plan for trace logs is that they shouldn't be enabled by default because they are too spammy. We can enable trace logs for specific modules temporarily to debug something.

**Comment by nlordell** [comment]
We disabled `trace` logs because of issues with `fluentd` with keeping up and sending them to our ElasticSearch instances and were losing logs.

We should experiment with re-enabling it to see if it can handle the load now. As @vkgnosis said - the truth is our k8s deployment configuration.

**Comment by vkgnosis** [comment]
I don't think we should always have trace logs enabled. I like the definition of trace to be that it's information we don't usually need but can enable in specific cases. If you need these trace logs to debug something now you can enable trace logging precisely for this module.
