### ISSUE TITLE
Add Support for OpenOcean DEX Aggregator

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1040]
This "mini-epic" issue capture the necessary work to introduce a new DEX aggregator, specifically [OpenOcean](https://openocean.finance/) to the list we already support. Fortunately, most of the ground work is already there because of the existing abstractions around DEX aggregators.

- [ ] Implement the API abstraction for the [OpenOcean API](https://docs.openocean.finance/dev/openocean-api-3.0/api-reference)
    - Note that we should **seriously** consider using the non-public API `ethapi.openocean.finance`. This is used by the OpenOcean front-end as well as [Defi Llama](https://swap.defillama.com/) and, at least in my experimentation, provided more accurate prices (the open API would either underquote or overquote by a significant margin). The API request can be reverse engineered from the Defi Llama UI (its a single HTTP request).
- [ ] Implement a price estimator using the OpenOcean API based on the [`TradeFinding` interface](https://github.com/cowprotocol/services/blob/main/crates/shared/src/trade_finding.rs).
- [ ] Implement a solver using the OpenOcean API based on the [`SingleOrderSolver` interface](https://github.com/cowprotocol/services/blob/main/crates/solver/src/solver/single_order_solver.rs).

**Comment by MartinquaXD** [comment]
OpenOcean is running their own solver by now so we no longer have to integrate them ourselves.
