### ISSUE TITLE
Let solvers prioritize multiple orders with same `owner` and `sell_token`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1064]
When a user creates an order we only verify that they have the required `sell_token` at the creation time. That means a user could create multiple orders for the same `sell_token` where the total `sell_amount` is bigger that what the user currently has.

In that case someone needs to decide which order to prioritize because they can not all be settled at the same time.
There are 2 options:
1. Do some heuristic in the `autopilot`.
2. Tell the solvers how much `sell_token` the `owner` has on each order and let them figure out which to prioritize.

Option 2 is pretty straight forward for us and reduces the "censorship" in the system. As a down side this requires more work on the solver side so we [asked](https://cowservices.slack.com/archives/C036JAGRQ04/p1673260079140729) them what they prefer.
The consensus seems to be that they prefer option 2 even if it's more work for them so I guess this is the winner.

Concrete implementation steps include:
1. Add `available_balance` field to [orders](https://github.com/cowprotocol/services/blob/main/crates/solver/src/liquidity.rs#L148-L177) sent to the solvers.
2. While building the auction in the `SolvableOrdersCache` we need to query the current `sell_token` balance of the `owner` of the order. I guess at this point it probably makes sense to also simulate pre interactions of the order in case they alter the balance before executing the order.
3. Drop current prioritization logic in the [`SolvableOrdersCache`](https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/solvable_orders.rs#L337-L396).

Note that pre-interactions theoretically have the same problem as the `sell_amount` (some pre-interactions might not be executable if some other pre-interaction runs first) but I believe this something we can tackle when we actually have more orders with pre-interactions.

**Comment by nlordell** [comment]
> Note that pre-interactions theoretically have the same problem as the sell_amount (some pre-interactions might not be executable if some other pre-interaction runs first) but I believe this something we can tackle when we actually have more orders with pre-interactions.

A concrete example of this is EIP-2612 permit pre-interactions as they have a "nonce" system.

**Comment by fleupold** [comment]
Solvers were first excited but noone actually implemented logic for filtering orders. We are now filtering orders for the same sell token prioritised by expected surplus in the driver:

https://github.com/cowprotocol/services/blob/0d355270030e736ce63afc04b39e1d3829a37074/crates/driver/src/domain/competition/auction.rs#L99-L101

**Comment by MartinquaXD** [comment]
Solvers said in the past that they would like to prioritize themselves but then never did.
Will close the issue since the current prioritization of the driver is reasonable and if solvers are actually keen on prioritizing themselves they can open a PR or rewrite the driver.
