### ISSUE TITLE
Driver access list gas optimization

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#1071]
If a transaction would end up paying more gas with the access list (which can easily happen for simple txs due to increased tx size), it doesn't make sense to specify the access list. As an optimization, the driver should not add access lists to settlements if this increases gas costs.

The `autopilot` used to already do this optimization.

**Comment by MartinquaXD** [comment]
> which can easily happen for simple txs due to increased tx size

AFAIK access lists can only cause increased gas usage if they cause the node to load storage that does not get used during the transaction. Although the access list increases the number of bytes required to send to the node those bytes don't cost gas like the usual call data does.

**Comment by nlordell** [comment]
> AFAIK access lists can only cause increased gas usage if they cause the node to load storage that does not get used during the transaction

No, there are other cases where this happens. Specifically, the contract being called (the `to` field in the Ethereum transaction) is always considered "warm", so adding it to the access list is only beneficial if you have enough storage accesses to offset the additional address warmup that you pay.

For a reference implementation on the specific optimization that we should do locally (which some nodes support, but **as a non-standardized option**):
- https://github.com/NethermindEth/nethermind/blob/84c269d684fa55b335de2d8a733a6ab9ba60b531/src/Nethermind/Nethermind.Evm/Tracing/AccessTxTracer.cs#L203-L211

Also, I _think_ we should remove "precompile" contract access list items (which get added but aren't needed as precompiles seem to be always warm - should double check this).

**Comment by fleupold** [comment]
I think the current trend is to rather move away from access lists completely (and instead warm up storage for Safes in a pre interaction) given the complexity and limited usefulness they pose.

**Comment by sunce86** [comment]
Last time I checked, access lists were saving us 1% of gas used on average. Whether this is significant amount or not, I'm not inclined to say.
Given this is an optimization that improve solvers cost (not the protocols) I agree to lower the priority.
