### ISSUE TITLE
Ethflow feature: Invalid order status 

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#1072]
If ethflow ordres are passed and we get an order placement error, the status of an order is currently still "open" or later "expired". A better status would be "invalid"

Hence, we should add a new status "Invalid" in the backend for an order. This status should be assigned to order each time there is a placement error. This new status should then be sent over to the front-end via the API.

**Comment by fleupold** [comment]
Maybe a consideration for the orthogonal ethflow service (or a wontfix since it doesn't seem to be affecting many users)
