### ISSUE TITLE
[Ethflow] Limit orders can be created as eth-flow orders even if globally disabled

### ISSUE THREAD

**Issue by fedgiac** [cowprotocol/services#1078]
I noticed a todo comment [here](https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/database/onchain_order_events.rs#L576-L579), this is the corresponding issue.
It should not be possible to create limit orders through eth-flow orders if limit orders are disabled.

Note that an error variant for this case was already created [here](https://github.com/cowprotocol/services/pull/969), however handling this case isn't implemented.

**Comment by fleupold** [comment]
Probably not worth fixing as limit orders are now always enabled.

**Comment by MartinquaXD** [comment]
By now we even removed the option to disable limit orders so this can be closed.
