### ISSUE TITLE
Seasolver token support - multiple token holders

### ISSUE THREAD

**Issue by pata-eth** [cowprotocol/services#1084]
COW protocol checks seasolver's endpoint `/token_holders` for a list of token addresses with a corresponding holder to determine whether a token is supported. Seasolver refreshes the list once every couple of days, so it's possible that a token may be considered unsupported if a holder in the list does no longer keep a balance of such token. 

It'd be useful if the driver checked for multiple token holders until it finds a valid one instead of determining validity based on a single datapoint. This will dramatically increase the chance of success when determining token validity, and therefore improve trading experience. Also, it's been difficult for Seasolver to learn about when orders are being dropped because their tokens were no longer supported because a holder wasn't found anymore. 

Current setup:

```json
"0x0327112423F3A68efdF1fcF402F6c5CB9f7C33fd": "0xd4dbf96db2fdf8ed40296d8d104b371adf7dee12"
```

Proposed setup:
```json
"0x0327112423F3A68efdF1fcF402F6c5CB9f7C33fd": [
    "0xd4dbf96db2fdf8ed40296d8d104b371adf7dee12",
    "0x592349f7dedb2b75f9d4f194d4b7c16d82e507dc",
    "0x16de73a47c9d663b02e625315d3c03f7aa3b8d7b"
]
```

Thank you, folks.

cc: @sunce86

**Comment by nlordell** [comment]
@pata-eth - what do you think about changing the API to return token holders to token instead of a large JSON map. Something like:

```
GET tokens/0x0327112423F3A68efdF1fcF402F6c5CB9f7C33fd/holders
```

Which would return:
```json
[
    "0xd4dbf96db2fdf8ed40296d8d104b371adf7dee12",
    "0x592349f7dedb2b75f9d4f194d4b7c16d82e507dc",
    "0x16de73a47c9d663b02e625315d3c03f7aa3b8d7b"
]
```

The reason I am proposing this API as it more closely matches the inner interface we use:

https://github.com/cowprotocol/services/blob/cabe79274f7ea61d554791c54ea567e01d9759ba/crates/shared/src/bad_token/token_owner_finder.rs#L40-L46C2

**Comment by sunce86** [comment]
@nlordell Wouldn't that slow down the implementation? We are now fetching holders in background thread and with your proposed solution it would require us to send http request each time.

**Comment by nlordell** [comment]
> We are now fetching holders in background thread and with your proposed solution it would require us to send http request each time.

I'm not too concerned, as I imagine that this is cached at multiple layers (both the SeaSolver token holder API implementation as well as locally).

I was just suggesting this to make the API more aligned with the internal interface that we expect, but I don't feel too strongly about it.

**Comment by pata-eth** [comment]
Thanks for the quick responses, folks. As suggested by @sunce86 I went ahead with the change as originally proposed. We are happy to provide the info in other ways if needed down the road. The change is live in the solver staging url.
