### ISSUE TITLE
Solution ID

### ISSUE THREAD

**Issue by ennmichael** [cowprotocol/services#1095]
This issue captures the work required to start encoding the solution ID in the onchain settlement.

The purpose of a solution ID is so that the autopilot can match onchain settlements with the solutions that they settle. The onchain settlement should include this settlement ID in its calldata. The autopilot listens for onchain transactions and matches them with their originating solutions via the ID. The solution ID is generated by the driver in `/solve` and returned to the autopilot.

The solution ID should be encoded as big-endian bytes, appended to the calldata.

**Comment by nlordell** [comment]
> Is it enough to just append it at the end of calldata [...] ?

Yes.
