### ISSUE TITLE
Auction-based Solver Rewards

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1108]
There has been discussion for quite some time for restructuring the solver rewards and move towards a model where solvers control how much they want to get reimbursed for the solutions they provide. Concretely:

1. Each solver would report a solution and the `score` it assigns to the solution, where the `score` is just a quantity denominated in ETH. 

2. The protocol would simulate all submitted solutions, and the solutions that successfully simulate get ranked in decreasing order of their score.

3. The winner is the solution that passed simulation and has the highest score, breaking ties randomly.

More discussion and details about the proposed model can be found [here](https://forum.cow.fi/t/cip-draft-auction-model-for-solver-rewards/1405).

**Required changes**
1. - [x] Solvers need to report one more value in their response json, which is the `score`. https://github.com/cowprotocol/services/issues/1114

2. - [x] Implement default `score` calculation.  https://github.com/cowprotocol/services/issues/1147

3. - [x] The score and ranking should be stored in the solver competition db, as it will be needed in order to analyse the `auction-based` ranking during the transition period and for general debugging purposes. https://github.com/cowprotocol/services/issues/1138

5. - [x] Solutions with negative score should be filtered out. This means that an auction where all solutions have a negative score will be rejected.

6. - [x] The driver simulates all submitted solutions, like it does now, but ranks solutions according to the score, which is reported by solvers themselves. However, since we want to have some checks, at least at an initial stage of the model, we would still want to compute the objective function, as it is computed now by the driver, and test whether `score > objective value`. There is an option here to always enforce that the score should be at most equal to the objective function, i.e., we could enforce that `score = min(score, obj value)`, but this has yet to be decided.

7. - [ ] Store all data needed for rewards calculation in a separate tables. 

8. - [x] Since the above model moves significant complexity to the solvers, we would like to do a 2-3 week trial run of the scheme. This would mean that solvers in production would report their solution and a score, and then we will do the "official" ranking and the payouts as we do now, but we would also like to have a shadow version of the competition, where the ranking would be based on score. Ideally this would also mean that if the winner changes when ranking according to score, we would simulate the alternative winner in the same block/index where the winning settlement ended up getting mined. This shadow version data should also be made accessible to all solver teams, so that they can evaluate their performance and get a good idea of what to expect from the model.

**Comment by nlordell** [comment]
> Since the above model moves significant complexity to the solvers, we would like to do a 2-3 week trial run of the scheme

Concretely, this means we probably need a feature flag for this.

**Comment by bh2smith** [comment]
Adding some data related tasks for services here:

- [ ] settlements table will have new columns `id` (unique integer) + and `execution_cost`  (or equivalently `gas_used * gas_price`)
- [ ] New table `settlement_rewards = [ settlement_id | surplus | fee | reported_score | second_score ]`
- [ ] [Transparancy] An API endpoint to return these rows (per tx_hash)...

Please feel free to alter if my understanding is missing something cc @sunce86 and @nlordell.

**Comment by bh2smith** [comment]
Proposed DB alterations PR is [here](https://github.com/cowprotocol/services/pull/1166)

**Comment by sunce86** [comment]
> 7. Ideally this would also mean that if the winner changes when ranking according to score, we would simulate the alternative winner in the same block/index where the winning settlement ended up getting mined.

Lets clarify this requirement. 
Is this supposed to be done in `driver`? 
What should we do with it? Should we store the success/failure in the solver competition db? Anything else?

**Comment by bh2smith** [comment]
Results of today's sync: New urgent item!

- [ ] Add block_deadline (integer column) to settlement_scores
```
block_deadline = instance_block + solver_time_limit + 10 (config param?)
```
