### ISSUE TITLE
SolverRewards: Add `score` to solvers response json

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1114]
Issue tracker: https://github.com/cowprotocol/services/issues/1108

Solvers need to report one more value in their response json, which is the `score`.

**Comment by nlordell** [comment]
This also means we need to add a "score" to the existing Gnosis solvers right? Is there a plan for that?

**Comment by sunce86** [comment]
> Solvers need to report one more value in their response json, which is the `score`.

Indeed, added https://github.com/cowprotocol/services/issues/1147

**Comment by sunce86** [comment]
Closed with https://github.com/cowprotocol/services/pull/1140
