### ISSUE TITLE
Prevent certain ETH flow orders below auto refunding limit

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1119]
The `refunder` background task that refunds expired ETH flow orders only refunds orders that did set a reasonable slippage (currently 190bps).
This is a limitation that integrators will probably not be aware of. For example DefiLlama is currently sending us orders that have 0 slippage which prevents them from getting refunded [[0](https://cowservices.slack.com/archives/C0361CDD1FZ/p1674246929312629)].

Could we automatically prevent the creation of such orders? Maybe all orders that have `appdata` that suggests they come from an integrator must have at least the minimum slippage amount for ETH flow orders?

Since it's not great that intgrators would have to be aware of the current slippage requirement we could respond with an error stating the current min slippage in case we change it in the future (although that can also leave orders unrefunded although they were created with the correct value at the time; might need another patch to address that).

**Comment by josojo** [comment]
>Could we automatically prevent the creation of such orders? Maybe all orders that have appdata that suggest they come from an integrator must have at least the minimum slippage amount for ETH flow orders?

I think all of this is not possible, as the orders are placed via a real ethereum transaction, rather an API call. Hence, we can only change the quoting. Here, I like your suggestion from the call, to provide the minimum refunding requirements as part of the quote.

**Comment by anxolin** [comment]
Maybe @MartinquaXD idea can be made into an alert. 
If we receive orders with low slippage for ETH Flow, we can just increment a counter in Prometheus or something. 

If we have better documentation and SDK maybe this is not an issue, but if it's low-hanging and let us discover new cases of bad integrations, maybe worth considering doing.

**Comment by fleupold** [comment]
I don't think we were having issues with this in the last 6 months so probably fine to close.
