### ISSUE TITLE
Choose transaction identifier tag in autopilot

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1136]
https://github.com/cowprotocol/services/pull/1135

> For this PR I set the tag to the auction id. This can be considered a placeholder, although it works well in practice too as long as different environments on the same network do not use the same id at the same time. I'm going to make an issue for this because it isn't part of this PR.

**Comment by fleupold** [comment]
Do we need to consider barn/prod producing the same auction id?

**Comment by MartinquaXD** [comment]
This is just a theoretical/unlikely issue.
But mitigations could be to not label the tx with the auction id but with some randomly generated key.
Or alternatively continue to submit the auction id but increase the auction_id in staging to such a high number that prod will "never" catch up to cause this collision.
