### ISSUE TITLE
SolverRewards: Implement default `score` calculation

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1147]
Issue tracker: https://github.com/cowprotocol/services/issues/1108

For external solvers, `score` will be provided as part of the solution json.
For non-external solvers, `score` needs to be calculated. Some default scoring calculation should be implemented, so the external solvers could use it also, during the transition period.

**Comment by sunce86** [comment]
Default scoring calculation should be equal to the current objective value calculation:
`score = objective_value = surplus + fees - costs` where costs are estimated (not mined) values. (estimated > mined)

In that case, the new reward would be:
`reward = surplus + fees - (surplus + fees - costs) = costs`

That said, since mined cost is smaller than estimated cost, solvers won't initially be running with minus.

**Comment by fhenneke** [comment]
This scoring function might be good enough to make a profit but is also easy to improve upon by solvers.

It contains two error compared to an optimal score which might cancel out to some expend:
- costs are overestimated, so the submitted score is smaller than it should be
- revert risk is not incorporated and thus the quality is overestimated, so the submitted score is larger than it should be

> In that case, the new reward would be:
> reward = surplus + fees - (surplus + fees - costs) = costs
> 
> That said, since mined cost is smaller than estimated cost, solvers won't initially be running with minus.

This is essentially correct with a small caveat: It is what would happen in a first price auction. There the reference score is the score submitted by the winning solution. In a second-price auction, the reference score can be smaller than the score of the winning solution. Thus
`reward = surplus + fees - reference_score >= surplus + fees - (surplus + fees - costs) = cost`.

**Comment by sunce86** [comment]
Closed with https://github.com/cowprotocol/services/pull/1279
