### ISSUE TITLE
Drop quoting strategies argument once we settle on a setup

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1168]
In order to easily test multiple different strategies for optimizing which limit orders to update the `surplus_fee` for I added the argument `--quoting-strategies`.
Eventually we should no longer need it when we tested each strategy and settled on a set of strategies we always want to apply.

This was suggested [here](https://github.com/cowprotocol/services/pull/1153/files#r1091812983).

**Comment by sunce86** [comment]
Background quoting limit orders was dropped. Now solvers define the surplus fee.
