### ISSUE TITLE
Specialize native price background updates for Autopilot

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1175]
Related to https://github.com/cowprotocol/services/pull/1159 .

How Autopilot wants to use native prices:
There is a large list of tokens that we need and are going to continue needing native prices for. The list is too long to fetch completely, so we get whatever prices are ready now and queue the others for later retrieval.

How Orderbook uses native prices:
Native prices are triggered by unpredictable external events like when an order is created or a quote requested.

Orderbook doesn't need background updates at all. The benefit from background updates here is that it reduces latency if a native price is already in the cache because of a background update, before it has been requested. The downside is that it is wasteful by creating load on the estimators, that sometimes is wasted. For rarely requested tokens, the background fetches are almost always wasted. For often requested tokens, we usually get a cache hit without background updates anyway. Currently (see Grafana) the cache hit rate is ~90% even though effectively all entries are out of date. The background updates do not contribute to the cache hit rate and the cache hit rate is already good. With smarter updating logic, the background updates could contribute more but that would still be a small benefit, and more complicated code.

Autopilot requires background updates and the current approach works fine for it. But it doesn't make sense to share this approach with Orderbook.

This is why I would like to move the current updating logic into Autopilot (out of the shared crate) so it is clear that it is written for Autopilot and doesn't have to concern itself with doing the right thing for Orderbook too. If we want to add a smarter Orderbook specific backbground updater, we can do that too, but it isn't urgent.

**Comment by MartinquaXD** [comment]
> For rarely requested tokens, the background fetches are almost always wasted. For often requested tokens, we usually get a cache hit without background updates anyway. Currently (see Grafana) the cache hit rate is ~90% even though effectively all entries are out of date.

I think this logic is flawed. Having a high hit rate despite having 90% outdated tokens can either mean that the background updates don't do anything or that it selects the tokens to update very well so little effort can be used to keep a lot of token prices usable. IMO grafana currently doesn't give a definitive answer on that.

Last time I did the [analysis](https://github.com/gnosis/gp-v2-services/pull/1671) on the topic there was already a notable difference in cache hit rate between different updating strategies so there should be at least as big of a difference between having the task and not having it.

My suggestion would be to disable the background task (or rather dial down to next to no updates)  in the orderbook for a while and see what impact that has on the cache hit rate. And even more importantly whether we can see a regression in the latency for quote responses.

If that experiment suggests that the update task doesn't improve things in the `orderbook` I'm on board with removing it.

If it shows that the update task helps, we have a different discussion on our hands. Namely if we can only issue a limited number of price estimation requests (to not get rate limited or overwhelm any API) where should we spend the resources? In that case I also agree that it makes more sense to spend them on the `autopilot` although we can probably find a reasonable middle ground where updating only a small number of tokens in the `orderbook` already gives us good enough results.

As a side note, we could also come up with a system where cached native prices can be shared across `autopilot` and `orderbook` but that seems like a lot of work for probably negligible gains.

**Comment by nlordell** [comment]
I also agree that we should remove the background task if it doesn't help with latency much.

> Currently (see Grafana) the cache hit rate is ~90% even though effectively all entries are out of date.

Is this with orderbook background task already disabled?

> If that experiment suggests that the update task doesn't improve things in the orderbook I'm on board with removing it.

This would also be my suggestion. We should be able to measure the impact and make an informed decision.

I would not be in favour of a big regression in quoting latency (as that has a negative impact on the CoW Swap UX).

**Comment by vkgnosis** [comment]
> Is this with orderbook background task already disabled?

No. I assumed that the background updates were not useful because the metrics show that almost all tokens in the cache are out of date  and we don't have a smart strategy for selecting which token to update. It turns we do we have a smarter than naive strategy. We select tokens first, that have most recently been requested. I wrongly assumed we updated the most outdated token first.

In that case I agree that we should run an experiment first. Either way it might still be useful to have the code separated between Orderbook and Autopilot because of the different requirements. Will think about it more.

**Comment by MartinquaXD** [comment]
The only thing that seems to have regressed slightly after disabling the background task is the 95 percentile latency of `/get_native_price` requests but not to a degree where it looks problematic.
TBH I'm a bit surprised but it looks like at this point the data really confirms that the background task can be disabled in the `orderbook` without causing a degraded experience.

**Comment by nlordell** [comment]
> TBH I'm a bit surprised but it looks like at this point the data really confirms that the background task can be disabled in the orderbook without causing a degraded experience.

One thing to be mindful of is that we have more traffic now than we used to. This may affect the 95% for the requests. Also, the native price cache used to be shared for auction building (which is no longer the case since the `autopilot` split-off). Given this data, I'm also OK with simplifying semantics of the `orderbook` and disabling the background thread in the orderbook.

I think, maybe a long-term thing we can think about, is moving price estimation as a whole out of `orderbook` and `autopilot` into a single service. I may be over-engineering here (if you think so, feel free to `goto END`), but this would allow us to combine price estimates across functions into a single place, and better control scaling for this **very** critical infrastructure piece in our protocol. Another simple answer might be to have the `autopilot` just issue `token/.../native_price` calls directly to the `orderbook` (as it already scales with requests and has caches). Still very cloudy in my mind, but something to think about. 

`:END`
