### ISSUE TITLE
Quote feeamout verification in autopilot

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#1176]
The API pod caches the balance of cow and vcow in order to calculate the subsidy factor. The same is done in the autopilot. If there was a significant movement of cow, shortly before the order was placed, the caches could not be in sync. This can imply that the calculated fee subsidy is different and in the worst cases, it could cause a quote to be rejected due to Insufficient fee amount. [This happened this ](https://cowservices.slack.com/archives/C035N0YEB6J/p1674992216205379) weekend.

Federico and I brainstromed some solutions:
- Share the cached balances of cow and vcow between the two pods either via a common database or via API requests
- Store the subsidy factor for each quote and don't recalculate it in the autopilot while parsing onchain orders
- Wait until we introduce limit-onchain orders (surplus charging orders)

Option 1 has the downside, that its still not failure proof: If a user places an onchain order with a lot of COW, but then - while the onchain order is still in flight - sends his cows somewhere else, the order could still fail
Option 3 is too risky, as this is not even on the priority list of this Q1.

Option 2 would be implemented in the following way:
Create a new database quote_subsidy with the fields, (quoted(Primary key), subsidy_factor, user). We can fill this table for all quotes if there is a unique user for a quote. If there is no unique user for the quote, then we simply will not store it.
 In the autopilot, we would then look up this table and use the calculated subsidy_factor from the quote, rather than recalculating the quotes again.
 
 Wdyt? If you agree I would start coding it today, such that its ready for next week's release. cc: @fedgiac

**Comment by MartinquaXD** [comment]
The new `CachingBalanceFetcher` invalidates balances on every new block it sees and only keeps balances warm that have been used recently. If it doesn't put too much pressure on the node we could simply try using that for the cow subsidy computation.

**Comment by josojo** [comment]
>The new CachingBalanceFetcher invalidates balances on every new block it sees and only keeps balances warm that have been used recently. If it doesn't put too much pressure on the node we could simply try using that for the cow subsidy computation.

That is a nice idea that would have saved us the issue from last weekend. But it does not solve all scenarios: Image a  quote is created with a high COW balance. Later -  when the autopilot does process the onchain order - it could be that the cow balance is lower and the calculated subsidy is no longer sufficient to justify the good quote. Then the Insufficient Fee Error would happen again.

**Comment by nlordell** [comment]
> it could be that the cow balance is lower and the calculated subsidy is no longer sufficient to justify the good quote. Then the Insufficient Fee Error would happen again.

Isn't this as designed? This means that the user changed their COW token balance between quoting and transaction mining. Do we need to support this case?

**Comment by nlordell** [comment]
Where did @MartinquaXD 's comment go?

**Comment by josojo** [comment]
>Isn't this as designed? This means that the user changed their COW token balance between quoting and transaction mining. Do we need to support this case?

I think for the ethflow orders, it's quite bad UX. We would have to warn users about yet another failure mode of their transactions. Hence, I would oppose this. I think we should only design it this way, if there is a risk of subsidy misuse. But I don't see this attack vector, especially with the long cache time of 1 hour.

**Comment by MartinquaXD** [comment]
> Where did @MartinquaXD 's comment go?

I removed it because I thought about the case @josojo brought up. Probably didn't refresh the page first to see that he already answered.

**Comment by vkgnosis** [comment]
> I think for the ethflow orders, it's quite bad UX.
Alternative solution: Don't consider cow balance subsidy when creating ethflow orders.

**Comment by josojo** [comment]
> Alternative solution: Don't consider cow balance subsidy when creating ethflow orders.

This would be the most straightforward fix. But I don't particularly like it, as we need to explain to users when their subsidy is applying. It would also require coordination with the front end.

**Comment by josojo** [comment]
Thanks for you thoughts. If you guys think I should start with the initial implementation(first comment in issue), please do a thumbs up. Otherwise, please voice your opinion one more time.

**Comment by nlordell** [comment]
> I think for the ethflow orders, it's quite bad UX

How so? You would have to really try to send out your CoW between getting a quote and submitting your EthFlow transaction to the block chain. I don't see this happening without a user trying hard to do this.

**Comment by josojo** [comment]
> I don't see this happening without a user trying hard to do this
I agree that this is an edge case. It will happen super rarely. But if it happens, it's bad. But I would also think that it's only happening if the user has some low-gas ethflow order that takes some minutes to mine and he is doing other onchain activity meanwhile, or if we process on-chain orders with a time-delay due to technical issues on the autopilot.

If you say it's okay to go have these super edge cases, then I am also fine with Martin's suggested solution. As you say in 99.9% of cases it's good enough.

**Comment by josojo** [comment]
> > The new CachingBalanceFetcher invalidates balances on every new block it sees and only keeps balances warm that have been used recently. If it doesn't put too much pressure on the node we could simply try using that for the cow subsidy computation.
> 
> That is a nice idea that would have saved us the issue from last weekend. But it does not solve all scenarios: Image a quote is created with a high COW balance. Later - when the autopilot does process the onchain order - it could be that the cow balance is lower and the calculated subsidy is no longer sufficient to justify the good quote. Then the Insufficient Fee Error would happen again.

Nick and I talked privately and we concluded that the COW balance reduction is super rare: It only happens if someone first creates a ethflow quote, then places the ethflow order and immediately after that reduces the cow balance with another transaction. Though the immediately could be stretched if our indexing of onchain orders is delayed for some reason. 
Hence, it trade-off between technical complexity and indexing correctly in very very rare conditions. I think both solutions are fine, but with Nick, we concluded that we would slightly prefer lower technical complexity and actually wanna try out Martins suggestion
