### ISSUE TITLE
Include order ID for liquidity orders in the payload to solvers

### ISSUE THREAD

**Issue by pata-eth** [cowprotocol/services#1185]
An order id is not currently provided for liquidity orders. The order id allows solvers to obtain more info on an order during an auction, such as the time left to expiration, and when debugging a batch among other benefits.

**Comment by sunce86** [comment]
Just to give a bit more context, `id: OrderUid` serialization is skipped for some of the liquidity orders, namely ZeroEx liquidity orders for which we can't generate the `OrderUid`. So, I am not sure this is an actionable issue.

**Comment by pata-eth** [comment]
Thanks, @sunce86 . Following our conversation, let's close the issue.
