### ISSUE TITLE
Cow Token Utility

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#124]
Subsidy can be calculated in several ways, based on:

1. vCow balance
2. Cow balance + vested vCow balance
3. Historically based balance of (1) or (2) in the last 30 days
- based on the lowest value (user buys one day and need to hold for 30 days in order to get the full subsidy)
- based on the average value (user buys one day and his subsidy increases linearly each day until full subsidy is reached after 30 days)
4. Staking contract

Interesting metrics could be:
1. Number of trades with subsidy / number of total trades.
2. Average subsidy for all accounts that traded.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1737 by @sunce86

**Comment by MartinquaXD** [comment]
Deciding these tokenomics is not the responsibility of the backend. Once something has been decided we can create issues to capture the specific work.
Also subsidies based on token ownership has not been a thing for quite some time.
