### ISSUE TITLE
Also get token info for tokens exclusively part of the liquidity

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1255]
Right now the driver already populates some [meta data](https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/api/routes/solve/dto/auction.rs#L17-#L30) about tokens in the auction.
However, this happens before the driver collects liquidity. Because we can basically add arbitrary liquidity we might add a few tokens which don't already have an entry in the token meta data.
This poses a problem for Quasimodo because it expects the `token` list to contain an entry for every token it could possibly encounter while computing a solution.

The concrete suggestion would be to only add the token meta data after we collected liquidity so we actually know about all the tokens in the auction.

There is already a [workaround](https://github.com/cowprotocol/services/pull/1251#discussion_r1114998729) in place for that to avoid crashing Quasimodo but we currently only default initialize data for tokens which is only contained in liquidity.

**Comment by vkgnosis** [comment]
How important is token information for Quasimodo? I think it might only be used for better debugging. This matters for how urgent this issue is and whether we need to filter out orders and liquidity for which we can't fetch token info.

**Comment by MartinquaXD** [comment]
Actually the meta data itself doesn't matter at all for Quasimodo AFAIK. It just has to be able to find the key in the `HashMap<Token, Info>` struct to not trigger an exception. Quasimodo can deal with `null` values in `Info` but not with the entry missing altogether. That's why the workaround I already implemented should be good enough for now.
It just pointed out that we currently build the token info when we don't yet know all the tokens that will end up in the auction.

**Comment by vkgnosis** [comment]
If Quasimodo doesn't need it at all, then why do the work of getting any token info for it?

**Comment by nlordell** [comment]
I am also OK with removing this if we don't make use of metadata. It accounts for a large amount of `eth_call`s that I don't think we need to do by default.
