### ISSUE TITLE
Verify On-Chain Liquidity for Internal Buffer Usage

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#126]
This PR captures the necessary work to allow our optimization solvers to specify on-chain liquidity equivalent to some internal buffer swap.

These internal buffer swaps need to to have some on-chain liquidity equivalent on the auction block for them to be considered "valid" - so the driver should verify this before submitting settlements that use internal buffers.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1740 by @nlordell

**Comment by MartinquaXD** [comment]
Other than the bare minimum required for maintenance we should no longer add new features to solvers maintained by us.
