### ISSUE TITLE
Don't report exact toml deserialization error

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1266]
Although I initially suggested that we should print the exact error encountered while parsing the new toml config files (to make debugging easier) this can leak sensitive data with specific format errors.

Best to not print the exact parsing errors to avoid having to rotate solver keys after misconfiguring something. 😅

**Comment by vkgnosis** [comment]
That's pretty unfortunate. In general we want better error messages but they can print secrets.
