### ISSUE TITLE
Expose Solution Competition Externally

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#127]
This _epic_ issue captures the work to make solver competition be visibly externally (and not just be private to the driver).

There are currently two approaches for tackling this:

### The Easy Way

The easiest, and least invasive approach, would be for the `driver` to have some blessed "api-key" and be allowed to store settlements in the orderbook.

This way, the driver could:
1. Collect all solutions from our current solvers
2. Perform local solver competition (so filters out the settlements that fail transactions)
3. Call `POST api/v1/solution_competition` with some "solution competition data" including the full auction (or an auction ID - but this would require storing the auctions some other way) as well as each "successfully simulating" solution, 

### The Hard Way

The harder and more invasive way to make this change would be to move settlement competition entirely to the orderbook API. In this model, the driver would submit settlements directly to the orderbook API and have it be responsible for verifying the settlements as well as determining the winner.

This is a more involved change as it would require:
- Closing auctions (i.e. building an auction and then recording it as "finalized" with some ID attached to it). The reason for this is to ensure multiple consecutive calls to `api/v1/auction` should return the same orders and prices! This is to allow things like driver-restarts mid auction, as well as multiple external drivers (decentralized future 😄 🤖).
- Have a way for settlements to "refer" to some existing auction at a database level (so you can query auction + settlements for ID `42` and get all orders that were included plus all settlements that were submitted and, if the auction is done, which one won and which one is on-chain)
- Either move settlement submission component into the `orderbook` or a separate `submitter` pod that queries the orderbook API for new settlements and just executes them on-chain as the driver does currently.

All in all, this is quite a bit more work but fits more nicely into our "decentralized future".

> Original issue https://github.com/gnosis/gp-v2-services/issues/1741 by @nlordell

**Comment by vkgnosis** [comment]
Currently we auto scale the api pods but this doesn't fit the model where we have a canonical auction id and get settlements posted to us. I'm wondering if we should drop the scaling because there is not much work done by the pod itself. Most is forwarded to the database or ethereum nodes. This would simplify our setup and the design.

**Comment by sunce86** [comment]
This is implemented long ago.
