### ISSUE TITLE
Remove submit_slot_transaction when not needed anymore

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#128]
Discussed here to remove the `submit_slot_transaction` call: https://github.com/gnosis/gp-v2-services/pull/1738#discussion_r831066827

For now let's keep it in the code, since I will build Eden automatic builder and test if we can own a slot in the next months (at least for a part of the time).

Opening issue just so we don't forget about this.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1751 by @sunce86

**Comment by josojo** [comment]
Just as a side note, the implementation is also no longer working:
https://logs.cow.fi/goto/d35abe30-2470-11ed-bc72-a56ba304fbef
We are using eth_sendSlotTx but only eth_sendSlotTxs is supported.

**Comment by MartinquaXD** [comment]
Eden is no longer used.
