### ISSUE TITLE
Partially Fillable Limit Orders

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1280]
# Partially Fillable Limit Orders

This epic tracks the total work required for implementing partially fillable limit orders.

## Introduction

Late last year, we added preliminary support for limit orders. This initial implementation worked by having the autopilot attach protocol- determined fees to each order, that would be taken from order surplus. This allowed an initial version to be implemented that would not require changes to any of the existing solvers (either Gnosis operated solvers, or any of the external solvers). The `solver` crate would be responsible for computing synthetic "normal-orders" that are indistinguishable from market orders for each limit order, and also be responsible for correctly encoding them into a settlement such that exactly the protocol-computed surplus fee would be deducted from them.

Now, we want to extend the current limit orders feature to also support partially fillable limit orders. This work can be split into 3 major milestones:

1. Accepting partially fillable orders into the orderbook, and include them when building auctions.
2. Modify the solver API to allow HTTP solvers to specify a partial limit order execution, **including the executed surplus fee**.
3. Add basic support to the Gnosis solvers for dealing with partially fillable limit orders.

## Risks

We should be mindful of the co-located driver when implementing these changes. Every change to the `solver` would also need to be ported to the `driver`.

## Milestone 1

The first milestone would be to add support for getting partially fillable limit orders into the orderbook. For this milestone, we don't actually need to solve for them.

- [x] #1288
- [x] #1289
- [x] #1290

## Milestone 2

The second milestone would be to accept and encode partially filled limit orders in the `solver` and `driver`.

- [x] #1322
- [x] #1323
- [x] #1324

## Milestone 3

The third milestone is around adding support to existing solvers for partially fillable limit orders. In order to drive external solvers to implement this, there needs to be sufficient support in existing Gnosis solvers. The assumption is that this will attract users to placing partially fillable limit orders, which will increase how much potential observed value can be extracted from them
and incentivize the external solvers to also add support for them.

- [x] #1291
- [x] ~~Add support to the Naive solver for partially fillable limit orders~~. **WON'T FIX**.
- [x] #1292
  - **Note**: This may require research on the "best approach" for doing this. A naive one would be to binary search on the fill amount and try to find some partial fill that works. However, some DEX aggregator APIs report price impact for a trade, this can be used for more accurately searching for the optimal fill amount for a partially fillable limit order.
  
## Additional Work

- [ ] #1378
- [x] #1402
- [x] #1403

**Comment by fleupold** [comment]
Complete
