### ISSUE TITLE
Include Partially Fillable Limit Orders in Auctions

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1290]
Given partially fillable limit orders that appear in the orderbook, we should add them to the auction if:
- They have a native token price
- There is sufficient balance for _partially_ filling the order

Note that we should make sure that the existing knobs we have for hedging risk of growing orderbook size (such as filtering limit orders based on limit prices using the reference native token prices) should also apply to partially fillable limit orders.

This will also likely require some internal refactoring, as we don't need surplus fees for all orders of class `"limit"`, but only the fill-or-kill kind.

**Comment by vkgnosis** [comment]
Is there anything that needs to be done with regards to the risk adjusted rewards for orders? In `risk_adjusted_rewards.rs` we hardcode 0 if the order is a liquidity order or partially fillable.

**Comment by nlordell** [comment]
> Is there anything that needs to be done with regards to the risk adjusted rewards for orders?

No. In theory, there should be a reward for these, but we are moving to the CIP-20 style scoring/payouts and explicitly decided not to figure out how to compute risk-adjusted rewards for these order types (since CIP-20 is likely to be in place before partially fillable limit orders).

**Comment by vkgnosis** [comment]
Partially fillable limit orders are included in the auction but only if the balance is large enough to completely fill the order. See #1317 .

**Comment by nlordell** [comment]
Closing in favour of #1378 which is specific to the remaining work.
