### ISSUE TITLE
Additional JIT order validation in the `driver`

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#1304]
The rules are:
- If a JIT order has the `partially_fillable` flag set, then the `executed` amount can be smaller than the actual `buy` or `sell` amount.
- If the flag is not set, then the `executed` amount has to be equal to the target amount of the order (`buy` amount for buy orders or `sell` amount for sell orders).

The `domain::order::Jit` object should reflect these invariants at the type-level, if possible.

**Comment by MartinquaXD** [comment]
Btw, the same logic should probably apply to any order type (not just JIT) as they all can be either fill-or-kill or partially fillable.
