### ISSUE TITLE
Possible improvements to the test framework

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#1306]
The tests need to be easy to write and work with, otherwise people will be reluctant to write them. We want to have many tests exercising many different edge cases, and with the current state of affairs I think people will be unlikely to want to write tests. I recently spent an excessive amount of time debugging some settlements that were failing simulation during testing. Debugging this involved changing the code to actually publish the settlement instead of simply simulating it and using `debug_traceTransaction` and looking for `LOG2` opcodes to see which logs would have been emitted. I also had to go change the `GPv2Settlement` contract in the [contracts](https://github.com/cowprotocol/contracts) repo to emit more debug events. Figuring out the hash of the event is also error-prone. Needless to say, this is an abysmal development experience.

Here are some improvements which need to be made:

- It's absolutely crucial to have all of our tests able to run both locally and on Tenderly, and the Tenderly experience needs to be smooth. (I.e. the tests should upload all the ABIs to Tenderly so that the debugging functionality actually works, and the number of simulations needs to be minimized to avoid running into rate limits. One easy way to reduce the number of tenderly requests could be to batch the entire setup into a single transaction, if possible. Running on tenderly instead of locally should be as simple as specifying a different configuration flag or similar.)
- It would be nice to make it hard to make silly mistakes when writing tests. The test framework should take care of the following for you so that you don't need to remember to do it:
  - Keep the orders for the mock solver in sync with the orders that you're actually passing to the /solve endpoint.
  - Keep all the signatures in sync with the orders.

These ideas can be applied to `driver`, `solver`, and `e2e` test suite.

**Comment by cowfee** [comment]
Closed via https://github.com/cowprotocol/services/pull/1348 and https://github.com/cowprotocol/services/pull/1549.
