### ISSUE TITLE
Add a quote ID

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#131]
One idea from @anxolin would be to add an `id` field to our `api/v1/quote` replies to make it easier to identify them as well as debugging issues reported by users and the FE.

Additionally this can be passed into Quasimodo similar to how we pass in auction IDs now since #1762.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1764 by @nlordell

**Comment by anxolin** [comment]
Nice! I connected it to the issue from the frontend.
@nlordell do you have one issue for reporting the slippage together with the other order information? (so i connect it too)

**Comment by anxolin** [comment]
> I think we should be able to compute the slippage from the quoted price to the order's limit price (that way there is less to pass in. WDYT?

Sorry i missed this. Yes, agree. It depends on which implementation we decide to do. But you are right that for a centralized one would be OK just with the ID. 


As we discussed in the sync before, I created a document to help with the definition and coordination https://docs.google.com/document/d/1N8K-ueKxxuuFfKjnegbPUYx30Qk1H8zjeiLo3jg-X14/edit#

**Comment by nlordell** [comment]
Created an issue #170 to add the work of adding `quoteId` field to the `POST orders` route.

**Comment by MartinquaXD** [comment]
@nlordell this can be closed by now, right?

**Comment by nlordell** [comment]
Yes, sorry. Thanks for cleaning up issues today 💪.
