### ISSUE TITLE
Optimize Native Token Unwraps

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1312]
The basic support for buy `ETH` orders in the new driver (#1311) is pretty suboptimal as multiple `WETH` unwraps could be collapsed into one to avoid the additional gas overhead. Linking the original [issue](https://github.com/gnosis/gp-v2-services/issues/1496) which added the same logic in the current driver that already contains all the required context.

**Comment by cowfee** [comment]
The `solver` crate implements this via the `PostProcessing` trait. This is done as part of `Solver::solve`, where the encoded settlement is "optimized" right before being passed to the solver. It's worth considering whether the new driver should simply include the optimizations as part of the settlement encoding process. (I think it should.)
