### ISSUE TITLE
Consider storing limit order surplus fees in separate table

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1313]
We group fok limit order surplus fee updates by `(sell_token, buy_token, sell_amount)`. All such orders' fees are updated together. The way this is currently implemented that in the orders table we change the values of  `surplus_fee,, surplus_fee_timestamp, full_fee_amount` for all matching orders.

This is inefficient because data is duplicated and updated more than necessary. It would be more efficient to store these values in a separate table, which is joined with the orders table. Then for each group only one value needs to be changed. 

This is especially important as we get more old orders. Currently we update these values for all orders, including orders that have already been settled or expired. In the future the ration of such orders to open orders increases and the updating becomes slower.

**Comment by nlordell** [comment]
I think this is a nice proposal and we should do it. It also paves the way for efficient "bucketing" of surplus fee computation.

**Comment by MartinquaXD** [comment]
Obsolete since we no longer compute surplus fess ourselves.
