### ISSUE TITLE
Do not send liquidity to specific solvers

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1334]
We need an option to skip sending liquidity to specified solvers.
This is [done for price estimation](https://github.com/cowprotocol/services/pull/1331), but we need it also for solving.

Concretely, I noticed that Barter solver is returning error `413 Payload Too Large` when we turned on UniswapV3:
https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/gaPoN

This is probably something that external solvers should handle, but wouldn't hurt to have. Therefore, low priority task.

**Comment by MartinquaXD** [comment]
IIRC we now have a flag for that in the new driver.
