### ISSUE TITLE
Make Univ3 baseline liquidity init to crash pod

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1336]
In case of initialization failure of UniswapV3 pool fetcher on app startup we just return `None` and continue.

This error appears as oncall alert:
`ERROR autopilot: failed to create UniswapV3 pool fetcher in autopilot: error decoding response body: expected value at line 1 column 1`

OnCall doesn't know what to do with this, nor how serious the error is. 

Either we need to fix fix this error internally in UniswapV3 contructor or we need to crash pod with `expect` and expect successful initialization in next startup.

**Comment by fleupold** [comment]
@nlordell was there a path forward discussed for this issue?
