### ISSUE TITLE
Allow external solvers to provide gas price for submission

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1350]
This would allow external solvers to start settlement submission with initially higher gas price compared to what would our native gas price estimator return.
Consequently, it would decrease chances of transaction revert.

**Comment by nlordell** [comment]
This should be solved with solver+driver co-location. We should instead push to get it out the door and allow solvers to configure and manage these kinds of settings themselves.

**Comment by sunce86** [comment]
Closing as not needed.
