### ISSUE TITLE
Index Balancer V2 "Composable Pool" Types

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1379]
> Did you check if we are able to index `composable stable pool` type of pool? Like this one:
> https://app.balancer.fi/#/gnosis-chain/pool/0xfedb19ec000d38d92af4b21436870f115db22725000000000000000000000010
>
> I was under impression that this is also a new factory type.
>
_Originally posted by @sunce86 in https://github.com/cowprotocol/services/issues/1376#issuecomment-1484642135_

Specifically, it might be low-hanging fruit to add new pool types (as long as they behave similarly to existing weighted/stable pools).

**Comment by MartinquaXD** [comment]
Done.
