### ISSUE TITLE
Multiple Fills are Unreliable

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1402]
I noticed while developing and debugging that multiple executions of a partially fillable order is unreliable. That is, there are issues in computing solutions for partially fillable orders that are partially filled with the baseline solver in particular (it may affect other solvers as well).

Fortunately, there is a reliable way to reproduce conditions where the computed settlement is invalid and fails to simulate.

In particular, apply this patch to the E2E tests:

```diff
diff --git a/crates/e2e/tests/e2e/partially_fillable.rs b/crates/e2e/tests/e2e/partially_fillable.rs
index d7b849aa..ad084b7b 100644
--- a/crates/e2e/tests/e2e/partially_fillable.rs
+++ b/crates/e2e/tests/e2e/partially_fillable.rs
@@ -81,7 +81,7 @@ async fn test(web3: Web3) {
         .with_sell_token(token_a.address())
         .with_sell_amount(to_wei(500))
         .with_buy_token(token_b.address())
-        .with_buy_amount(to_wei(390))
+        .with_buy_amount(to_wei(400))
         .with_valid_to(model::time::now_in_epoch_seconds() + 300)
         .with_kind(OrderKind::Sell)
         .with_partially_fillable(true)
@@ -112,16 +112,5 @@ async fn test(web3: Web3) {
         || async { token_b.balance_of(trader_a.address()).call().await.unwrap() != 0.into() };
     wait_for_condition(TIMEOUT, trade_happened).await.unwrap();
 
-    // Expecting a partial fill
-    let sell_balance = token_a.balance_of(trader_a.address()).call().await.unwrap();
-    assert!(
-        // Sell balance is strictly less than 250.0 because of the fee.
-        (249_999_000_000_000_000_000_u128..250_000_000_000_000_000_000_u128)
-            .contains(&sell_balance.as_u128())
-    );
-    let buy_balance = token_b.balance_of(trader_a.address()).call().await.unwrap();
-    assert!(
-        (199_000_000_000_000_000_000_u128..201_000_000_000_000_000_000_u128)
-            .contains(&buy_balance.as_u128())
-    );
+    tokio::time::sleep(std::time::Duration::from_secs(u64::MAX)).await;
 }

```

And execute the test:
```
cargo test -p e2e -- --ignored --test-threads 1 --nocapture local_node_partially_fillable
```

This causes the Baseline solver to produce an invalid solution which should never happen:
```
2023-03-30T14:14:21.673Z  WARN auction{id=1093 run=3}: solver::driver_logger: BaselineSolver settlement simulation failed at submission and block 252:
```

**Note that this _may_ be unrelated to partial fills, but it is worth investigating.**

**Comment by MartinquaXD** [comment]
The changed buy amount of the provided patch didn't seem to produce any other result for me compared to the regular buy amount.

What I observed (with and without the patch) doesn't appear to be a bug in the partial fill logic or the baseline solver. The pattern of failed solutions looks like this:
1. return a working solution and settle it
2. produce 2 - 3 failing solutions
3. return a working solution and settle it
3. produce 2 - 3 failing solutions (and on and on)

The computed amounts all looked correct to me so I started logging at which block we collected the liquidity from. That revealed that for the failing solutions we queried the liquidity from the same block as for the previous working solution. This means even after we already settled a partial fill we still computed solutions based on outdated liquidity for a while. Whenever we indexed the liquidity of the correct block we returned a working solution.
