### ISSUE TITLE
Handle partially fillable order balance in colocation

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1408]
In https://github.com/cowprotocol/services/pull/1406 this was implemented for non co location. For colocation we aren't yet passing the balance information in the auction and it's not used in the colocation driver.

**Comment by vkgnosis** [comment]
Email me at valentin at cow dot fi .

**Comment by vkgnosis** [comment]
Note the PR linked above this message.

**Comment by fleupold** [comment]
This has been implemented
