### ISSUE TITLE
Confusion about single order solver surplus fee logic

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1421]
Take the example at https://github.com/cowprotocol/services/blob/99692011ab996863c1c11633e53abd3d33da1abe/crates/solver/src/solver/single_order_solver.rs#L950

```rust
assert_eq!(
            trade(settlement(order(OrderKind::Sell), 100, 110).unwrap()),
            TradeExecution {
                sell_token,
                buy_token,
                sell_amount: 100.into(),
                buy_amount: 108.into(),
                fee_amount: 2.into(),
            }
        );
```

We have a swap that will trade 100 sell for 110 buy. From the user we take 100 and give them 108. This means we are taking the fee from the buy token. But didn't we want to take fees only from sell tokens?

**Comment by MartinquaXD** [comment]
@nlordell brought up taking fees from the buy token [here](https://cowservices.slack.com/archives/C036JAGRQ04/p1680066919739089) due to some complications with partial fills. I think it's worth having a broader discussion about that as it seems to have been decided pretty ad-hoc.

**Comment by nlordell** [comment]
> But didn't we want to take fees only from sell tokens?

The `fee_amount` is always transferred in by the from the `sell_token`, this is guaranteed by the smart contract. **However**, it is possible for surplus fees to be taken in either buy or sell token.

In an **unrelated** note, note that that the transferred in `fee_amount` can be converted to `buy_token` at the solver's discretion. This property can be very useful from a solver perspective. Imagine settling an order:

1000000 SHITCOIN + 1000 SHITCOIN fees -> 1 WETH

No, the solver can:
1. Swap 1000000 SHITCOIN -> 1 WETH against an AMM, and be left with 1000 SHITCOIN collected in fees
2. Swap 1000000 + 1000 SHITCOIN -> 1.001 WETH against an AMM, and be left with 0.001 WETH collected in fees

This property can therefore be used to shift fees into trusted tokens and used to reduce inventory risk.
