### ISSUE TITLE
Collect more data on who provides the winning price estimate

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1428]
### General Idea

It would be great to have some sort of estimate about how confident we are that we actually found the best quote for a given trade. If we detect a lot of quotes where we with high confidence didn't return the best price we could issue an alert.

What I'm thinking about would be to let the `CompetitionPriceEstimator` keep track of which estimator wins how often per `(sell_token, buy_token, order_kind)`. If, for example we see that `1Inch` provides the best quote for `(usdc, usdt, sell)` 90% of the time and some rate limiting error prevents it from submitting a price this time we could be 90% confident that we didn't give the user the best price.

If enough of these high confidence missed quotes pile up we could say with high confidence that on average our end users are having a degraded experience.

### Notes

This is just an idea and probably requires a bunch of research. For example it's not clear that `(sell_token, buy_token, order_kind)` is all the data needed to predict the winner. It could be that different estimators perform better for low and high volume trades.

Also if the system works really well we could even consider to not send requests to estimators where we are 95% sure it would lose. There are for example tokens that can only be estimated by a single API (looking at you yearn). For those tokens it doesn't make sense to spam the other estimators.

We should only record the outcome for an estimator if it actually provided a quote (not when it's returning internal server errors, or rate limiting errors).

**Comment by nlordell** [comment]
Very neat idea.
