### ISSUE TITLE
Send 0x liquidity to Quasimodo for price estimates

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1433]
[Slack](https://cowservices.slack.com/archives/C0375NV72SC/p1681743780128319)

They mentioned that there exists 0x liquidity for this token already, however it’s not being picked up by our price estimates. From reading the code, it looks like we aren’t sending any 0x liquidity to Quasimodo for price estimates. Would it be possible to include these orders in the instance file we send Quasimodo for quotes (maybe even in the baseline price estimator if they are partially fillable)? Given that they are technically liquidity orders that execute at limit price, I don’t imaging this making the algorithm much “harder”.

**Comment by MartinquaXD** [comment]
Can be closed in favor of https://github.com/cowprotocol/services/issues/1666.
