### ISSUE TITLE
Outdated Docs.

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/services#1436]
https://github.com/cowprotocol/services/blob/38013f5104b5fcbe403f6060ef96b67fa59d939f/crates/orderbook/openapi.yml#L1050-L1053

I think these required fields are out of date.

**Comment by MartinquaXD** [comment]
@mfw78 I remember you going over the docs in detail. I assume this can be closed (or rather marked as `wontfix` for now)?

**Comment by mfw78** [comment]
> @mfw78 I remember you going over the docs in detail. I assume this can be closed (or rather marked as `wontfix` for now)?

FYI, the model will be strictly enforced on the completion of https://github.com/cowprotocol/pm/issues/23.
