### ISSUE TITLE
Observed fees set to zero

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#1437]
Fees seem to not be computed correctly, potentially due to this method not treating market orders correctly:

https://github.com/cowprotocol/services/blob/38013f5104b5fcbe403f6060ef96b67fa59d939f/crates/autopilot/src/decoded_settlement.rs#L263

**Comment by MartinquaXD** [comment]
@nlordell I see that you opened a PR for this already. Thanks for that.
But don't you think we also need to ensure we store all the `solver_fee`s in the DB to make sure that the we have the correct value for `solver_fee` [here](https://github.com/cowprotocol/services/blob/main/crates/database/src/orders.rs#L567)?
AFAICS we might also have to have a single use script to set the missing `solver_fee` values in the DB by looking at the auction data we stored with S3 and re-index the settlement tx from last week.

**Comment by nlordell** [comment]
Sorry, I missed your comment somehow.

I checked the DB and the last auction for which there are null `solver_fee` values is [38 days ago](https://etherscan.io/tx/0x2efb43352a27ba4ce35dd930e39eb4e7ff870aa25ae4b8f2b9b2d67af9b5d76b). I imagine that this is a product of changes that happened during the CIP-20 implementation.

```
mainnet=> select max(auction_id) from order_execution where solver_fee is null;
   max   
---------
 5820526
(1 row)

mainnet=> select * from auction_transaction where auction_id = 5820526;
 auction_id |                  tx_from                   | tx_nonce 
------------+--------------------------------------------+----------
    5820526 | \xa21740833858985e4d801533a808786d3647fb83 |    32168
(1 row)

mainnet=> select * from settlements where tx_from = '\xa21740833858985e4d801533a808786d3647fb83' and tx_nonce = 32168;
 block_number | log_index |                   solver                   |                              tx_hash                               |                  tx_from                   | tx_nonce 
--------------+-----------+--------------------------------------------+--------------------------------------------------------------------+--------------------------------------------+----------
     16817782 |       278 | \xa21740833858985e4d801533a808786d3647fb83 | \x2efb43352a27ba4ce35dd930e39eb4e7ff870aa25ae4b8f2b9b2d67af9b5d76b | \xa21740833858985e4d801533a808786d3647fb83 |    32168
(1 row)

```

The last auction with `solver_fee = NULL` in staging is even further back (46 days ago).
