### ISSUE TITLE
Add An `additional_flashbots_absolute_tip` Configuration

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1449]
This PR captures the work for adding an additional absolute tip (in addition to the existing additional relative tip configuration option) for controlling the `max_priority_fee_per_gas` in the transaction.

**Comment by sunce86** [comment]
This is done I think, by adding `max_additional_tip` here https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/config/file/mod.rs#L108

**Comment by sunce86** [comment]
Reopen, since we agreed to set to `wontfix` instead of closing.
