### ISSUE TITLE
Prepare http solver auction instance before determining the deadline

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1461]
The `Yearn` team mentioned that sometimes their solver times out because the deadline is not always constant.
Overall I think it's up to the team to fit inside the time window but I agree that it would be helpful if the time to solve is always constant.
Right now this is not the case because the `HttpSolver` has to build an `Instance` (`instance.json`) before sending it to the solver URLs. This process does not always take the same amount of time and it would probably be good if we could do that before determining the auction deadline.
This would have 2 possible outcomes:
1. if we want to give gnosis solvers (that don't need that additional work) the same amount of time as before the time between settlements will increase by ~1s
2. gnosis solvers would have slightly less time to compute a solution

I think both outcomes are fine because the variance is not so big right now but I wanted to bring it up regardless.

**Comment by vkgnosis** [comment]
I'm unsure if this is worth doing. As you said, solvers need to be able to handle the deadline. They will always need some code to make sure that they return within the deadline even if that means cutting some computation short. Whether the deadline changes per call to the solver or is a hardcoded constant doesn't change this. But it is more robust to use the deadline from the request. If we rely on hardcoding 30 seconds then it would be a huge hassle to change this later. Also with colocation the deadline definitely has some variation.

**Comment by Gelato-B2B** [comment]
Good day. 

My team and I are building a solution on top of CoW - https://docs.google.com/presentation/d/1npKvDYhcinaqmlCT6zjjIW1Ykg66tURY-kebeD0dKMY/edit?usp=sharing 

We believe that there is value in giving solvers a well defined time limit to supply a solution and let them know immediatly who the winner is after the limit is reached. This would  allow for a better way to plug in all sorts of RFQ based systems such as what we are building. 

For example, in our case market makers are asked to provide the best price they can give in response to CoW order. As market makers have to pre commit to a certain price, they will have to add some margin to cover their risks which results in cow users getting worse prices than what they could potentially get. Narrowing the timeframe between a) maker having to pre commit to a certain price and b) maker receiving confirtmation on whether he got to settle the trade  would basically mean better prices for CoW users in the end. 

At least this is how we view it. I wonder, does CoW currently support any type of RFQ based liquidity? If not, is there a general interest in plugging in such liquidity to optimize pathfidning?

**Comment by MartinquaXD** [comment]
Becomes irrelevant with solver-driver colocation. Auction pre-processing will be the responsibility of the solver so we'll no longer be able to pick deadlines with that in mind.
