### ISSUE TITLE
Return multiple solutions from solvers to the driver

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1464]
It would be more ergonomic for solvers which use the driver to be able to return multiple solutions when their driver calls `/solve`. The driver would then validate solutions **and filter out** the invalid ones. It would then score the solutions and publish the best-scoring one. This allows some solvers to completely omit logic for validation and scoring. Other solvers might still prefer to include their own validation and/or scoring logic so that they can optimize their solutions.

The API between the driver and solver needs to change. The meaning of "solution ID" and "settlement ID" also needs to change. This is what the flow will look like:

- The driver calls the solver `/solve` endpoint.
- This endpoint returns multiple solutions. Every solution has a solution ID which is unique within the response.
- The driver picks a solution, generates the _settlement ID_ (which we previously referred to as "solution ID," but the term "solution ID" has a slightly different meaning now, due to the bullet point above), and embeds the settlement ID in the settlement.
- If it wins the competition, the driver publishes the settlement.

The score and validity of each solution needs to be logged from the driver. Tenderly simulation links should be included to ease debugging. The solvers can query the autopilot and the driver logs to understand exactly what happened and why.

**Comment by harisang** [comment]
Comment/clarification from an outsider. The above would imply that the driver component is actually the one that is aware what constitutes a "good/competitive" solution, while the solver component is oblivious to that and acts more like a router that attempts to generate feasible solutions.

I am not saying this is good or bad, but just want to understand if we want to think of the driver as being the one evaluating the quality of each generated solution, while the solver just generates candidate executions without being able to internally evaluate which one to choose.

**Comment by nlordell** [comment]
> The above would imply that the driver component is actually the one that is aware what constitutes a "good/competitive" solution

In our design, the driver is aware of what is:
- A valid solution
- How to estimate an observed value similar to how we do now.

I agree that under CIP-20, the second point may be not exactly what we want, but that is a larger change and orthogonal to this feature IMO. With CIP-20 in mind, I would expect the driver to do the same validation it does today (i.e. preventing solvers from foot-guns) and just pick the solution with the highest reported score from the solver engines instead of estimating what the settlement observed value will be (like it does today).
