### ISSUE TITLE
Verify and score quotes in the `driver`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1468]
The quoting process relies on the solving process. Generating a quote from the driver involves requesting the solver to generate a solution to a "synthetic order," which is a fake order that trades the assets that the user wants to get a quote for.

The solver can return multiple solutions. Before using these solutions for anything, the driver needs to verify that they are valid (i.e. that they can actually execute) and it needs to pick the best one among them (according to some criteria). During the quoting process, verifying is difficult because the synthetic order is fake: it isn't signed and the `from` value is also fake, i.e., it's not guaranteed to have any funds. So this synthetic order, in this form, can't be simulated. OTOH, picking the best quote is easy, since the best quote is simply a valid quote which gives the user the best price.

Therefore, the problem statement comes down to: how do we verify that the solutions generated for quotes are correct? I.e., how do we simulate the solutions that solve synthetic orders?

**Comment by MartinquaXD** [comment]
Quote verification has to happen in the `autopilot` / `orderbook` anyway so we might as well not implement it in the `driver`.
