### ISSUE TITLE
Config value for solving timeout in the `driver`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1474]
When the driver receives solutions from the solver, it spends some time verifying the solutions and scoring them. This will take longer depending on how many solutions are returned.

The driver [allocates less time to the solver](https://github.com/cowprotocol/services/blob/af238e136ffff21ee927c600a222ad786cd498e4/crates/driver/src/domain/competition/auction.rs#L73-L76) than the actual auction deadline so that there's enough time for the driver to do verification and scoring. However, the time buffer for verifying and solving is hardcoded to 1s. For solvers which return a large number of solutions, this might not be sufficient. The time buffer should be configurable per solver and the solvers should be able to set it based on empirical data.

The time buffer needs to also be used when calculating the solution merging timeout. See https://github.com/cowprotocol/services/issues/1498.

The driver should trace (log) the time needed to verify and score solutions to give guidance to the user as to what the time buffer should be configured to.

**Comment by fleupold** [comment]
Covered by #1498
