### ISSUE TITLE
Merge solutions in the driver

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1477]
Since the driver is responsible for scoring and verifying all solutions returned by a solver, the driver should also be responsible for merging together those valid solutions which can be merged. This should be done after the invalid solutions have been filtered out and before the scoring.

The `solution` field should probably be removed from `Settlement` and instead a field such as `solutions: Vec<solution::Id>` should be added. This is because multiple solutions can be encoded into one settlement due to merging, and the settlement doesn't really need to know about the solution data. It only cares about the IDs, and even that is just for observability.

For now, the merging process will rely on the legacy code from the boundary. The work required to refactor this code is defined in https://github.com/cowprotocol/services/issues/1478.

**Comment by MartinquaXD** [comment]
> This should be done after the invalid solutions have been filtered out and before the scoring.

In order to filter out invalid solutions we already have to filter them which gives us scoring for free. Also having a score attached to valid settlements will give us a good idea which settlements might be worth merging.
But of course we still have to ensure that newly created merged settlements are also scored.

**Comment by cowfee** [comment]
> In order to filter out invalid solutions we already have to filter them which gives us scoring for free.

@MartinquaXD Filtering (verifying) does not give scoring for free.

**Comment by MartinquaXD** [comment]
Maybe my wording was bad. I meant that going from an unverified solution to verified solution is a lot of work because we have to do simulations which takes time. But going from a verified solution to a scored solution is basically free as it doesn't even do any heavy logic or network calls.
