### ISSUE TITLE
Enforce uniform clearing prices for user orders

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#148]
We want to enforce that normal user orders (not liquidity) actually get uniform clearing prices from the solvers. This would happen in the driver before solution ranking so that solutions that don't do this are discarded.
This is important for allowing external solvers to participate.

**Comment by vkgnosis** [comment]
Looked into this. This is already enforced because our Settlement struct stores a HashMap<H160, U256> for the user order prices making it impossible to not have uniform clearing prices.

**Comment by sunce86** [comment]
Since solvers are forced to return `Settlement` I believe you are right.

**Comment by MartinquaXD** [comment]
With that hashmap the mapping from token to price should indeed be consistent.

**Comment by fleupold** [comment]
Closing, since this is already the case
