### ISSUE TITLE
Parallelize settlement merging

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1483]
The settlement merging process is IO-bound, since it needs to simulate the merged settlement, which requires an HTTP request. Use [`dashmap`](https://lib.rs/crates/dashmap) (or something else) to maximize IO-bound concurrency in the settlement merging process. For example, perhaps a task should be spawned for each settlement which attempts to merge it with every other settlement that succeeds it, inline in the dashmap.

**Comment by fleupold** [comment]
We now have a pipeline approach that should be "good enough"
