### ISSUE TITLE
Redesign external solver api

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#149]
To integrate external solvers we have so far by way of least resistance chosen the http solver interface. This interface is mostly ad hoc designed for whatever was easy to work with for the original http solvers but not necessarily the best api. We should redesign it before people start programming towards a bad api that is going to be harder to change later.

**Comment by vkgnosis** [comment]
We are going to first run with the current api then do the redesign later with the help of feedback from external solver creators.

**Comment by nlordell** [comment]
100% agree.
