### ISSUE TITLE
Don't rely on legacy code for solution scoring in `driver`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1494]
At the moment, `Settlement`s are [scored](https://github.com/cowprotocol/services/blob/ccd7edf33ec510c6d2690e8c4691b841d198a9b7/crates/driver/src/domain/competition/solution/settlement.rs#L117-L126) by calling into the legacy code. Ideally, the scoring code would be in `driver`, and the `score` method would be defined on the `Solution` type, not `Settlement`.

**Comment by fleupold** [comment]
Not quite done yet (we still need to remove the conditional logic once CIP-38 is live)
