### ISSUE TITLE
Individual surplus fees via the API

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#1502]
I would like to access surplus fees for partially-fillable orders for each auction where they were executed. This is necessary for monitoring for partially-fillable orders. At the moment this seems not be be possible from the orderbook api. Only the fee of the latest execution is shown (see #1500).

An alternative is to use the database directly. One downside to this is that the monitoring tool would depend on data which is not publicly accessible. This makes it more difficult to share, e.g., with solvers.

**Comment by MartinquaXD** [comment]
Would it make sense to start working on the monitoring tool by using the DB directly? Then you will know exactly which queries you actually end up using so we can later serve them by an endpoint.
This would also mean you are not blocked by the backend team waiting for the endpoint to be ready.
