### ISSUE TITLE
Ensure external http like solvers cannot break driver

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#151]
For example through things like timing out, sending large responses.

**Comment by vkgnosis** [comment]
@sunce86 @MartinquaXD Do you think there is another way of an external solver to break the driver? We already have timeouts and with the PR above we have response size limit.

**Comment by sunce86** [comment]
As Martin suggested few days ago, I would prefer to eliminate `unwrap` and `expect` from `Settlement` and `SettlementEncoder`.
This seems easier then writing a validation from scratch.

**Comment by MartinquaXD** [comment]
Yes, returning solutions which violate invariants leading to panics would be one way to mess with stability of the system.
With time and size limits already in place I hope `hyper` prevents or mitigates the remaining sophisticated low level attacks.

**Comment by vkgnosis** [comment]
Looked at all the unwrap and expects in those two modules. They seem fine. What is harder to tell is if we later rely on some unstated invariants that external solvers might violate.

**Comment by fleupold** [comment]
Seems like this issue can be closed (no longer relevant, investigation happened)
