### ISSUE TITLE
Remove Gas Price from Auction Input

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1514]
We used to pass around a `gas price` with the auction from the `autopilot` as this was important for scoring. Since the score is now computed by the solver as of CIP-20, it makes more sense for them to determine the gas price themselves (as this more accurately depicts the cost that they expect to incur). As such, gas price estimation should be done in the `driver` and `solver` binaries and not in the `autopilot` binary anymore.

**Comment by MartinquaXD** [comment]
Done.
