### ISSUE TITLE
Support `FactoryDisabled` event in Balancer factories

### ISSUE THREAD

**Issue by fedgiac** [cowprotocol/services#1515]
Balancer has disabled a few factory contracts, among which our `WeightedV3`:
- [mainnet](https://dashboard.tenderly.co/tx/main/0x162852c28f1384e670447cd1b4be99edd2fd48a5e9a324500888cd9933873c32/logs) (`0x5dd94da3644ddd055fcf6b3e1aa310bb7801eb8b`)
- [xdai](https://dashboard.tenderly.co/tx/xdai/0x75555a955fdf1d1962c563c4a282305fbd62e875feb3992284d2974bf3875132/logs) (`0xc128a9954e6c874ea3d62ce62b468ba073093f25`)

This caused our indexing to fail because the event `FactoryDisabled` isn't supported by our indexer.
I expect that there are two tasks associated to this issue:
- Indexing should not partially fail in case it encounters `FactoryDisabled` (or other uncommon events).
- Determine if `WeightedV3` will be reenabled, and if not remove it from the codebase.

**Comment by MartinquaXD** [comment]
I'm pretty sure they announced in our shared slack channel that `WeightedV3` will be permanently disabled but all their old responses have been deleted from the channel recently. :(

**Comment by nlordell** [comment]
We should not remove V3 from code, despite the factory being disabled, there are still pools from this factory that are supported. For example:

https://app.balancer.fi/#/gnosis-chain/pool/0x21d4c792ea7e38e0d0819c2011a2b1cb7252bd9900020000000000000000001e
