### ISSUE TITLE
Extend bad token test

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1516]
There was an [incident](https://cowservices.slack.com/archives/C0361CDD1FZ/p1684358106219619) where our internalization logic interacted with a strange token in an unexpected way.
The [WAGMI](https://etherscan.io/token/0xef8e456967122db4c3c160314bde8d2602ad6199) token had some logic that limits your transfer to the balance you actually have.
When our trade internalization logic tried to simulate the solution without onchain liquidity the `_transfer()` function then didn't try to transfer the expected amount but only 0 (which was the settlement contract's balance at the time). This caused the internalized simulation to pass but it changed the outcome for the user dramatically.

I propose to verify in the bad token check that if we try to transfer more than the address has balance for the call should revert. This would have marked the token as unsupported and would have prevented the weird interaction with the internalization logic.

**Comment by nlordell** [comment]
> the call should revert

It should revert or return `false` - both are supported by the settlement contract.
