### ISSUE TITLE
Better handling of start up crashes due to external services being unavailable

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1525]
Sometimes when we restart pods they panic on start up for while due an external service not being available. The ones I'm aware of happening recently are due to using the graph:

- failed to create Balancer pool fetcher: failed to execute query on subgraph, /src/crates/solver/src/run.rs:218:14
- innitializing Uniswap V3 pool fetcher: error decoding response body: expected value at line 1 column 1, /src/crates/orderbook/src/run.rs:296:14

Panicking isn't great because it is creates spammy logs and it just doesn't feel like the right response to an external service that could also stop working any time later after initial startup, which wouldn't cause a panic. I have the following ideas for how to improve this:

- On startup, don't unwrap but wait for the initialization to succeed, retrying it. Maybe with some time limit at which it panics anyway.
- Succeed start up but keep the component that needs initialization disabled. Meaning we wouldn't get balancer and univ3 pools until it gets initialized.

In either case we can have a metric that tracks initialization status too so that we can alert on it.

Edit: On the other hand, if the subgraph is only used during start up then the argument that the service could go away later doesn't hold. And it might be confusing to have some kind of liquidity enabled but it silently not working because the subgraph is down.

**Comment by nlordell** [comment]
> And it might be confusing to have some kind of liquidity enabled but it silently not working because the subgraph is down.

This is why we changed (UniV3 AFAIR) recently to panic on startup - it was to make explicit the fact that some liquidity was enabled but not working.

**Comment by vkgnosis** [comment]
Maybe the "wait for initialization up to to some time limit" is the best compromise then. We would print a message like "univ3 subgraph initialization has failed. retrying for up to 5 minutes.". When the 5 minutes are over, we panic.

**Comment by MartinquaXD** [comment]
> Maybe the "wait for initialization up to to some time limit" is the best compromise then. We would print a message like "univ3 subgraph initialization has failed. retrying for up to 5 minutes.". When the 5 minutes are over, we panic.

I think this is not a good idea. If we panic after a few minutes you have to be aware of this change or get surprised by logs in the alert channel. Also this would likely cause the pods to enter the ready state which probably means crashloop detection will not kick in and that we get lots of restarts which at least for the `autopilot` are somewhat costly.

So **if** we wait for some time the readiness check should be aware of that which makes things more complex again. And usually the graph has outages longer than 5 minutes anyway so we'll have to restart the system without anyway.
