### ISSUE TITLE
Refactor submission logic in new driver

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1543]
The driver currently uses the existing submission logic from the `solver` binary under the hood.
We recently noticed that MevBlocker's soft cancellation feature doesn't work very well with that logic. To address that issue we decided to do a very simple patch for the submission logic in the `solver` binary and do a proper fix by doing a bigger refactor/re-implementation of that logic in the new driver.
This issue captures the work for the changes in the `driver`.

**Comment by sunce86** [comment]
I am not sure what was the patch and what is the proper fix. Putting a question mark here.

**Comment by MartinquaXD** [comment]
This issues is currently not very specific/urgent. But there is still great potential for simplification (at the very least when we move to 1 block per auction). Closing for now.
