### ISSUE TITLE
Switch from Rinkeby to Sepolia/Goerli

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#155]
Ethereum 2.0 POS Merge will not be done on Rinkeby network, meaning we need to switch to another test network.
Ideally, this should be done before the merge is applied on Sepolia/Goerli so we could test our app on time - before mainnet merge.

**Comment by anxolin** [comment]
Related task for FE https://github.com/cowprotocol/cowswap/issues/416

**Comment by sunce86** [comment]
Decided to go with Goerli. We will first add Goerli, and have Goerli and Rinkeby both for some time and then remove Rinkeby when deprecated.

**Comment by anxolin** [comment]
We will need to coordinate also the deprecation works. 👍

**Comment by MartinquaXD** [comment]
Closing because the transition to `goerli` is complete and the `rinkeby` pods got deleted. #648
