### ISSUE TITLE
Change order replacement app data validation

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1550]
For the "replace order" functionality we check that the app data hash of the new order matches the "hash struct" of the old order. See [here](https://github.com/cowprotocol/services/blob/ac8439b194e010eee098cbf7b000523b0b466a22/crates/orderbook/src/orderbook.rs#L308).

This goes against the new app data format. We need to encode that into the full app data.

How widely used is order replacement? Does the frontend support it?

**Comment by nlordell** [comment]
> How widely used is order replacement? Does the frontend support it?

It does not.

I think the correct approach is to add a "replaces order" field in the back-end reserved app data.

**Comment by fleupold** [comment]
Fixed by #2441
