### ISSUE TITLE
Add tracing spans with current block number

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1552]
Requested on [slack](https://cowservices.slack.com/archives/C0375NV72SC/p1685642370617109)

To improve debugging it would be great to know in every log which block number the pod thinks the latest block is.
This is slightly different from the usual tracing spans because the value in the span might change during the lifetime of the instrumented future.
To get around this issue we probably have to implement a custom future that implements the [`Instrumented`](https://docs.rs/tracing/latest/tracing/instrument/struct.Instrumented.html#) trait.
Every time that future gets polled it needs to read the latest block from our block stream component (which should be very cheap) and store a tracing span inside itself. Afterwards it just has to enter the span and voila.
See regular `Instrumented` [implementation](https://docs.rs/tracing/latest/src/tracing/instrument.rs.html#269-273) for reference.

**Comment by vkgnosis** [comment]
I want to push back against this a tiny bit. We should be careful to not put too much into every log message. You can already find block number by looking for the log message that is emitted when it changes. No big deal either way though.

**Comment by fleupold** [comment]
> You can already find block number by looking for the log message that is emitted when it changes.

I think this is technically true for all non-concurrent information in the span (e.g. auction and run id), but for convenience and simpler filtering purposes we add them to the context. Finding out what block we were on and when the observed block changed is one of the most common debugging tasks I perform using our logs.
