### ISSUE TITLE
Prices service

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1555]
## Preface

In the CoW Protocol today, quotes are used for two very distinct use cases: to provide price estimates to the user indicating how much of one token they can swap for another token, and to provide a guarantee to the user that their trade will go through at a certain price or otherwise fail. The first use case (referred to as _price estimation_ from here on) is purely a UX feature, allowing our web page to display prices to the user interactively. OTOH, the second use case (referred to as _quoting_ from here on) is crucial to the correctness of the protocol, since the quoted prices are used when placing orders, and these orders will only go through if the prices are actually achievable.

Since these two distinct features are convoluted into the same `/quote` mechanism, this leads to problems like we've seen with the USDC depeg where incorrect _price estimates_ were used as _quotes_, leading users to place failing orders and cause a bad experience for them and real monetary costs for us.

For this (and other) reasons, we have decided that we will provide separate _price estimation_ and _quoting_ mechanisms.

## Price Estimation

The price estimation request will contain `sellToken`, `buyToken`, and exactly one of `sellAmount` or `buyAmount` (or simply `amount` and `side` depending on what we prefer, the two options are equivalent). The response will contain `sellAmount`, `buyAmount`, and `fee`. The `fee` will be denominated in the sell token.

Side note: this is different from our current quote API, which supports different selectors for how the fee would affect the estimate: `sellAmountBeforeFee`, `sellAmountAfterFee`, and `buyAmountAfterFee`. The CoW Swap FE only uses two: `buyAmountAfterFee` is used for buy orders, while `sellAmountBeforeFee` is used for sell orders. All these selectors can be applied by the client after calling into the API. The fee, which is expressed in the sell token, can also be converted into the buy token by the client by using the buy/sell ratio.

In the process of price estimation, the prices service will query estimates from a number of different estimators (e.g. baseline, uniswap, our own solvers, etc.) with a deadline, and the median estimate will be returned as the final estimate for the end user.

## Quoting

A quote represents a guarantee from the protocol that **an order** will go through at **a price** that is no worse than the quoted price. Therefore, the quote request will be the order itself, without exactly one of `sellAmount` or `buyAmount`, and the response will be the `sellAmount` or `buyAmount` that the protocol can guarantee.

The quoting system stays largely the same. The only difference is that now with the driver colocation, all quotes will be coming from solvers, and they will all include calldata which the autopilot will simulate in order to verify the validity of the quotes. Note that solutions still won't include calldata (i.e. the solution calldata stays secret up until the point when the winner publishes his settlement), to prevent the possibility of a winning solution being stolen from a solver.

## Decoupling

This is a good opportunity to decouple code and follow DDD practices. I would advocate for putting the price estimator code (including the HTTP routes) into a separate crate. The routes can be mounted as part of the orderbook, though conceptually, they don't _really_ belong there. They could also be mounted as part of a separate service. This is also appealing because, if something breaks down and the price estimation service becomes unavailable, the protocol will keep running. The FE can simply display a message to the user that estimates are not available, but still allow users to attempt to generate quotes. For this reason, my personal preference would be to run this as its own service.

**Comment by vkgnosis** [comment]
> I believe all these selectors can be applied by the client after calling into the API.

I think so too and I agree that the api user should do it.

> The `quality` field is a neat opportunity to also give the client an indication of how good this estimate might be.

I'd like to figure out how we intend api users to use this field. As in what specifically will they do that they can only do because they have this field.

**Comment by cowfee** [comment]
> I'd like to figure out how we intend api users to use this field. As in what specifically will they do that they can only do because they have this field.

The price estimate is just an indication to the user. The `quality` can also be an indication of how good the estimate is. Ultimately this field can be left out (it's not fundamental to the estimate in any way), I just thought it might be nice to have.

**Comment by nlordell** [comment]
> The fee will always be denominated in the buy token, and always be included in the buyAmount. (Alternatively, if we prefer, the fee can always be in the sell token. I believe the analysis which follows is analogous in both cases.)

Interesting. Why not have the fee in Eth? The reason we've done this in the past was to ensure things like minimum fee amounts in Eth denomination. It also allows us to apply more fine grained protocol level fee discounts to those indicative fees.

If we do go this route, I would always denominate the fee in `sellToken`, for consistency with how it is coded in the smart contract.

**Comment by nlordell** [comment]
> The quality field is a neat opportunity to also give the client an indication of how good this estimate might be.

I think there is a nice opportunity here to use internally to, for example, trust estimates from fewer sources (to reduce load on price estimators from a rate limiting perspective). I.e. we try estimating and get back a quality of "1", then there is no use to asking a slower/more aggressively rate limited price estimate API to improve the estimate (since the estimator source has high confidence in it).

I would like to define exactly how we intend on computing/using this better, but it is an interesting concept.

I would keep it out from the external price estimation API (I don't think we intend on showing this in the front end, so we shouldn't necessarily include it until we need it.

I would call it `confidence` not `quality` (at least, that is more close to what it represents in my mental model, but I may have misunderstood).

**Comment by nlordell** [comment]
> They could also be mounted as part of a separate service

I don't feel strongly either way, but my intuition is that it isn't worth splitting this into a separate process. That being said, there are some marginal benefits though (separate scaling rules, it can crash without affecting the `orderbook` process, etc.), so it _may_ be worth the work.

**Comment by nlordell** [comment]
One last thing worth considering: Do we have a separate component for native price estimates (i.e. estimating token prices in Eth) or do we piggy back on the price estimation service? Should this have separate routes?

**Comment by cowfee** [comment]
> Why not have the fee in Eth?

Because our protocol doesn't charge the fee in ETH. Ultimately the purpose of this "prices service" is to provide a nice UX for the CoW Protocol, and since the CoW Protocol charges fees in the traded token and not in ETH, it makes most sense to return the fee in one of the traded tokens. Thanks for letting me know that using the sell token makes more sense for consistency, will update the description.

> `quality` field

I've made a note to discuss this field on Monday. Your idea for it and mine are different, but I think both ideas are useful.

> there are some marginal benefits though (separate scaling rules, it can crash without affecting the orderbook process, etc.), so it may be worth the work.

Note: the only real "additional work" is the Pulumi infra code. In terms of the service itself, there's essentially no difference.

> My basic understanding is that this just be the quoting system we have today with required simulations (i.e. we get calldata from external drivers and simulate that to compute fees and prices).

Exactly! Will update the issue description to include this.

> Do we have a separate component for native price estimates (i.e. estimating token prices in Eth) or do we piggy back on the price estimation service?

I would definitely use the prices service for this. I don't think we need an additional route, just use `0xEEEE...EEEE` to denote ETH. Or maybe just use WETH? Is that an option?
