### ISSUE TITLE
Streaming estimates in the prices service

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1559]
It might be useful to allow prices to be streamed to the UI, where the UI opens a WebSocket and fetches prices via that WebSocket. As the price changes, the prices service can keep streaming the price for the same token pair and amount until the client requests a different token pair and amount (again, by sending a message on the WS connection). In terms of request overhead, this is an improvement over today's polling system. OTOH, WebSockets are less pleasant to work with due to being stateful (unlike HTTP requests which are stateless) and they can be more difficult to scale (e.g. pods can't be shut down while long-lived WebSockets are still open). (_Side note: can't we just document that WebSocket connections may periodically be closed by the server and require clients to re-connect? I'm pretty sure that with basically any WebSocket connection you can expect spurious shutdowns, so the client is in charge of reopening the socket in case anything goes wrong. So maybe there isn't any drawback after all._)

**Comment by nlordell** [comment]
Another similar technology that is typically used for pushing server -> client (where WS are a duplex communication) are server sent events.

**Comment by nlordell** [comment]
> can't we just document that WebSocket connections may periodically be closed by the server and require clients to re-connect?

👍

**Comment by fleupold** [comment]
Not a priority for now.
