### ISSUE TITLE
Better estimate selection in the prices service

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1560]
[The prices service issue](https://github.com/cowprotocol/services/issues/1555) describes how the prices service queries multiple external estimators and forwards the median estimate as the final estimate for the end user. Additionally, to improve the quality of the final estimate, outliers should be filtered out. The sensitivity of the filtering process can be configurable.

**Comment by fleupold** [comment]
Price estimation has been folded into colocation architecture (no plan to build a separate price service atm)
