### ISSUE TITLE
`driver`: test `user_fee` and `solver_fee`

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1561]
The `user_fee` and `solver_fee` order fields are currently untested.

The `solver_fee` only affects the score of the solution. Write a test with 2 identical orders, but one has a bigger `solver_fee`. The one with the bigger `solver_fee` also gives a higher score, so a solution for that order should be preferred by the driver over a solution for the other order.

To test the `user_fee`, assert that the `user_fee` remains in the settlement contract after settling an order with a non-zero `user_fee`.

**Comment by fleupold** [comment]
We do have unit tests for the score now, not sure we still want to add this test?

**Comment by sunce86** [comment]
We already use `solver_fee` for testing surplus fee calculated by the solver, while 'user_fee` will be dropped once we move to `all orders are limit orders` so I think we can close this.
