### ISSUE TITLE
Custom Order Interations Specified in App Data

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1573]
This issue captures the work to make the pre- and post- interactions tied to an order exclusively specified in the `fullAppData` instead of being specified as sidecar data.

The rationale for this change is that:
- It makes the verification of pre- and post- interactions being signed implicit (they are parsed from the app data and the app data is signed)
- It enables all smart contract orders that support custom `appData` fields to support pre- and post- interactions (essentially, they would upload the document containing pre- and post- interactions to IPFS/backend which will be fetched at order creation time)
- Future proofs smart contract orders to support other app data flags (for example, you would be able to have a "wait for CoW" TWAP order without requiring smart contract changes)

The work required for this is expected to be minimal on top of what is already planned for pre- and post- interactions.

**Comment by MartinquaXD** [comment]
Done
