### ISSUE TITLE
Time To Happy Moo SLI Implementation

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1582]
This issue captures the additional work for adding measurements required for computing a "time to happy moo" SLI.

We decided to implement this by creating an "event log" per order in the database, thus allowing us to re-construct the "time to happy moo" for a particular order.

1. Create a new `order_events` table for storing order event logs. This should be a simple table with:
   ```
   order_uid | timestamp | event
   ```
  - We should consider whether or not this should be a separate DB or schema, to avoid performance issues with our orderbook database.
2. Store events for each **market** order:
   - At order creation, store a `order_uid, now(), 'created'` log
   - During auction cutting, store a `order_uid, now(), $outcome` log, where the outcome can be any one of the outcomes for an order during an auction cut:
     - `'ready'`: the order is included in an auction and sent to solvers
     - `'filtered'`: the order is not included in an auction and is not being considered. This is for cases where an order was filtered because of protocol reasons and not because it was invalid. It **should count towards the time to happy MOO**.
     - `'invalid'`: the order is invalid, so it cannot be settled on-chain. This **should not count towards the time to happy MOO**.
   - On settlement competition updating, (i.e. when the driver posts the settlement competition to the `orderbook`)
     - `'executing'`: the order was included in the winning settlement and is being executed on-chain
     - `'considered'`: the order was included in a settlement that did not win
   - When a trade event happens, store a `order_uid, now(), 'traded'` log, this will correspond to the user hearing the "MOOOO" in the UI (as it is tied to the `order.status` field that is provided by the backend which uses this trade event).
   - At order cancellation, store a `order_uid, now(), 'cancelled'` log
3. Periodically clean up table (remove all events older than 60 days for example?) - exact parameters for clean up TBD.
   
### Open Questions ❓ 

- Should we also add an `auction_id` column to the logs?
  - My intuition is that this might be useful for debugging but *not* needed for the SLI, so I would keep it out this issue.
- Should we also add an `block_number` column to the logs?
  - Similar to above. We could, however, pivot the SLI to "number of blocks to happy MOO" where this would be useful, I would keep it out of this issue for now, but would be slightly more inclined to introduce this from the beginning.
  
### Sample Data 📈 

As presented in this issue, you can assume some sample data that looks like:

```sql
CREATE TYPE OrderEvent AS ENUM (
  'created',
  'ready',
  'filtered',
  'invalid',
  'executing',
  'considered',
  'traded',
  'cancelled'
);

CREATE TABLE order_events (
    order_uid bytea NOT NULL,
    timestamp timestamptz NOT NULL,
    event OrderEvent NOT NULL
);
```

<details><summary>Some sample data:</summary>

```sql
-- Order matched right away
INSERT INTO order_events
VALUES
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '2023-01-01 00:00:00', 'created'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '2023-01-01 00:00:02', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '2023-01-01 00:00:07', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '2023-01-01 00:00:10', 'executing'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000', '2023-01-01 00:00:19', 'traded');

-- Order that got cancelled after some time
INSERT INTO order_events
VALUES
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001', '2023-01-01 00:00:00', 'created'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001', '2023-01-01 00:00:02', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001', '2023-01-01 00:00:07', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001', '2023-01-01 00:00:12', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000001', '2023-01-01 00:00:14', 'cancelled');

-- Order that became invalid, but then eventually traded, not that only
-- a portion of its lifetime should contribute to the "time to happy MOO".
INSERT INTO order_events
VALUES
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:00:00', 'created'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:00:02', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:00:07', 'invalid'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:00:12', 'invalid'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:01:12', 'invalid'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:01:17', 'ready'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:01:23', 'executing'),
  ('\x0000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000002', '2023-01-01 00:01:29', 'traded'),
```

_Disclaimer_: SQL statements were not tested, but should work (or work with minor alterations).

</details>

**Comment by MartinquaXD** [comment]
Really nice summary!
I like the distinction between `executing` and `considered`.

Not sure about the additional data (`auction_id`, `block_number`) you are suggesting but I guess we'll see if we feel the need to add that for debugging purposes.

Another thing that might be worth pointing out explicitly is that we should probably only track these events for market orders as these are the only orders that are expected to execute very quickly.

**Comment by mateipopa** [comment]
This is outright awesome! 

I think that ideally we'd have the metrics in a separate db than the order book - my intuition is that we'll have different usage patterns for the metrics DB than we do for the order book DB and possibly even other instance configurations would make sense (smaller instances/single az/maybe even other sql compatible db at some point).

My two cents regarding the `auction_id` and `block_number` fields: I'd say if it's not too much work, let's add them - it might not count towards the SLI, but we'll have a lot of fun debugging stuff before we get an actual SLO up and measured properly, so the additional information would be nice to have if the extra work isn't too much.

**Comment by ahhda** [comment]
Great writeup! 🚀 

This makes a lot of sense. Apart from SLI, this will also help to see timelines for particular orders for debugging purposes. In future, we could also create order timeline visualizations using this data (for users, solvers etc.)

For the DB, I would recommend keeping the data in the same DB and using a read-only replica for our SLI metrics and analytics. Since we are doing a regular clean-up anyway, this will not increase the storage capacity a lot (our DB is not very big) and if we are using read replicas we will not increase the read load on our DB. Our CPU utilization is currently low, so we can handle writes to the main DB without issues.

Few suggestions/questions
* Can this be behind a feature flag or be configurable like our logging?
* For filtered orders, can we add the reason the order was filtered? This could be a useful metric to track as well.
