### ISSUE TITLE
`driver`: Filter order based on tokens

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1585]
In the past, specific solvers have had issues with specific tokens. This issue captures the work to add logic in the `driver` to filter orders based on tokens on a per-solver basis.

**Comment by MartinquaXD** [comment]
I think I'm lacking context here?
Which solvers have problems with which kinds of token?
Is this intended as "always filter out these tokens for solver X" or rather "when solver X produces solutions that don't work because of a token automatically ignore that token in the future"?

**Comment by nlordell** [comment]
To add more context, we've had DEX aggregator APIs return bad estimates for certain tokens (one example that comes to mind is ParaSwap not considering AMPL token rebases leading to incorrect routes).

One solution to this problem would be to allow solvers to specify a driver configuration to pre-filter out specific orders by token address to ignore them entirely.

Note that this is not an urgent/important feature to implement (in fact, we simulate this when checking settlement and starting soon when quoting as well), just something that I thought would be a nice QoL change for solvers and give us more fine-grained control over what solvers serve which orders.
