### ISSUE TITLE
Return More Descriptive Error on Low Verification Gas Limit

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1593]
Currently, if a user specifies a low `verificationGasLimit` at quoting time and tries to use the quoted `feeAmount` to create an order, we return a generic `InsufficientFee` error. In cases where the fee would be enough had the EIP-1271 verification gas usage been lower, we should return a different error message so integrators can troubleshoot these issues themselves.

See [Slack thread](https://cowservices.slack.com/archives/C0375NV72SC/p1686854697002189) for more context.

**Comment by fleupold** [comment]
I feel like this will go away once all orders are limit orders so probably not worth fixing before?
