### ISSUE TITLE
Prometheus metrics for colocated autopilot auction

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1601]
Similar to the metrics we have in the old driver (solver crate) for solvers.

**Comment by MartinquaXD** [comment]
We have rudimentary metrics in the colocated autopilot by now.
But we might have to go over them to see if they are all we need or if we are missing important ones.

**Comment by fleupold** [comment]
I'd suggest we do this as we go and don't have a specific task for this.
