### ISSUE TITLE
Colocated Autopilot doesn't store into solver_competition table

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1602]
More context on [Slack])(https://cowservices.slack.com/archives/C0375NV72SC/p1687195079186329?thread_ts=1687192847.302879&cid=C0375NV72SC).

We should add a check for this to the colocation e2e test in `crates/e2e/tests/e2e/colocation_univ2.rs`.

**Comment by cowfee** [comment]
Closing in favor of https://github.com/cowprotocol/services/issues/1603.
