### ISSUE TITLE
Required Solver Competion Fields

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1603]
Currently, the `solver_competitions` table is intended for debugging purposes and not meant to provide a stable API for data consumption. However, our analytics makes use of the following keys for the **winning solution**:

- solver address
- calldata (while this can be retrieved from the blockchain, it would require an archive node, so we should store it in our DB - we already fetch it for the CIP-20 solver rewards payout).
- uninternalized calldata
- simulation block

As such, we need to provide a stable API for these fields (potentially create a new table for storing this).

We should also add a check for this to the colocation e2e test in `crates/e2e/tests/e2e/colocation_univ2.rs`.

**Comment by cowfee** [comment]
[Related slack thread](https://cowservices.slack.com/archives/C0375NV72SC/p1687192847302879).
