### ISSUE TITLE
Allow tokens with small rounding issues on transfer?

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1613]
Token 0x856c4Efb76C1D1AE02e20CEB03A2A6a08b0b8dC3 is a bad token because 

> Token 0x856c4efb76c1d1ae02e20ceb03a2a6a08b0b8dc3 is unsupported: Transferring 3664580429618735024777 into arbitrary recipient 0xcd7328a5d376d5530f054eaf0b9d235a4fd36059 was expected to result in a balance of 3664580429618735024777 but actually resulted in 3664580429618735024776. A common cause for this is that the token takes a fee on transfer.

Felix says this is a rounding issue in the token contract. We could consider not failing when the amount is off by a tiny bit. Could even be +-1 just for rounding issues.

**Comment by nlordell** [comment]
I’d rather double down on using quote simulations for bad token detection (i.e. we can simulate an external solver’s quote, then that means that we can solve the order).

This would allow external solvers to support tokens with fees on transfer without additional work for us.

**Comment by vkgnosis** [comment]
When we move to quote simulations for bad token detections we should clear the token deny list. There are tokens in there that don't have to be denied for example because they have off by one errors.
