### ISSUE TITLE
Additional Hook Gas Passed To Solvers

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1658]
Additional hook gas needs to be passed to solver engines. This is so the actual cost of the order is more accurately represented.

We can reuse the `cost` field which used to be the expected gas for the Settlement contract overhead of dealing with the order.

**Comment by fleupold** [comment]
Probably sufficient to expose this on the new API between driver <> solver_engine to which we expect solvers to migrate if they want more accuracy (and not on the legacy instance/result.json interface)
