### ISSUE TITLE
Filter out in-flight orders in the autopilot

### ISSUE THREAD

**Issue by cowfee** [cowprotocol/services#1659]
This is causing issues with the current driver. In-flight orders are those orders which have been published as part of a settlement, but that settlement hasn't been mined yet. The in-flight orders used to be filtered out in the solver crate. With the driver crate, the solver crate isn't being used anymore, so this filtering logic should move to the autopilot. Arguably, maybe it should have been in the autopilot from the start.

**Comment by nlordell** [comment]
> Arguably, maybe it should have been in the autopilot from the start.

Yes... In my mind at least, I always planned to move this into the `autopilot` post-colocation.

**Comment by cowfee** [comment]
This was only needed before due to weird edge cases. Not necessary anymore.
