### ISSUE TITLE
Update Balancer SOR API

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1667]
There is a new Balancer SOR API that builds calldata and supports more Balancer pools. We should switch to it.

**Comment by fleupold** [comment]
@MartinquaXD you were looking into this. Do you have an update (probably not related to colocation in any case).

**Comment by MartinquaXD** [comment]
IIRC my branch is functional it's just that we have a few tests that mock the old balancer API which no longer make sense because they expect to build custom call data. Those tests have to be ported to use some other API instead.
But it should be mostly done.
