### ISSUE TITLE
`driver`: Add Liquidity E2E Tests

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1669]
This issue captures the work to completely E2E test the various driver supported liquidity types. Namely:
- [x] Uniswap V2
- [ ] Uniswap V3
- [ ] Balancer V2
    - [ ] Weighted Pools
    - [ ] Stable Pools
- [ ] Swapr
- [ ] 0x Limit Orders

**Comment by fleupold** [comment]
We do have solver integration tests for Uniswap and Balancer (not sure about swapper). 0x limit orders and Uniswap v3 is currently not supported. Do we want to keep this task around (my tendency is it's a wontfix)

**Comment by MartinquaXD** [comment]
Closing as we all agree that it's a wontfix
