### ISSUE TITLE
chore: handling orders without full app data

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1683]
For backward compatibility we are currently accepting orders where we do not have full app data. Full app data can come from the create order request, the database, ipfs. If full app data cannot be found in any of these places we currently still allow the order to be created.

At some point we want to stop allowing this. This will break applications that set the app data hash to an arbitrary value.

**Comment by fleupold** [comment]
Next step here should be to log whenever this happens so we can identify the sources and decide when we are willing to make the breaking change.
