### ISSUE TITLE
Blockscout API problems

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#1690]
We are currently using Blockscout [1][2] to find holders of tokens. This happens in `crates/shared/src/bad_token/token_owner_finder/blockscout.rs`. During on call I saw that the Xdai error rate for doing this is high, which raised an alert. In my investigation I noticed a couple of things.

We are using an old api. The new api [2] has the same API we're using now but under a different path.

There is a **global** rate limit of 50 requests per seconds. This makes this API unsuited for our purposes as the global rate limit can be exceeded for reasons out of our control. This is likely what is happening on Xdai. The way I read their website is that they want you to self host the service or pay them to host it for you. Their public API is more documentation and less a public free service.

[1] https://docs.blockscout.com/
[2] https://eth.blockscout.com/api-docs
[3] https://docs.blockscout.com/for-users/api/requests-and-limits

**Comment by MartinquaXD** [comment]
Rate limiting was addressed with https://github.com/cowprotocol/services/pull/1754 and https://github.com/cowprotocol/infrastructure/pull/635.
