### ISSUE TITLE
Make success_probability mandatory

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1821]
With https://github.com/cowprotocol/services/pull/1753 solvers are allowed to send optional success_probability + gas_cost as part of their solutions.

Once merged and stable, `success_probability` needs to become mandatory. Also, `score` needs to be dropped.

**Comment by sunce86** [comment]
How do we force solver to switch from `score` to `success_probability` if we don't make `success_probability` mandatory? They will just continue to submit scores.

**Comment by fleupold** [comment]
I also thought we only allow scores for colocated drivers, since otherwise everything except for revert risk is not really under their control anyways.

**Comment by sunce86** [comment]
Closing this as we will not drop `score` any time soon AFAIK.
