### ISSUE TITLE
In-memory database for E2E tests

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/services#1845]
**Problem**

The services stack makes use of postgresql for persisting data used within the stack, creating a strict depedency when wanting to run E2E tests.

**Solution**

Research abstracting the database dependency so that for E2E tests an in-memory SQLite database may be used, opening up the ability to parallelise E2E tests.

**Considerations**

1. Whether this would modify the CI/CD pipeline such that in-memory SQLite tests are used for PRs (*fast E2E test*), and PostgreSQL is used for merges to main.
2. In lieu of (1), adjust release cycle for enhanced smoke tests when deploying releases to Gorli / Gnosis Chain if there is no longer a "long" E2E test through production equivalent postgresql databases.

**Comment by MartinquaXD** [comment]
We could also just :tm: spawn a new docker container per `e2e` test. This would get around the limitation that `postgres` can't simply spawn in memory DBs while still not forcing us to use a different DB for testing than for running the actual system.
For this we could use the [bollard](https://crates.io/crates/bollard) crate which allows us to interface with the `docker` daemon within Rust. It seems to be fairly well maintained/used and our use case seems to be extremely basic:
1. spawn container that dynamically exposes a DB port
2. figure out which port was exposed to use in the connection URL
3. tear down container at the end
