### ISSUE TITLE
`driver`: Add Comprehensive Partial FIll E2E Tests

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1860]
This issue captures the work to add partial fill E2E tests to the driver. In particular, we should be able to:

1. Partially settle an order
2. Since the price is no longer favorable, stop producing solutions for that order
3. Move the price and see the rest of the order settle

**Comment by fleupold** [comment]
We have a similar test now that achieves partial fills by placing an order which doesn't have full balance and later on mints more balance to the user (for the second fill). This should be sufficient.

https://github.com/cowprotocol/services/blob/0d355270030e736ce63afc04b39e1d3829a37074/crates/e2e/tests/e2e/colocation_hooks.rs#L33-L34
