### ISSUE TITLE
Forked tests no longer work after move to anvil

### ISSUE THREAD

**Issue by devanoneth** [cowprotocol/services#1862]
After #1830, forked tests no longer work because anvil does not have feature parity with hardhat for `hardhat_reset`. I've opened an issue in Foundry https://github.com/foundry-rs/foundry/issues/5805 and will soon open a PR to fix it. Just wanted to track it here too as @MartinquaXD asked in PR #1830 if forked tests still work but I cannot comment there anymore.

As an aside, I would like to add a forked test to this repo so that these issues can be caught upstream before my solver does. Would you be happy with that? Any forked tests you've wanted to add that I could tackle for you? Thanks!

**Comment by nlordell** [comment]
> Would you be happy with that?

Please do - although I _think_ CI shouldn't fail on them (so we allow merging when "node provider is down" for example).

**Comment by fleupold** [comment]
It looks like the foundry PR has been merged. Does this mean we can close this now or would you @devanoneth still like to add a test (in which case I'd assign you to this issue)?
