### ISSUE TITLE
Ranking in Gnosis Chain is based on risk-adjusted scores

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1868]
We currently score solutions from Gnosis solvers on Gnosis Chain based on risk-adjusted scores. However, there is no CIP-20 for Gnosis Chain and no risk models for Gnosis Chain!

An example auction where this affected the ranking is `8582009`.

This should be fixed by always assuming probability of success to be equal to 1, which would suggest that the score is equal to the old objective; here, particular attention should be paid in order to ensure we are not discounting costs derived from simulations, as we do on mainnet.

**Comment by fleupold** [comment]
We can override the `risk_parameters` argument for the Gnosis Chain solvers in the infrastructure repo. Which value would we need so that the existing logic arrives at a 100% success probability?

@sunce86 as oncall could you look into configuring this?

**Comment by harisang** [comment]
Ok, if we are to configure the risk_parameters, here is what we should do.

I see this: https://github.com/cowprotocol/services/blob/19c17324f81be1d0890c5e683834e883357bcd19/crates/solver/src/solver/risk_computation.rs#L31

So the easiest way to get to a probability of essentially 1 would be to set the following:

- `gas_amount_factor = 0`
- `gas_price_factor = 0`
- `nmb_orders_factor = 0`
- `intercept = whatever number larger than, say, 20.`

**Comment by sunce86** [comment]
Fixed by @fleupold
