### ISSUE TITLE
Use tenderly gas estimations when ranking solutions

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1872]
`eth_estimateGas` can be very inaccurate. This is nothing new but so far my assumption that `eth_estimateGas` inaccuracy is normally distributed which would on average not impact the fairness of ranking solver solutions.
However, it was brought to my attention that `eth_estimateGas` can be systematically more inaccurate with some liquidity pools but not with others.
That means that solutions using the "bad" pools might have an disadvantage when scoring solutions.
To address that we could use the gas estimation capabilities of tenderly. I don't know if its inaccuracies are normally distributed but on average it's way more accurate in general so that should already improve the fairness since that max deviation is way smaller than before.

**Comment by fleupold** [comment]
I think @sunce86 was looking into this as part of making sure gas price and gas amount are more accurate for ranking. Before using tenderly (which likely will incur costs), I'd like to check if an on chain gas metering contract (that checks the difference of `gasLeft` before and after the settlement call) or someting like the [Enso simulator](https://github.com/EnsoFinance/transaction-simulator) can be free alternatives to get better estimates.

**Comment by MartinquaXD** [comment]
If we look into using a helper contract for the simulation we can also fetch 100% accurate block numbers per simulation. 👌

**Comment by sunce86** [comment]
Tenderly simulation for ranking should be available out of box for colocated driver AFAIS: https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/simulator/mod.rs#L69

This simulator is used to estimate gas for each settlement build in the driver.

**Comment by fleupold** [comment]
I played with the Enso trade simulator last week and if we get Nick's access list PR merged it should work very nicely without costing us a lot of money (tenderly simulations aren't free if iirc)

**Comment by sunce86** [comment]
Additional long term solution would be the `eth_multicall`: https://github.com/ethereum/execution-apis/pull/383
No ETA unfortenately, but based on the current spec it should support calling multiple simulations and guarantee the execution on the same block, while also returning the `block_number` of execution and `gas_used` 🤯

**Comment by fleupold** [comment]
Just another idea, trace_call also gives more accurate information on the actual gas used of the main call.
