### ISSUE TITLE
Dynamically calculate MAX_FEE_FACTOR

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1874]
Inspired by https://github.com/cowprotocol/services/pull/1867, constant `MAX_FEE_FACTOR` should be dynamically calculated based on the configuration parameters for solving time and submission deadline, since those can change.

**Comment by fleupold** [comment]
I'm not actually sure this is the correct fix. Instead of calculating the maximum possible base fee in the code, can't we just set `maxFeePerGas` to our `gas_price_cap` config value and be done with it?

Could be tackled as part of #2216

**Comment by sunce86** [comment]
Yes we can. In practice, I don't see a case where we would get into a trouble for setting high `maxFeePerGas`.
