### ISSUE TITLE
Remove Manual Hardhat Revert Parsing

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1875]
We fixed `ethcontract` to parse Hardhat revert messages in https://github.com/cowprotocol/ethcontract-rs/pull/962. This issue is to remind us to remove the TODO in the linked issue once the PR is merge and the improvement released.

_Originally posted by @nlordell in https://github.com/cowprotocol/services/pull/1873#discussion_r1325730134_

**Comment by MartinquaXD** [comment]
Resolved in #1904
