### ISSUE TITLE
Substitution for /notify in colocated driver

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1891]
Original comment https://github.com/cowprotocol/services/issues/1655#issuecomment-1733838182

`notify_auction_result` is not implemented for the colocation.

In order to support all types of notifications that exist, we would have to propagate data across all layers - for example, ranking would be determined in the `autopilot`, simulation errors in the `driver`, results.json format issues in `solvers`. 

Add `/notify` to `solvers` crate and forward notifications.

### Must have:
- [x] Add `/notify` endpoint in `solvers` and basic infrastructure changes to support notifications propagation.
- [x] Implement simulation failure
- [x] Implement winner settled
- [x] Implement bad score
- [x] Implement general solver communication error

### Not blocking colocation prod:
- [x] Implement timeout errors
- [ ] Invalid execution plans
- [x] Implement invalid success probability input
- [ ] Check if we can remove `InsufficientBalance` notification if it is already checked in simulation.
- [x] Add environment (`eth.network_id()`) to the notification model.

**Comment by fleupold** [comment]
I wouldn't persist any data in a database, because conceptually we want to be able to run all components in different clusters (mainly autopilot <-> driver, but even as we move solvers towards the new api design we may also have driver <-> solver_engine communication across clusters).

**Comment by devanoneth** [comment]
At Enso we anyway were going to open a PR to add `metadata` to the `/notify` payload, similar to what we already receive at `/solve`. This is so that we can run the same infra for multiple chains and switch based on `metadata.environment`.

Could we also ensure this happens in the new `/notify` endpoint? If you want, I can just do both in the same PR.

**Comment by sunce86** [comment]
@devanoneth If it doesn't take too much of your time, feel free to make PR for the old `notify`. I will check which of these fields can be populated for the new `notify`. 
Environment can be definitely easily added so I will add it to the list ☝️

**Comment by fleupold** [comment]
Is there anything more we need to add for `/notify` now that the open PRs are merged?
