### ISSUE TITLE
Implement accurate `gas_amount` estimation using Enso in `driver`

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1897]
Currently, there are two ways to estimate gas for a settlement: https://github.com/cowprotocol/services/blob/main/crates/driver/src/infra/simulator/mod.rs#L69-L83

We need to add Enso simulator as a third option.

As a consequence, no `gas_amount` should be considered from external solvers, going forward. Make sure no external solver is sending the `gas_amount` and after that remove it from https://github.com/cowprotocol/services/blob/main/crates/shared/src/http_solver/model.rs#L214

**Comment by MartinquaXD** [comment]
> Make sure no external solver is sending the gas_amount and after that remove it

I think you don't have to wait for solvers to stop sending the gas amount. You can simply drop it and the parsing logic will ignore the field if it's still present.
Or are you worried that some solvers might get angry when we suddenly start ignoring the gas amount they send with their response?

**Comment by sunce86** [comment]
Yes, we want to remove it after we have a proper replacement.
