### ISSUE TITLE
bug: The Staging 0x solver does not compute a fee for fok limit orders 

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#1959]
### Problem
Here is a settlement from 0x on barn from a few hours ago, that executes two limit orders and sets zero fee to them.
https://etherscan.io/tx/0x21fa43eab9efae65320ebc170b31176edd03a9097b064dd240142b1dc56cf6d2
https://explorer.cow.fi/tx/0x21fa43eab9efae65320ebc170b31176edd03a9097b064dd240142b1dc56cf6d2?tab=orders

The two order ids are:

- `0xf61a074c198e0b8556eb07784a137f664023822ab05f3ff368883f1ed7e7eb5dffab14b181409170378471b13ff2bff5be012c64654f6e8a`

- `0x574b858644c51cc19614b18f936ccb0dcc1867f110f3299874f8065a1e742275ffab14b181409170378471b13ff2bff5be012c64654f94d7`

I checked the database and this is what I saw:
![image](https://github.com/cowprotocol/services/assets/64154020/695b7ffb-ff91-4cf1-863b-314b03536b44)

This [log](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.10.13?id=vHRjJosBGP6wkTcjOPFj) seems to suggest there was some fee computed by the solver, if I am not mistaken.

**Comment by fleupold** [comment]
Looking into it. I see we did encode three prices (and computed a surplus fee on the solver side), but it looks like something may be off with the interaction amount encoding (we are sending the whole sell amount in and not 4994).

Logs: https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/7FXyg

<img width="323" alt="image" src="https://github.com/cowprotocol/services/assets/1200333/47227f19-f10c-417e-add4-5f31514bf5bd">

<img width="823" alt="image" src="https://github.com/cowprotocol/services/assets/1200333/50c98b69-53a3-4533-825d-23cb48d23220">

**Comment by harisang** [comment]
> Looking into it. I see we did encode three prices (and computed a surplus fee on the solver side), but it looks like something may be off with the interaction amount encoding (we are sending the whole sell amount in and not 4994).
> 

If I am not mistaken, I feel this is the intended behavior, as it is easier to then pocket the fee in the buy token, so as to not invoke the API once again. I.e., solvers are supposed to report a fee in the sell token, but then Gnosis solvers decide to incur negative slippage in the sell token and then positive slippage in the buy token, as the driver ultimately corrects the price to account for that fee.

So my complaint was mainly for not propagating the surplus fee into the database; something is lost on the way.

Anyways, seems you have already figured most things out so I don't want to add noise here.
