### ISSUE TITLE
feat: Refactor Liquidity Indexing Into Separate Service 

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#1963]
### Background

We currently implemented the `driver` to index liquidity and send this to solver engines. However, only the Baseline and Quasimodo solvers make use of this, so it feels like the liquidity indexing in the `driver` may have been a mistake.

This also creates asymmetry in that
- All solver engines that use provided liquidity **CANNOT generate calldata**
- All solver engines that generate raw interactions **CAN generate calldata**

Having access to calldata in the solver engines in `solvers` is useful in the context of swap simulation for accurate fees (see #1960 - which currently cannot be implemented for the baseline or naive solver because of their inability to generate calldata).

Not indexing liquidity in the `driver` has an additional nice property that if, for example, the Graph is down and the liquidity indexing cannot bootstrap, then it would not affect the `driver` binary's ability to start.

### Details

I propose:
- [ ]: Create a separate crate **only** containing the `infra::liquidity` code from the Driver and expose an HTTP endpoint for querying liquidity. This should pretty much only require moving code around and should be fairly trivial to do
- [ ]: Change the `baseline` and `legacy` solvers to poll the new liquidity service instead of getting the `driver` to augment the auction with liquidity.

**Comment by fleupold** [comment]
@MartinquaXD is this something we want to tackle before we consider co-location done? I like that this would go towards the direction of offering a "liquidity book", ie. a service that other solvers can tap into to receive liquidity and that external projects could integrate their own liquidity into.

I'm not sure how core this first step is towards solver/driver colocation however (building another orthogonal service and getting it production ready sounds like a whole nother 🥫 of 🐛 to me)

**Comment by MartinquaXD** [comment]
I consider this a separate project which would indeed be another set of risks that we should not tackle before we are happy with the colocation.
