### ISSUE TITLE
chore: Move settlement merging to `solvers` crate

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1971]
### Background
Currently settlement merging is done in the `driver` crate. We should consider moving the merging to `solvers` crate.

Leftover from https://github.com/cowprotocol/services/issues/1893

**Comment by fleupold** [comment]
@sunce86 could you give a bit more context on why it's desirable to move the merging logic into the solver crate (why was it put in the driver crate initially and what did we learn since that makes us revisit this choice)? This is not obvious to me from the linked issue.

**Comment by sunce86** [comment]
Based on the linked issue, it's just a matter of what is whose responsibility. So, if `RiskCalculator` is part of the `solvers`, than the merging also needs to be done in `solvers` so that the success probability is accurately calculated for the merged settlements also. Right now, merged score for merged settlements is just an approximation of what it should be: https://github.com/cowprotocol/services/blob/main/crates/shared/src/http_solver/model.rs#L251-L254

`Driver` shouldn't do merging. It should just do the encoding, simulations and scoring. It should not generate additional solutions that the `solvers` is not even aware of.

IMO we can exclude this from the `Colocation` feature, because the merging was done on `SettlementEncoder` in the old driver also (so it's not strictly tied to colocation). It should probably be part of the new initiative where we simplify and port the `SettlementEncoder` into `driver::domain`.
