### ISSUE TITLE
chore: Remove `score` from `boundary::settlement`

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#1973]
### Background
Original comment: https://github.com/cowprotocol/services/pull/1901#issuecomment-1738884013

### Details
Basically try to decouple `boundary::settlement` and `score` as much as possible, so we could move scoring away from `boundary`. This is also related to #1494, but this issue is a prerequisite for #1494.

**Comment by fleupold** [comment]
Will tackle this as part of #1494

**Comment by sunce86** [comment]
Are we removing the score completely with `ranking by surplus`? I tried to glance over the forum post but couldn't find it.

**Comment by fleupold** [comment]
@harisang correct me if I'm wrong but I understood that given we submit the clearing prices and executed amounts with the solutions we no longer need to report a score but can instead compute it in the autopilot for each submission. 

I'm not sure we want to wait for "rank by surplus" though to remove the legacy solver crate.

**Comment by sunce86** [comment]
I even imagined driver submits encoded settlement so we can use the same logic for ranking in both autopilot and driver (driver still needs to do the internal ranking to see which solution to submit).

**Comment by fleupold** [comment]
> I even imagined driver submits encoded settlement (but with cleared interaction) 

What data in addition to than clearing prices and order executions would be needed for that.

> I even imagined driver submits encoded settlement (but with cleared interaction) 

That's a very good point. In this case it may be simpler to continue sending a score from the driver to the autopilot and leave it up to the off chain verification to make sure it was correct.
