### ISSUE TITLE
bug: Can't find a mined transaction when running in colocated mode

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1974]
### Problem
In the colocated mode the `autopilot` is orchestrating the auction. It informs solvers about the auction, picks a winner, tells the winner to `/settle` the solution and afterwards monitors the blockchain for some time to detect the requested tx.
But it turns out that we often are not able to find the expected auction which can indicate a bug. ([logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-12T11:41:07.415Z',to:'2023-10-16T16:00:00.000Z'))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'log:%20%22could%20not%20find%20a%20mined%20transaction%20in%20time%22'),sort:!(!('@timestamp',desc)))))

### Impact
It makes it unnecessarily difficult to debug the run loop for a given `tx_hash` because we don't issue a log linking the hash to an auction id.

### Expected behaviour
If a driver submits a solution the `autopilot` should be able to detect it in a timely manner.

### Screenshots/logs
[1](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-10-12T11:41:07.415Z',to:'2023-10-16T16:00:00.000Z'))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'log:%20%22could%20not%20find%20a%20mined%20transaction%20in%20time%22'),sort:!(!('@timestamp',desc))))

### services version/commit hash and environment
`v2.227.1-26-g44bf11c4`

**Comment by MartinquaXD** [comment]
After investigating a bit more I see 2 options for submission issues so far:
1. some solvers report a solutions very quickly and then have to wait a lot before being declared the winner. In the meantime the solution might become unviable
2. it even happened a few times that right after simulating a solution and being declared the submission loop stopped because the simulations started to revert. This seems very suspicious and might indicate some node or simulation issues. Has to be investigated further.

**Comment by fleupold** [comment]
Can this issue be close?
