### ISSUE TITLE
chore: Refactor `SolverSettlement` struct

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1976]
### Background
We store a bunch of information about the solutions submitted for every auction. The information that is available running in the colocated mode is not the same as when running in the old mode. (see [TODO](https://github.com/cowprotocol/services/pull/1975/files#diff-8a11a8276d7572d1f949773ad29d0e2089fc86498483ca91e6f6828cac310517L235-L236))

### Details
As part of the clean up after we deployed colocation completely we should revisit the `SolverSettlement` struct to properly model what we can store in the colocated world. This can mean dropping fields entirely, only changing types or for example grouping existing optional fields together. (the 2 calldata fields are only `Some` for the winning solution; this could be encoded as a type)

### Acceptance criteria
The `SolverSettlement` no longer contains fields that don't make sense in the colocated world.

**Comment by fleupold** [comment]
This was done with #2143
