### ISSUE TITLE
chore: Reduce the size of `order_events` table

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#1977]
### Background
In order to keep track of our "time to happy moo" SLI (time between order creation and trade) on an order-by-order basis we created the table `order_events` that stores timestamped events throughout an order's life cycle.

### Details
Most of the data in `order_events` are entries for `invalid` orders (most likely due to missing balances). This bloats the size of the DB significantly and slows down the SLI query. Note that this is already the case but will become more prominent when we deploy colocation because we store more events in the colocated mode.
The goal of this issue is to manage the number of entries in `order_events` to a manageable/usable number.

### Acceptance criteria
- [x] add background tasks that periodically drops order events that are very old (configurable)
- [x] special treatment for `invalid` events (maybe only store another `invalid` event when the order was previously **NOT** invalid; meaning only store state changes)
- [x] only store events for `market` orders as these are the orders for which we want to guarantee very fast execution anyway

**Comment by squadgazzz** [comment]
> special treatment for invalid events (maybe only store another invalid event when the order was previously NOT invalid; meaning only store state changes)

Does it make any sense to update the timestamp of the existing row?
Should this also be applied to any other status?

**Comment by MartinquaXD** [comment]
> Does it make any sense to update the timestamp of the existing row?

No. We'd like to be able to recover the entire time span when an order was `invalid`. If we update the timestamp in the row we'd move the start of the `invalid` period forward. I think it's enough to have some logic like:
`only add the new row if has a different lable than the previous entry for this order`.
That way we keep the entire information for all state transitions without wasting memory for duplicates.
>  Should this also be applied to any other status?

I think we only need it for the `invalid` state but best not to introduce additional special cases if it can be avoided.
