### ISSUE TITLE
chore: Reduce number of solutions that fail after calling `/settle`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2007]
### Background
Similar to https://github.com/cowprotocol/services/pull/1999 this issue aims to reduce the time we waste due to incomplete data in the `autopilot`.
For example it can happen that some solver is very quick to respond with a solution for a given auction. But if some solvers take all the time they can use before reporting a solution they will return solutions with more up-to-date date whereas the quick to respond solvers would be unaware that a new block appeared that made their solution revert.

### Details
I see 2 ways to handle this:
1. in the `driver` keep requesting new solutions from the matching engine until the time runs out. This is the actually the most rational behavior and would produce the most recent data the solver can provide at the cost of more compute resources on the external solver's end.
2. In the run loop of the `autopilot` don't just pick the highest score and declare them the winner. Instead call `/reveal` on the individual drivers from the highest to the lowest score and simulate their solutions. Only call `/settle` for the highest ranking solutions that **still simulates**. This solution would be totally fine for as long as we are running all the drivers but would undermine a pretty important aspect of the redesigned system (improved market maker support that only expects you to produce call data if you actually won).

We could of course go for both solutions (or some other solutions I didn't consider) but since just doing `2` would result in a system that is effectively identical to our legacy system (together with [the mentioned PR](https://github.com/cowprotocol/services/pull/1999)) and is easy to implement I would go for that until we figure out a better way to avoid wasting precious run loops.

### Acceptance criteria
Some change that results in more winning solutions actually ending up on-chain.

**Comment by MartinquaXD** [comment]
Since we have to have way higher throughput and should overall have the lowest latency possible on prod I consider this issue as `Blocking Prod`.

**Comment by sunce86** [comment]
Considering that is blocking prod I would be ok with (2) but would make immediate follow up plan what to do in a cleanup - probably communicating with external solvers about this and implement (1) and potentially reduce the solving time to further reduce the change of solution being invalid.
