### ISSUE TITLE
chore: add `/notify` api endpoint to openapi.yml

### ISSUE THREAD

**Issue by mfw78** [cowprotocol/services#2035]
### Background
It's frustrating when there are endpoints of which there is no documentation (noted that the endpoint in question is in development :grin:).

### Details
All endpoints should be documented in the applicable `openapi.yml`.

### Acceptance criteria

- [ ] `/notify` endpoint documented in `openapi.yml`.

**Comment by MartinquaXD** [comment]
The `/notify` endpoint has been documented in the `solvers` create by now.
It's still not present in the `driver` openapi spec but that endpoint is only useful for the transition period where we are still running drivers for external solvers. Once solvers run their own drivers they can could get all the data from the logs or the competition endpoint.
Closing this issue for now. If there is enough demand down the line to keep this endpoint alive for some reason we can reopen it.
