### ISSUE TITLE
bug: Colocated solvers timing out on prod mainnet

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2041]
### Problem
When testing colocated drivers on prod mainnet we saw basically all of them timing out.
This is concerning for 2 reasons:
* it looks like something is making the whole process surprisingly slow (maybe contention on some lock 🤷‍♂️)
* our timeout management in the `driver` is not working. Ideally we should never see timeouts on the autopilot side. Instead the `driver` should abort the computation right before the deadline and return 0 solutions.

### Impact
Colocation is basically not usable like this on prod.

### To reproduce
Only way is to apply colocation on prod mainnet because that is where we have the required traffic to trigger the issues.

### Expected behaviour
The driver should never time out and we should not see a reduced number of proposed solutions compared to the current setup.

### Screenshots/logs
[logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-11-02T10:21:31.579Z',to:'2023-11-02T11:00:20.182Z'))&_a=(columns:!(log),filters:!(),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'mainnet%20and%20(log:%20%22timeout%22%20or%20log:%20%22timed%20out%22)%20and%20driver'),sort:!(!('@timestamp',desc))))

**Comment by sunce86** [comment]
A bit more information:

`Autopilot` gives a `driver` a deadline to return the solution. Currently, 15s are given to `driver`.
`Driver` then gives 14s to `solvers` for calculation. Approximately ~1s is left for `driver` to simulate solutions, do the merging, simulate merged settlements, do the scoring...

There are several issues here:
1. `Driver` is left with 1sec, but this deadline is not enforced anywhere, leading to timeout responses in `autopilot`.
2. 1sec is hardcoded and cant be changed via config.
3. 1sec is same for all solvers, which is not appropriate. Some solvers return a single solution while others return a lot of solutions. Some solvers return early, others spend full time given to them (14s).
4. Network delay for sending the response back to `autopilot` is not taken into consideration.

I would suggest the following:

- [ ] Add time buffer for network delay (500ms) and make it configurable. The value is the same for all solvers. Subtract this time from the auction::Deadline on the `driver` side.
- [ ] Make `1sec` time configurable per solver (if easy, if not, just make it configurable).
- [ ] Respect the deadline in `driver` and return partial result in case of timeout. Partially tacked with https://github.com/cowprotocol/services/pull/2059
- [ ] Change the deadline from 15s -> 20s.

This way, 20s would be given to `driver`, 0.5s reserved for network delay, 14s for solving, 4,5s for encoding, simulations, merging, scoring.
