### ISSUE TITLE
feat: Remove the out-of-market flagging as liquidity orders

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2057]
### Problem
It seems we continue to flag orders as liquidity orders when they are "out of market". At some point in time, this was meaningful, but I think it is not anymore, and it might lead to problematic flagging of orders. See [here](https://cowservices.slack.com/archives/C0375NV72SC/p1699972242026989) for an example and discussion.

### Suggested solution
Remove this "rule", effectively reverting PR #301

**Comment by MartinquaXD** [comment]
@sunce86 didn't we have an issue that says we want to get rid of the concept of liquidity orders altogether. I wanted to link it here but can't find it. Do you know where it is?

**Comment by sunce86** [comment]
Maybe this comment? https://github.com/cowprotocol/infrastructure/issues/1032#issuecomment-1903697480
