### ISSUE TITLE
feat: Store quotes for limit orders

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2078]
### Problem
Every time a limit order is created, a quote should be stored in database.

### Additional context
Limit orders usually have a quote before being created, since UI asks for limit order quotes with `PriceQuality:Optimal` option, which means quote will be generated.
Quote for Limit orders should be generated in the same way quotes are generated for market orders. 

### Acceptance criteria
- [ ] Quotes for limit orders are stored in database on creation.
- [ ] Quotes for limit orders can be fetched from database (from autopilot).
- [ ] ~Quotes for expired limit orders should be periodically removed from the database, for performance reasons.~ cc @MartinquaXD @fleupold wdyt?

**Comment by MartinquaXD** [comment]
> Quotes for expired limit orders should be periodically removed from the database

I'd probably not make this an acceptance criteria. We could have already done that for all orders but we didn't so I think this is probably not super important.

**Comment by fleupold** [comment]
Should this also include that the driver has access to the fee (as this is likely where the default logic would be implemented) or is this a different task?

**Comment by sunce86** [comment]
> Should this also include that the driver has access to the fee (as this is likely where the default logic would be implemented) or is this a different task?

Was cooking it in meantime, here it is: https://github.com/cowprotocol/services/issues/2081
