### ISSUE TITLE
Log more feedback on why a solution got ignored

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#209]
External solver implementers are sometimes confused why a solutions was not considered by the driver.
Usually the solutions violate a condition which we didn't properly communicate to them.
A first step to improve this situation would be to log more detailed information when a solutions gets ignored in the driver. Solver implementers running the driver could then check the logs to see what's going on.

[related slack thread](https://cowservices.slack.com/archives/C0375NV72SC/p1652955145717999)

**Comment by nlordell** [comment]
Started with #213, but still not 100% happy with it (it just adds additional logs at various points).

Ideally, we should come up with a "settlement filter" abstraction that can be instrumented and chained together. Various parts of the `driver.rs` beast can be factored out into "settlement filters" that can be instrumented independently so we see where most settlement get filtered and add logs in a way that applies to each of these "filters".

**Comment by MartinquaXD** [comment]
Closing because the problem this issue wanted to address got solved in #661 and #684.
