### ISSUE TITLE
feat: [ON HOLD] Differentiate TWAP limit orders in autopilot 

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2091]
### Problem
TWAP limit orders need to have a different protocol fee treatment within driver. For example, initial (default) way of calculating protocol fees for regular limit orders will be based on price improvement while for TWAP limit orders will be based on fixed fee.

### Suggested solution
If protocol fee parameters are defined per order, than the `driver` can be oblivious if the limit order is regular or TWAP. Only the autopilot would have to know so it could define fee parameters for each order in the auction before sending it to the `driver`. Based on my latest learnings, currently autopilot doesn't know if the order is TWAP or not, so this should be implemented in this issue (probably via appdata).

### Acceptance criteria
- [ ] Autopilot knows if the limit order is regular limit order or TWAP

**Comment by fleupold** [comment]
Can we scope out TWAP fees into a somewhat different epic/milestone? While useful for the design, I don't think we should put any work into TWAP fees before limit order fees are live as this will just distract and delay us (cc @olgafetisova)

**Comment by sunce86** [comment]
> Can we scope out TWAP fees into a somewhat different epic/milestone? While useful for the design, I don't think we should put any work into TWAP fees before limit order fees are live as this will just distract and delay us (cc @olgafetisova)

I think this makes sense a lot. 
I will go with the simplest initial implementation supporting only general limit orders with out-of-market price.

**Comment by sunce86** [comment]
For the same reason as in `https://github.com/cowprotocol/services/issues/2115#issuecomment-1892233770`, nothing to do for this issue.
