### ISSUE TITLE
feat: Observability of gas estimation

### ISSUE THREAD

**Issue by fedgiac** [cowprotocol/services#2094]
### Problem
I've noticed that the `GnosisSafe` gas estimator has been broken for a long time, and to my understanding there is no way I can see that from logs or metrics since it's never used in practice, even when configured.

On prod we run with gas estimators `Native,BlockNative,GasNow,GnosisSafe,EthGasStation,Web3`, which are queried in series and the first successful response is returned. However I think we never query anything except `Native` and `BlockNative` since the two of them just work ([failure logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-15d,to:now))&_a=(columns:!(log),filters:!(),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'log:%22gas%20estimator%22%20and%20log:%22failed%22%20and%20kubernetes.labels.network:mainnet'),sort:!(!('@timestamp',desc)))), `Native` is already enough except one time when we had caching issue).

### Suggested solution
- Add metrics that count request count, success, and failure of each gas estimator.
- Add tests for each gas estimator that actually run on CI. We could make these "known unpredictable flacky tests" run as a different job and not block merge on failure, to make these failures less annoying but still noticeable.

### Alternatives considered
We could just get rid of the whole gas estimator setup and just use `Native` and maybe a single backup.

### Other considerations

This code is mostly legacy from when gas estimation was harder. After EIP-1559, it has become much simpler. We should check if other chains we could deploy to in the future support it.

**Comment by fleupold** [comment]
In the spirit of complexity reduction, I'd be in favor of removing most of these strategies from our production deployment given that gas estimates have become much simpler since EIP1559.
