### ISSUE TITLE
Flashbots `unable to decode txs` Error

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#210]
We have intermittent error with Flashbots submission (an increased frequency on 17.05.2022 caused an alert - although this has been happening on and off since end of April):

```
2022-05-17T08:49:58.763Z DEBUG auction{id=33017}: shared::transport::http: [flashbots][id:4794] received response: "{\"id\":4794,\"error\":{\"code\":-32603,\"message\":\"relay error response: unable to decode txs\"},\"jsonrpc\":\"2.0\"}"
```

<details><summary>An example log of a transaction that triggered this error:</summary>

```
2022-05-17T08:49:58.489Z DEBUG auction{id=33017}: shared::transport::http: [flashbots][id:4794] sending request: "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendRawTransaction\",\"params\":[\"...\"],\"id\":4794}"
```

</details>

Note the transaction data is very long - one concern I have is that Kibana didn't correctly record the full log message. [I attached the encoded transaction hex calldata](https://github.com/cowprotocol/services/files/8729220/tx.txt).

**Comment by sunce86** [comment]
First interesting thing is that we have examples of two sequential requests (with two seconds in between) where first one fails while the second one passes successfully, while both of them having the SAME `params` (not even gas price changed):

UTC time
Failed: `2022-05-27T02:01:11.644Z DEBUG auction{id=10754}: shared::transport::http: [flashbots][id:1155] sending request: "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendRawTransaction\",\"params\":[],\"id\":1155}"`
Succeeded:  `2022-05-27T02:01:09.150Z DEBUG auction{id=10754}: shared::transport::http: [flashbots][id:1154] sending request: "{\"jsonrpc\":\"2.0\",\"method\":\"eth_sendRawTransaction\",\"params\":[],\"id\":1154}`

Second interesting thing is that, for the first one that fails, in parallel there is also the failure (with the same error message `unable to decode txs`) for request sent to Eden network.
