### ISSUE TITLE
feat: Make subgraph URL's configurable

### ISSUE THREAD

**Issue by ahhda** [cowprotocol/services#2105]
### Problem
We use two subgraphs in our backend, Uniswap v3 and Balancer v2. The Base URL for these subgraphs has been made configurable in #2126, however it turns out that in order to use third party hosted solutions, we not only need the base URL but instead the entire URL configurable. 

For example the Alchemy URL is in the format `https://subgraph.satsuma-prod.com/API_KEY/ACCOUNT/balancer-v2-subgraph/version/v0.0.1-new-version/api`.

This requires a code change so that the URL's can be configured via env variables/infra config.

### Suggested solution
Make entire subgraph URL's configurable similar to what we have for `ethRpc` or `ethplorerApiUrl`

### Additional context
As the hosted service is being shut down, the hosted subgraphs that we use currently have performance issues. We are now trying to host the subgraphs on either the graph explorer or Alchemy.

This should help fix #1759, #1020

### Acceptance criteria
* Entire subgraph URL for Uniswap and Balancer are configurable via infra config

**Comment by ssvarmma** [comment]
amazing

**Comment by fleupold** [comment]
The issue was re-opened, because we actually need to make the full URL (not just the base) configurable for each liquidity type.
