### ISSUE TITLE
feat: Add some subscription logic to the cow API. 

### ISSUE THREAD

**Issue by marcovc** [cowprotocol/services#2125]
### Problem

Given that notify stopped notifying about the rank in the co-located setup, to be able to monitor if a solver wins an auction we need to query the cow API. For this, we need to know the batch id, which is I suppose is only provided in the solve() call. 

In order to keep the monitoring logic separated from my solver, I have a dedicated process that just monitors the competition, and stores whatever is needed. This process does not get a notify call, so it does not know the latest auction id. 
 
### Suggested solution

Maybe there is a way I am not aware of, but would be nice if I could just subscribe some websocket to be informed of new auctions, or at least some endpoint I could keep polling.  

### Alternatives considered

An alternative is to listen to the smartcontract submission events, which gives a txhash that can also be used to query about the settlement. But unfortunately, querying with a txhash is only possible 30 minutes or so after the settlement happened, which does not provide an updated monitoring.

**Comment by fleupold** [comment]
Don't we already populate the auction id on each instance we send to solvers ([code](https://github.com/cowprotocol/services/blob/main/crates/shared/src/http_solver/model.rs#L305))?

With this id you should be able to query https://api.cow.fi/docs/#/default/get_api_v1_solver_competition__auction_id_ to get your ranking.

@marcovc can you confirm this is working and close this issue in that case?

**Comment by fleupold** [comment]
I see. Would https://github.com/cowprotocol/services/issues/1945 solve the issue? Adding websocket support to our API seems like a big endeavour that I don't see happening in the near future.

**Comment by marcovc** [comment]
That would solve it indeed. I suppose you guys are used to solvers continuously polling the endpoints anyway :)

Thanks
