### ISSUE TITLE
chore: Define minimum slippage tolerance

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2137]
### Background
We had an [alert](https://cowservices.slack.com/archives/C0371SB243E/p1701967344998349) about frequently failing settlements on Gnosis Chain, which seems to be due to setting too little slippage tolerance.

### Details

Some users on Gnosis Chain trade ridiculously small amounts ([example](https://explorer.cow.fi/gc/orders/0x9fe0a4526cd755e18d88f54c4edd79b7d019c368b4f9583b5e22f16adf239a0362ec782b3e1e3ad131cbfb62f9581d0ee0a155656571f68c?tab=overview)). Those solutions are particularly prone to reversion because the way Gnosis solvers compute slippage tolerance is a relative volume % capped at some maximum value. 

Now 0.1% slippage tolerance of a minuscule value is an even smaller absolute value making solutions very prone to revert if the underlying AMM has the slightest change in reserves (cf. this [simulation](https://dashboard.tenderly.co/gp-v2/staging/simulator/6422a868-a317-4357-ba84-eceba8d73b52?trace=0.6.0.0.2.17.6)) 

### Acceptance criteria

Similar to the maximum absolute-slippage, allow to define a minimum absolute slippage which is being respected in the solutions

https://github.com/cowprotocol/services/blob/5b7201fd3ee22cd6d41a9e34b356a0d7d4937f05/crates/solvers/src/infra/config/dex/file.rs#L34-L36

**Comment by Braqzen** [comment]
Looking around it seems straightforward to add another field, rename this current one and retain functionality. I'm unsure about when the minimum slippage would be used within the Limit though. Adding it and not using it anywhere seems lackluster. Should the minimum be used in the calculations of the Limit?

**Comment by MartinquaXD** [comment]
Thanks for your interest in this issue.
Each dex solver implementation queries the respective dex API and applies a slippage to that solution in the `swap()` function. This is where the min_slippage would come into play.

**However, this particular code was already moved into a separate repo and for legal reasons we must no longer accept external contributions for it.**
I will therefore remove the `help wanted` tag from it to avoid further confusion.
