### ISSUE TITLE
Investigate Flashbots gas API

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#214]
Few months ago, we tried to use the Flashbots gas price API but it was giving us too high gas prices compared to native gas price estimator / blocknative.

We need to check the values again, compare them with native gas price estimator / blocknative and see how the values behave under network congestion. 

If it feels meaningful, since we expect that `flashbots gas price > native gas price`, maybe implement `gas price = (flashbots gas price + native gas price) / 2`

**Comment by vkgnosis** [comment]
Currently we have a fixed factor for extra gas for flash bots. We could check their gas api against that value and use the lower of both. This way we don't overpay when not needed (assuming their api is mostly accurate). 
On the other hand if we're running in a flash bots only mode then arguably we should replace our whole gas price logic with the flash bot api but it really depends on how good their gas algorithm is. I'm not sure I'd trust it that much.
