### ISSUE TITLE
bug: We don't `/notify` solvers on some errors

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2140]
### Problem
It looks like there are some errors for which we don't correctly call the `/notify` endpoint to give the solver debugging information.

### Impact
External solver maintainers have a hard time debugging issues with their solutions.

### To reproduce
Check these [logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-7d%2Fd,to:now))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.app_kubernetes_io%2Finstance,negate:!t,params:(query:ingress-nginx),type:phrase),query:(match_phrase:(kubernetes.labels.app_kubernetes_io%2Finstance:ingress-nginx))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.appClass,negate:!t,params:(query:mainnet-api-prod),type:phrase),query:(match_phrase:(kubernetes.labels.appClass:mainnet-api-prod)))),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'log:%20%22notify%22'),sort:!(!('@timestamp',desc)))) to see that we don't have a single notification for:
* simulation errors
* negative scores
* encoding errors

### Expected behaviour
A solver should receive a `/notify` request for every solution it provided. Either a reason why it was discarded or the rank it achieved in the competition.

**Comment by MartinquaXD** [comment]
cc @ColePBryan (user which reported that they are missing `/notify`s for many auctions)

**Comment by sunce86** [comment]
I see that we have notifies for simulation errors: https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/Gk4lS

**Comment by fleupold** [comment]
Do we have a concrete solver that didn't receive a notification for a specific auction?

Unlike stated in the issue description, I see logs for [simulation failures](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.12.18?id=ZQrAfowBlutGF6GyLaEz), [non-positive score](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/doc/ea511870-d9b3-11ed-a9d0-a17451f01cc1/cowlogs-staging-2023.12.18?id=-r7DfowBu25xllFNV_N0) (encoding errors are mostly also simulation failures).

We don't notify runner ups with their rank, but this is by design (rank can be fetched from the solver competition endpoint)

**Comment by MartinquaXD** [comment]
The specific example that sparked this issue is [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-06T16:31:53.956Z',to:'2023-12-06T16:32:37.324Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.app_kubernetes_io%2Fcomponent,negate:!t,params:(query:controller),type:phrase),query:(match_phrase:(kubernetes.labels.app_kubernetes_io%2Fcomponent:controller))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.container_name,negate:!t,params:(query:mainnet-api-prod),type:phrase),query:(match_phrase:(kubernetes.container_name:mainnet-api-prod))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.network,negate:!f,params:(query:mainnet),type:phrase),query:(match_phrase:(kubernetes.labels.network:mainnet)))),grid:(columns:('@timestamp':(width:164))),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'shadow%20and%20log:%20%228119291%22'),sort:!(!('@timestamp',desc)))) where the `odos` solver provided some solution which failed to simulate with `execution reverted` but did not receive any `/notify` call about it.

**Comment by fleupold** [comment]
In this specific auction, the error was in estimating the access list, which currently is classified as a "Basic" Simulation error (for which we don't notify solvers). I will make a PR to address this.
