### ISSUE TITLE
Additional fee subsidy for locked GNO

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#217]
We want to reward people committing to the cow-protocol/gnosis eco system by reducing their fees on trades.
We already covered people committed to cow-protocol (by holding CoW/vCow tokens) but people committed to gnosis currently don't get any benefits.

This issue tracks the work required to give people fee subsidies based on the amount of their locked GNO.

**Comment by MartinquaXD** [comment]
It's currently unclear to me what the details should look like:
Should the GNO fee subsidy be additive to the existing CoW/vCoW subsidy?
Should there be an equivalence of `m` locked GNO == `n` CoW + vCoW?

If anyone knows the details, feel free to add them to the issue description.

**Comment by nlordell** [comment]
> Should the GNO fee subsidy be additive to the existing CoW/vCoW subsidy?

Yes.

> Should there be an equivalence of m locked GNO == n CoW + vCoW?

I think `m locked GNO == n CoW` vested over some time. There is no `vCOW` balance associated with locked GNO.

Concretely, we would have to read the total locked amount from the Merkel tree
> Since it’s a merkle drop, you can’t read the balances from a smart contract (until they are first claimed). We keep all the allocations + merkle proofs in this repo: https://github.com/gnosis/locked-gno-cow-merkle-distro
So you could read it from https://raw.githubusercontent.com/gnosis/locked-gno-cow-merkle-distro/main/mainnet/original.json

And then add contract binding to [`0x68FFAaC7A431f276fe73604C127Bd78E49070c92`](https://etherscan.io/address/0x68FFAaC7A431f276fe73604C127Bd78E49070c92#readProxyContract) subtract the already claimed amount from the total that is part of the Merkel tree.

**Comment by MartinquaXD** [comment]
We don't have any fee subsidies based on token ownership anymore
