### ISSUE TITLE
feat: Restore gasPrice in competition endpoint

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2170]
Not sure if this is already in the to-do list, but it would help a lot to be able to recover the gas price (shared with solvers in the each /solve request) in the competition endpoint. Two use cases:

1. Detecting overbidding
2. Evaluating how accurate solver-compute fees are.

**Comment by fleupold** [comment]
The autopilot doesn't specify a gas price for the auction (and the driver doesn't return a gas price to the driver, because it doesn't fundamentally matter for the protocol anymore). What we could expose is the gas price that ended up being used on the settlement transaction (this could be looked up from chain as well).

The other things we are thinking about doing in #1752 is storing the auction that we sent to solvers (which should include the gas price the driver estimates). Would having access to this be sufficient?

**Comment by harisang** [comment]
> The autopilot doesn't specify a gas price for the auction (and the driver doesn't return a gas price to the driver, because it doesn't fundamentally matter for the protocol anymore).

Oh wasn't aware of this, good to know.

Does the autopilot specify a block though as the "latest block" observed the moment the auction starts? Just curious about how this entry is populated in the endpoint

`"auctionStartBlock": 18784707`

Now that i am thinking about it, we could instead use the block number and just fetch the base fee, so most likely there is no need to do anything else (as long as this startBlock is provided)

**Comment by fleupold** [comment]
> Does the autopilot specify a block though as the "latest block" observed the moment the auction starts?

It does, but it's only for internal tracking purposes (to make sure simulations happen on that block). It's not broadcasted to the driver. Do you think we should remove it?

**Comment by harisang** [comment]
> > Does the autopilot specify a block though as the "latest block" observed the moment the auction starts?
> 
> It does, but it's only for internal tracking purposes (to make sure simulations happen on that block). It's not broadcasted to the driver. Do you think we should remove it?

I see. So, is there an "official" timestamp then associated with each auction that is communicated to drivers/solvers? I think in the` /solve` requests we pass a timestamp as a parameter (or maybe as part of the name of the auction), but maybe it would be good to have something formal regarding the moment the auction starts.

**Comment by fleupold** [comment]
We do still populate the `auctionStartBlock` and `competitionSimulationBlock` (might want to remove this to "competitionEvaluationBlock") but from those we can quickly get to a timestamp from Etherscan. Is this sufficient?

**Comment by harisang** [comment]
> We do still populate the `auctionStartBlock` and `competitionSimulationBlock` (might want to remove this to "competitionEvaluationBlock") but from those we can quickly get to a timestamp from Etherscan. Is this sufficient?

Yeah that sounds good.

Now that i am thinking about it, a timestamp might be the most appropriate thing to have associated with the beginning of the auction. And it could be encoded as part of a new auction_id that would really be a unique identifier. (don't want to mix different topics though so I will go ahead and close the issue)
