### ISSUE TITLE
chore: update openapi.yml for solver-driver communication

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#2182]
### Background
Solvers are supposed to change their solver engines to receive auctions and return solutions conforming to a new API.
However, the specification in [`openapi.yml`](https://github.com/cowprotocol/services/blob/a72c4c374afea785929a0a0a98d7840faf3df34c/crates/solvers/openapi.yml) seems to be out of sync with what is actually used in the communication between driver and solver [here](https://github.com/cowprotocol/services/blob/0bdbfdcc262ba92a97e023e918d120829e581c76/crates/driver/src/domain/competition/auction.rs#L26) and [here](https://github.com/cowprotocol/services/blob/0bdbfdcc262ba92a97e023e918d120829e581c76/crates/driver/src/domain/competition/solution/mod.rs#L34C15-L34C15).

### Acceptance criteria
- [ ] Update `openapi.yml` to be consistent with the rust code

**Comment by fleupold** [comment]
I'll look into updating the yaml files
