### ISSUE TITLE
bug: Still paying high gas for non-revertable txs

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2196]
### Problem
https://github.com/cowprotocol/services/pull/2176 did not help. Apparently, we have somewhere a bug with internalize flag, because transaction that get internalized (0x577767a68da9ad92d29986679ae30cd27c7394d20d91bb42c22bf61a42f49110) still return `revertable() == true`.

There might be several problems here:
1. How did we end up internalizing the settlement with interaction having `internalize==false`.
2. Do we properly propagate internalize flag from solvers? AFAIS they are sending false for these simple interactions, why would they? It's in their interest to allow it for lower costs.

### Impact
Spending more gas than necessary.

### To reproduce
Analyze the driver logs for the example transaction
[0x577767a68da9ad92d29986679ae30cd27c7394d20d91bb42c22bf61a42f49110](https://etherscan.io/tx/0x577767a68da9ad92d29986679ae30cd27c7394d20d91bb42c22bf61a42f49110)

### Expected behaviour
We should have not disabled the Mempool in this case.

**Comment by fleupold** [comment]
The transaction you shared here is actually not an internalisation but one CoW Swap order + a single interaction which is a private market maker trade.

Technically, those pose no MEV risk neither and thus don't require private submission, but right now we have no way to identify if an interaction is "risky"


Please let me know if there are other examples of this, or if the issue can be closed.

**Comment by sunce86** [comment]
Ah, sorry for false alarm then. 
Verified that low gas prices are used for internalized settlements: https://etherscan.io/tx/0xa8dfd291f6fa29b5043c7b05426f98c6f16e8708a382c0f3c7e58fcc28c3a52b

Closing the issue.
