### ISSUE TITLE
feat: EncodedSettlement as response to /solve and /reveal

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2225]
### Problem
Response to the `/solve` should be `EncodedSettlement` without interactions, while for `/reveal` it should be full `EncodedSettlement`. From this structure we should be able to reconstruct everything we need right now - and in the future (order uids, trade in/out amounts, clearing prices...).

### Suggested solution
- Encode the settlement (build `EncodedSettlement`) in the `driver` before scoring and ranking. Same implementation on the `EncodedSettlement` should be used for scoring and ranking on both sides, driver and autopilot.
- Append additional calldata for `auction_id` (currently done in the submission phase so it needs to be moved out). This will allow us to drop `auction_transaction` table.
- Submit `EncodedSettlement` except `interactions` as a response to `/solve`.
- Autopilot competition: filter out all solutions that do not contain `auction_id` (we need this for solvers running their own driver, to make sure they added it).
- Submit full `EncodedSettlement` as a response to `/reveal`. Hash `EncodedSettlement` and save, to be checked after against onchain delivered calldata.

Related to both colocation phase 2 and rank by surplus, so not sure which labels to use.

**Comment by fleupold** [comment]
Other than the name, how is EncodedSettlement without interactions different to the existing datatype that is used for this driver<>autopilot communication?

https://github.com/cowprotocol/services/blob/2c3ad7f27153e7d063eb65ac715dd6440aaf5098/crates/driver/src/infra/api/routes/solve/dto/solved.rs#L74-L86

If we can parse this dto into a data type that can be used by a shared module for ranking and scoring, do we even need to tackle this issue?

**Comment by sunce86** [comment]
> Other than the name, how is EncodedSettlement without interactions different to the existing datatype that is used for this driver<>autopilot communication?

[Here](https://github.com/cowprotocol/services/blob/main/crates/shared/src/encoded_settlement.rs) is the encoded settlement. It contains much more information needed to calculate the surplus and fees.

This would enable us to extract this struct and scoring (surplus) calculations into separate crate and reuse it for both driver and autopilot. 

How would you calculate the surplus when we switch to rank by surplus? Would you ask the driver to calculate it and trust the driver and then verify that is the same once settled, or would you just calculate it in the autopilot based on the encoded settlement and just check the hash (to verify it's the same data) once settled.

**Comment by fleupold** [comment]
Here is the information we already have for each solution candidate
- clearing prices
- matched orders
- executed amounts

> How would you calculate the surplus when we switch to rank by surplus?

Assuming I have access to the auction (which the autopilot does), I would compare the executed amounts that are reported with the limit amounts or the matched orders and normalize its sum using the prices in the auction.

**Comment by sunce86** [comment]
Executed amounts can be derived values from the `EncodedSettlement`. So, for example, in autopilot, we could calculate the executed amounts from the onchain settlement and not trust the driver on this.

`EncodedSettlement` would also be better for verifying that the solution solver promised to deliver is actually delivered onchain (by simply comparing the whole struct (or a hash of struct) with the onchain data). This is also more aligned with our long term goal to rely more on the onchain format of data. I don't see any advantage of using custom data formats as a response to /solve like we do today.

This could be also combined with the problem of building the auction-transaction relation, once the solvers run their own driver (trust issue). Solvers can be required to submit `auction_id` at the end of calldata (like the reference driver do today), but the value of auction_id they submit must be enforced somehow. I proposed a solution to hash the EncodedSettlement (without `interactions` to allow solvers to submit a different solution with the equal quality as promised solution) + `auction_id` and save that hash to db during competition time. After being settled, we would hash the onchain solution and `auction_id` and verify it's the same as promised.

Definitely not a priority task but might be worth keeping it around as I see a value in it long term.
