### ISSUE TITLE
bug: Wrong signness in new API

### ISSUE THREAD

**Issue by marcovc** [cowprotocol/services#2229]
### Problem

A liquidityNet map in a concentrated pool should be a int->int (or maybe int->big_int). It can be negative too:

https://github.com/cowprotocol/services/blob/a72c4c374afea785929a0a0a98d7840faf3df34c/crates/solvers/openapi.yml#L348

### Impact

Can lead to reverts because solvers have the wrong AMM state.

**Comment by fleupold** [comment]
I think this is mainly a documentation bug. Looking at the dto, the type is actually signed

https://github.com/cowprotocol/services/blob/bffb3cb39676c6fe01f818e95992d6384f5dd587/crates/solvers/src/api/routes/solve/dto/auction.rs#L347-L348

So it shouldn't lead to reverts.
