### ISSUE TITLE
bug: "Low_fee" error for ETHflow orders with zero-signed fee.

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2248]
During the test we did on Barn where CoW Swap was only sending zero-signed fee orders, it was observed that ETH-flow orders (orders selling native ETH) got stuck.

Here is an example: 0xc1b5c07ab6d358bbae5b0ce132850599ff47b8172fa0719722781daed2df4cbdd02de8da0b71e1b59489794f423fabba2adc4d93ffffffff

and [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-21T10:00:00.000Z',to:'2023-12-21T22:00:00.000Z'))&_a=(columns:!(log),filters:!(),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'%220xc1b5c07ab6d358bbae5b0ce132850599ff47b8172fa0719722781daed2df4cbdd02de8da0b71e1b59489794f423fabba2adc4d93ffffffff%22%20AND%20%22low_fee%22'),sort:!(!('@timestamp',desc)))) is a log hinting at the root cause. 

Another example:
0x20a6d267c38baf7cdfd58b2ccc46bd500ea4ab6a03f7d562d026cb29aaaecb39d02de8da0b71e1b59489794f423fabba2adc4d93ffffffff

and [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2023-12-21T10:00:00.000Z',to:'2023-12-21T22:00:00.000Z'))&_a=(columns:!(log),filters:!(),index:ea511870-d9b3-11ed-a9d0-a17451f01cc1,interval:auto,query:(language:kuery,query:'%220x20a6d267c38baf7cdfd58b2ccc46bd500ea4ab6a03f7d562d026cb29aaaecb39d02de8da0b71e1b59489794f423fabba2adc4d93ffffffff%22%20AND%20%22low_fee%22'),sort:!(!('@timestamp',desc)))) is an identical log.

**Comment by fleupold** [comment]
Do we know what the correct fix is for this?

**Comment by harisang** [comment]
Haven't looked into this tbh. I believe @MartinquaXD had got ideas around this.
