### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#226]
Currently, build fails on Windows OS. Some of the smart contract json files fail to parse with the following error: 

> error: failed to run custom build command for `contracts v0.1.0 (C:\Users\lenas\work\backend\main\crates\contracts)`
> 
> Caused by:
>   process didn't exit successfully: `C:\Users\lenas\work\backend\main\target\debug\build\contracts-edc0b80862fececf\build-script-build` (exit code: 101)
>   --- stdout
>   cargo:rerun-if-changed=build.rs
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2Authorizer.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2BasePool.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2BasePoolFactory.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2Vault.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2WeightedPoolFactory.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2WeightedPool2TokensFactory.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2StablePoolFactory.json
>   cargo:rerun-if-changed=C:\Users\lenas\work\backend\main\crates\contracts\artifacts\BalancerV2LiquidityBootstrappingPoolFactory.json
> 
>   --- stderr
>   error[internal]: left behind trailing whitespace
>       --> <stdin>:1684:1684:16
>        |
>   1684 |             pub
>        |                ^
>        |
> 
>   warning: rustfmt has failed to format. See previous 1 errors.
> 
>   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Json(Error("expected value", line: 1, column: 1))', crates\contracts\build.rs:296:10

**Comment by sunce86** [comment]
Workaround for now is to manually fix the smart contract files. For example, file https://github.com/cowprotocol/services/blob/d68f45720c50c775057b899cc6ae973328ad8220/crates/contracts/artifacts/BalancerV2NoProtocolFeeLiquidityBootstrappingPoolFactory.json

from `BalancerV2LiquidityBootstrappingPoolFactory.json` 
to `{"key":"BalancerV2LiquidityBootstrappingPoolFactory.json"}`

This needs to be done for all files containing only name of the json file. Currently, those are:

`crates/contracts/artifacts/BalancerV2NoProtocolFeeLiquidityBootstrappingPoolFactory.json`
`crates/contracts/artifacts/BaoswapFactory.json`
`crates/contracts/artifacts/BaoswapRouter.json`
`crates/contracts/artifacts/HoneyswapFactory.json`
`crates/contracts/artifacts/HoneyswapRouter.json`
`crates/contracts/artifacts/SushiSwapFactory.json`
`crates/contracts/artifacts/SushiSwapRouter.json`
`crates/contracts/artifacts/SwaprFactory.json`
`crates/contracts/artifacts/SwaprRouter.json`

**Comment by nlordell** [comment]
Ah! Its a symbolic link issue.

Maybe there is a Git setting to do this automatically?

**Comment by nlordell** [comment]
Quick googling suggests that symbolic links in Git aren't portable, so maybe we should stop using them.

**Comment by sunce86** [comment]
When resolved. this PR should be reverted: https://github.com/cowprotocol/services/pull/228
