### ISSUE TITLE
feat: Refactor `auction_transaction` relation

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2282]
### Problem
With colocation, `auction_id` is appended to transaction call_data always (and this will also be required and verified once solvers run their own driver), so it's not needed to keep the `<from, nonce>` pair anymore. This paIr was used pre-colocation so that we connect the auction to the transaction hash.

Currently, our database looks like this:

`settlements` table (initially partially populated by `EventHandler` (without `<from, nonce>`), and later `OnSettlementEventHandler` updates  `<from, nonce>`):
- block_number
- log_index
- transaction hash
- Optional from
- Optional nonce

`auction_transaction` table (populated by `OnSettlementEventHandler`):
- auction_id
- from
- nonce

## **Proposal**:

`settlements` table:
- block_number
- log_index
- transaction hash
- Option<auction_id>

Drop `auction_transaction` table.

`EventHandler` would insert settlement on each new event, while `OnSettlementEventHandler` would fetch all settlements without `auction_id` and populate that field and all depending data (settlement observations and order executions). This would make `OnSettlementEventHandler` completely reorg friendly since right now the `auction_transaction` table is not reorg friendly and does not contain column `block_number` which would allow entry deletion when `EventHandler` detects reorg.
 
Related to https://github.com/cowprotocol/services/issues/2275

**Comment by MartinquaXD** [comment]
Seems good to me. I don't see any obvious problems with this approach and always found that we had to join using `from` and `nonce` instead of `auction_id` clunky.

**Comment by sunce86** [comment]
Done with https://github.com/cowprotocol/services/pull/2283
