### ISSUE TITLE
feat: Fix market price checker for market orders

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2312]
### Problem
As a consequence of https://github.com/cowprotocol/services/pull/2304, market orders 
contain a bug, because their sell_amount doesn't contain the fee. This leads to market orders being classified as liquidity orders. https://github.com/cowprotocol/services/blob/main/crates/shared/src/order_validation.rs#L682

An order being classified as liquidity order might lead to order being less likely to be picked up by solvers? (Haris confirmed that only quasilabs can solve them as part of COW).

Example order: https://dev.explorer.cow.fi/orders/0xa1b886011c8d077187bead0e7d0ba1077f68de6bc0d6423b9ac643ead2153e33dd9eb88c5c6d2a85a08a96c7f0cccce27cb843cb65ae7f5a?tab=overview

**Comment by fleupold** [comment]
Can you explain orders are more often considered as out-of-market due to @2304. This is not intuitive to me (and makes it hard to understand if #2312 is the right fix)

**Comment by fleupold** [comment]
Wouldn't the right fix in this case be to compare

`(sell_amount+fee_amount)/buy_amount < (quote_sell+quote_fee)/quote_buy`

?

**Comment by sunce86** [comment]
`sell_amount` is a signed sell amount from order so it contains the fee already.

**Comment by fleupold** [comment]
> sell_amount is a signed sell amount from order so it contains the fee already (it's a sell_amount_before_fee value).

At least here (see below) we are using the raw orders sell amount, which (at least for market orders) doesn't contain the fee amount:

https://github.com/cowprotocol/services/blob/d4fc3c22dd556975439b9ba280f39a2cd0347482/crates/autopilot/src/domain/fee/mod.rs#L50-L56
