### ISSUE TITLE
chore: Phase out `PriceQuality::Verified`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2322]
With the backend trying to verify as many quotes as possible there is no reason to distinguish between `Optimal` and `Verified` anymore.

This PR tracks the work to phase out the `verified` variant. This is mostly a trivial code change in the backend but needs to be coordinated with the frontend so we don't discard quote requests due to deserialization errors.

**Comment by fleupold** [comment]
I think there may still be some value in this field. At least when sending the response back to the frontend it would be nice to indicate if the quote was verified (so that the frontend could show something to the user).
