### ISSUE TITLE
chore: Discard quotes where the reported and simulated outamounts are too different

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2341]
### Background
At the moment we the quote simulation logic takes the provided calldata and simulates it to get the actual `out_amount` for the given trade. If the simulation succeeds we currently completely ignore the `out_amount` that was calculated and reported by the solver.
However, this could mask issues where a solver thinks it's able to accurately compute a trade for a token but in fact the result is way off. This is most likely going to happen for tokens that take fees on transfer.
Right now we try our best to detect those and mark them as unsupported but the goal is that with verified quotes we no longer need that check because we can verify whether a solver knows how to solve for those tokens.

### Details
For this to work we actually have to compare the reported `out_amount` with the simulated one and discard any quotes that are off. We could be very strict about it and discard all solutions that diverge by even 1 wei or we could be less strict and introduce a configuration parameter for the threshold (e.g. 0.1%)

### Acceptance criteria
Quotes where the solver reports a vastly different out_amount than what we simulate should be discarded with a log.

**Comment by fleupold** [comment]
Shouldn't the solver's execution contain some slippage tolerance? This means that if their estimate is too far off, their solution wouldn't even simulate but instead revert. If we can expect them to use the same slippage tolerance for solving, we wouldn't have to drop any quotes (just re-write the estimated amount).

**Comment by MartinquaXD** [comment]
> Shouldn't the solver's execution contain some slippage tolerance?

I think the only reason a quote should already contain some slippage tolerance is to allow for differences when we simulate on a different block than what they computed the solution. IMO the solvers should compute what's theoretically possible and not dictate a lower bound for slippage the user can set.
So if they math is wrong and they see they only need to produce X tokens to pass the limit price of an order they might compute what they think is a trade that satisfies the price but is in fact worse than the limit price.
