### ISSUE TITLE
feat: Support unbacked orders

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2343]
### Problem
At the moment we require the user has the entire `sell_amount` for fill or kill orders or at least 1 wei (already weird) for partially fillable orders.
This prevents a somewhat advanced workflow of first creating the order and then funding the trader account.
Originally we only imposed this restriction as a means of spam protection. However, if a user is determined they are able to spam the system anyway so we might as well get rid of this restriction to allow the frontend to support some more use cases.

### Suggested solution
Get rid of balance checks before placing an order. Keeping the allowance check (i.e. `allowance >= total_sell_amount`) makes sense IMO. Note that the `allowance` requirement should still take `permit` pre-interactions into account (which our `Balances.sol` helper contract already does)

**Comment by MartinquaXD** [comment]
cc @alfetopito since you were involved in coming up with the details.

**Comment by alfetopito** [comment]
Was addressed on https://github.com/cowprotocol/services/pull/2558
