### ISSUE TITLE
feat: Support internal buffer trading during quote verification

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2345]
### Problem
For small trades cowswap can seem very undesirable compared to other dexes for example on defillama.
The reason is that we basically query different dex APIs and forward the `out_amount` computed by the API. However, because executing the proposed trade in the context of our settlement contract incurs a bunch of gas overhead. This can sometimes almost double the fee which hurts the most for smaller trades.

### Suggested solution
One way to improve the situation is by allowing internal buffer trades while quoting.
Let's say 1Inch reports a gas cost of 200K. When we add the overhead of the settlement contract we'll end up with 306K. That's over 50% more gas which directly translates to a higher fee.
However, in the context of an actual settlement this trade would be internalized if it's possible. Meaning we would not execute the 1Inch transaction and instead trade with the same price against the buffers of the settlement contract.
So in this example if our settlement contract holds enough tokens at the time of quoting we could actually provide the same price as 1Inch but now with ~50% less fees (106K vs 200K).

To make sure the rules of the game are respected we'd need to verify that the trade actually works while executing the 1Inch transaction, check that the sell_token is trusted (requirement for internal buffer trading) and finally simulate the same trade without the 1Inch interaction to verify that we have enough funds in the buffers.

One thing to note is that we can't trade buffers indefinitely. So for example it could happen that 2 users create an order based on an internalized quote but there are only enough buffers for 1 of the trades.
In that case the second user would only get their order matched if executing the trade without internalization does not eat up their whole slippage.

Since quote verification can be disabled with a CLI flag I would suggest to first assume we don't run into the issue and only if it's actually a problem implement a more complex solution. For example we could try to enforce that at most X% of the buffer may be used for internalizing quotes to allow up to `100 / X` users to create orders without running into that issue.

### Acceptance criteria
Quote verification returns the gas cost of an internalized trade if it would respect the "rules of the game".

**Comment by sunce86** [comment]
This seems to me as a nice to have feature (low priority). I would expect a better quote competition to handle this and reward the solver with the internalized quote. Or am I missing something and we need this for verification of ALL quotes for all solvers (not just dexes)?
