### ISSUE TITLE
bug: ETH-flow doesn't work with zero-signed fee change as order is classified as market

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2356]
We noticed that ETH-flow orders, while they are now submitted, created and executed with the CoW Swap zero-signed fee change, they always pay zero fee as they are classified as market and not limit orders.

See [here](https://cowservices.slack.com/archives/C0361CDD1FZ/p1706877239122179) for relevant discussion.

**Comment by fleupold** [comment]
@sunce86 can you tackle this issue this week?
