### ISSUE TITLE
Integrate Hashflow liquidity

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#236]
Hashflow ([docs](https://docs.hashflow.com/hashflow/taker/getting-started)) offers an RFQ system which supports swaps within and across chains.

Ideally we would integrate `Hashflow` as another liquidity source in the driver such that every solver could automatically use that liquidity.
We currently have no RFQ support for integrating liquidity. As usual RFQ means that you first query the price you are interested in and if you are happy with the price commit to it and request the signed quote which is ready for execution.
This work flow is not that compatible with our code base at the moment but I have some ideas to make it work.

## Approach 1 (supply solvers with signed orders)
To make using the liquidity as easy as possible for solvers we need to query prices and get signed quotes during each batch auction and send those out.
This approach is very simply but `Hashflow` might penalize such behavior (committing to quotes and not executing) in a way that makes this approach not feasible.

## Approach 2 (supply solvers with prices and get quotes afterwards)
If approach 1 does not work things could get very tricky for multiple reasons:
1. In order to rate settlements we have to know the gas cost of each settlement. Currently we simply simply simulate the settlements coming from the solvers. But if we don't send the solvers already signed quotes we need some sort of post processing to know the gas cost of settlements including `Hashflow` orders. [slack thread](https://cowservices.slack.com/archives/C0369B2UF6J/p1651684089420069?thread_ts=1651683736.730569&cid=C0369B2UF6J)
2. Because the signed quote might be different from the `Hashflow` price estimate solvers using the estimate could produce solutions which are no longer valid when we know the final price. Either the final quote has a worse price which could violate users limit prices or it has a better price which would likely violate fairness properties of the solution.

TBH I estimate the chance that this approach works to be very slim but if it did it would still be very convenient for solver implementers.

## Approach 3 (supply solvers with prices and let them get the quotes)
Only solvers would know which quotes they actually need (which ones are advantageous for their solution). So it stands to reason that some more generic solution to RFQ systems could be that we supply the solver with all the prices (which is free) and make it easy for them to get the signed quotes for the trades they are actually interested in.
This would mean solver teams would have to put it some work to actually integrate with RFQ systems but at a first glance the amount of work seems reasonable.

**Comment by tbosman** [comment]
> Because the signed quote might be different from the Hashflow price estimate solvers using the estimate could produce solutions which are no longer valid when we know the final price. Either the final quote has a worse price which could violate users limit prices or it has a better price which would likely violate fairness properties of the solution.

On first read this actually doesn't sound very different from how it works with slippage occurring in AMM calls right now. Couldn't this same approach work for RFQ? Ie add a configurable slippage tolerance and don't submit the trade if it comes in above that?
