### ISSUE TITLE
chore: Allow providing custom appdata when cancelling an order

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2365]
### Background
Support for cancelling an open order and submitting a new one (effectively replacing the old one) was introduced in https://github.com/cowprotocol/services/pull/239.
The idea is that the new order has to have an appdata value that is equal to the hash of a cancellation request for the old order uid.
Because we have to be able to recover the owner from the signature of the new order and the appdata matches the cancellation of the old order uid we prove that it was the actual owner that intended to cancel the old order and not some random person messing with us.

Since we introduced that feature we also extended possible use cases for appdata so it's reasonable to expect that someone could also replace an old order with a new order that also contains some custom appdata you care about.
But because we currently expect some specific value for the cancellation appdata this is not possible.

### Acceptance criteria
A mechanism that allows you to cancel an old order while also providing additional appdata for the new order.
This probably requires you to provide the appdata content (i.e. the unhashed JSON string) which contains a new field with the order uid to cancel in addition to all the appdata values we expect by now.

This endpoint is used very rarely so we might get away with a breaking change and not introducing a new endpoint for this.

**Comment by Nagu40** [comment]
# Existing endpoint for cancelling orders
@app.route('/cancel_order', methods=['POST'])
def cancel_order():
    # Extract old order uid and signature from request
    old_order_uid = request.json['old_order_uid']
    signature = request.json['signature']
    
    # Verify signature and cancel old order
    if verify_signature(old_order_uid, signature):
        cancel_old_order(old_order_uid)
        
        # Extract appdata content for new order
        appdata_content = request.json['appdata_content']
        
        # Parse appdata content and extract necessary information
        new_order_info = parse_appdata_content(appdata_content)
        
        # Generate new order with provided information
        new_order = generate_new_order(new_order_info)
        
        # Process new order (e.g., submit to database)
        process_new_order(new_order)
        
        return jsonify({'message': 'Order cancelled and new order submitted successfully.'}), 200
    else:
        return jsonify({'error': 'Invalid signature.'}), 400
