### ISSUE TITLE
feat: Allow solvers to specify custom headers with their requests

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2372]
### Problem
Solvers may have custom authentication logic based on HTTP headers which they need to configure for their solvers.

### Suggested solution

The code has already been prepared with a comment here:

https://github.com/cowprotocol/services/blob/2a25e9c4a756cc40365dc3d22e67f398c83e6854/crates/driver/src/infra/solver/mod.rs#L102-L119

We should make the exact header name also configurable in the `toml` config cf:

https://github.com/cowprotocol/services/blob/2a25e9c4a756cc40365dc3d22e67f398c83e6854/crates/driver/example.toml#L1-L7

Maybe we can add an optional headers list with key value pairs to this config object and pass it all the way through to the infra component above.

### Acceptance criteria
- Driver binary can be configured with arbitrary header values per solver
- Headers are sent as part of both quote as well as solve requests

**Comment by jhweintraub** [comment]
Do you want to be able to support any arbitrary header which is included in the Reqwest library or just Authorization? I've implemented the logic for the auth header but allowing anything arbitrary will be a lot of work and should probably be specified in a different feature request?

This is my first PR to this repo and i'm still learning rust so feedback is appreciated. PR #2395

**Comment by fleupold** [comment]
This has been completed.
