### ISSUE TITLE
chore: Stop supporting legacy solver/driver API with the weekly release of March 18-22, 2024

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2384]
Opening this to set a final date after which we can officially stop supporting the legacy API. The date has been communicated to all solver teams.

**Comment by sunce86** [comment]
Closed in favor https://github.com/cowprotocol/services/issues/2437

**Comment by fleupold** [comment]
All that is missing here is Quasimodo to move over to the new API (@harisang, @fhenneke)
