### ISSUE TITLE
feat: New CIP rules switch mechanism

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2407]
### Problem
Inspired by https://github.com/cowprotocol/services/issues/2382

Autopilot needs to have a way to signal to drivers that rules of the game are changing.  Each time new CIP is approved, rules of game can change and both autopilot and drivers need to make the switch at the same "time" (auction number, block_number etc).

### Suggested solution
A new field `next_cip: block_number` in `driver` interface which will indicate a block number from which the new rules should be applied.

Slightly more explicit way is to send extended configuration struct each time new cip is accepted:

```
cips: {
cip_38: block_number,
cip_40: block_number, 
cip_45: block_number,
}
```

### Alternatives considered
?

**Comment by mfw78** [comment]
With regards to post-merge networks, would it be more suitable to use a specific timestamp as opposed to a block number?

**Comment by fleupold** [comment]
Is this really required though given that the autopilot and driver are still deployed in sync? For full co-location I agree some indication is needed, but I think it could be as simple as the autopilot specifying a protocol version number in its instance file and the CiP stating as of which version a specific behaviour should be implemented (with a rough target date).

**Comment by sunce86** [comment]
Not required before full co-location.
