### ISSUE TITLE
chore: Replace `net_version` with `eth_chainId`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2414]
### Background
Some node providers don't expose the `net` module or node clients might not enable it by default. This causes the backend to not work with for example the public [merkle RPC](https://freerpc.merkle.io/).

Since we are only using the `net` module to get the chain id (with `.net().version()`) we can get rid of the `net` dependency by using `eth_chainId` instead.
Note that `ethcontract-rs` currently also relies on `net_version` but a [PR](https://github.com/cowprotocol/ethcontract-rs/pull/967) to address that is already available so when tackling this issue we should also bump the `ethcontract-rs` version.

### Acceptance criteria
Service works using an RPC without `net` module (e.g. `https://eth.merkle.io`).

**Comment by MAGICXPLUS** [comment]
Y

**Comment by MartinquaXD** [comment]
Already fixed; just forgot to close the issue.
