### ISSUE TITLE
chore: Use redis to cache native prices

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2417]
### Background
Currently we require native prices at 2 points in the code:
1. To include an order in an auction we need to have the native price for the order's sell and buy token. This happens in the autopilot which always has only 1 instance. If we are missing native token prices some orders might not be part of the current auction.
2. When a user wants to create an order we make sure that we can compute a native token price for buy and sell token to not run into troubles in `1`. This happens in the orderbook which might be replicated.

### Details
That means currently there is always 1 autopilot and at least 1 but possibly multiple orderbook instances that all need to know about native prices which currently don't share their knowledge. That leads to 3 undesirable effects:
1. We make more native price estimates than necessary which can overall be pretty costly.
2. When restarting the `autopilot` it can take a bit for all native prices to be ready in cache again. Until then we will not have all open orders as part of the auction which is obviously suboptimal and increases the cost of restarting the system.
3. Let's say a user wants to create an order trading an exotic token. While creating the order the orderbook will already fetch the native prices for sell and buy token. After the order gets added to the DB the autopilot will update the current auction soon after. Since the traded tokens are exotic the autopilot likely doesn't know the native prices yet so it first have to compute them themselves before the order can be added to the auction. This delay contributes to the slowness users regularly complain about.

We previously considered tackling this issue by writing a completely new service described in https://github.com/cowprotocol/services/issues/1555 and others. This was deemed too much work compared to the impact it would have.

What I think we should alternatively consider is trying out something like [`redis`](https://redis.io/) which already has a good rust [library](https://github.com/redis-rs/redis-rs). This would already address most of the pain points (since regular price estimates can't be cached that well anyway) while adding very little complexity to the code base or additional work to the backend's roadmap.

### Acceptance criteria
Instead of storing everything in memory inside the [CachingNativePriceEstimator](https://github.com/cowprotocol/services/blob/a0e3ec77746957fb5a21b894d72cc99b12520af6/crates/shared/src/price_estimation/native_price_cache.rs#L298-L239) we should read from and write to a single `redis` instance inside our cluster. That way we can keep all of the interfaces as they are now while immediately fixing all 3 issues we currently face.

**Comment by fleupold** [comment]
I'm surprised. Aren't we already caching native price requests from different pods in our nginx cache?

**Comment by MartinquaXD** [comment]
Ahh, right. You implemented that some time ago.
However, the native price cache is currently not aware of that fact. When we build an auction we only get the prices that are already cached and schedule missing prices to be fetched in a background task. Since that logic was written before the nginx request caching the cache doesn't "know" yet that most prices should be extremely quick to fetch even when they are not yet cached in memory.

We should probably not simply revert back to the old implementation (where we simply try to fetch all prices) because that will time out if you don't have an nginx caching your requests (e.g. local deployments for testing). But we could fetch prices time boxed for 1s or so. That's not fast enough to fetch a completely uncached price but we should probably be able to get all or most of the prices that are cached on an nginx level.
That would be a smaller change without adding the complexity of another dependency. Will try that first.
