### ISSUE TITLE
Configurable deny list for balancer pools

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#242]
Apparently it's possible for balancer pools to report a different balance than the respective token contract reports it should have. This discrepancy can lead to failed transactions like [here](https://cowservices.slack.com/archives/C035TDPHQAJ/p1654021806753079).

A simple work around would be to allow deny-listing specific balancer pool ids via a runtime argument.

**Comment by bh2smith** [comment]
I think it would probably be more appropriate to deny-list liquidity sources by address. Then this solution would be generalizable to all types of supported pools. Given that it has already been done, I guess I am too late to the party.
