### ISSUE TITLE
feat: Reject orders with signed fee_amount != 0

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2437]
### Problem
Starting from 19th of March (as stated in [CIP38](https://snapshot.org/#/cow.eth/proposal/0xfb81daea9be89f4f1c251d53fd9d1481129b97c6f38caaddc42af7f3ce5a52ec)) orders with non-zero fee should be rejected by the protocol.

### Suggested solution
Rejection means the orders with non-zero fees will no longer be settled by the protocol, implying:
1. Backend API needs to reject creation of new orders and return a specific error type in this case.
2. Existing open orders within the orderbook should be filtered out in solvable orders query (when autopilot auction is built).

### Additional context
Market orders cleanup in all components can be done once this is released.

### Acceptance criteria
POST-ing a new order with non-zero fee fails with specific error.

**Comment by harisang** [comment]
I wonder whether we can avoid (2) (i.e., open orders being ignored and rejected) by instead doing the following:

1. Decide on an activation block (some block after Tuesday March 19 midnight)
2. Prevent new fixed-fee orders to be created that have an expiration deadline after the block decided in (1).

**Comment by sunce86** [comment]
Possibly duplicate of https://github.com/cowprotocol/services/issues/2384.

Will keep the issue open as it contains more detailed info around implementation itself.
