### ISSUE TITLE
Handle very slow price estimation requests

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#244]
Usually every price estimator always takes a similar amount of time to return an estimate.
But [sometimes](https://cowservices.slack.com/archives/C0361CDD1FZ/p1653028275381829) they encounter a period of time where every request takes way longer which in turn results in very [high response times](https://dashboard-projects.gnosis.io/d/3Z-RJHuGz/gpv2?viewPanel=83&orgId=2&from=1654070991325&to=1654102058143) for multiple of our API endpoints.

One way to automatically handle such situation would be to keep track of how often an estimator encounters an unusually long response time and when that happens too frequently back off from that estimator for a while and try again later.
This would keep the platform more responsive as a whole while requiring no manual intervention from the colleague doing on-call.

This rate limiting should be accompanied by metrics which we can use to trigger an alert if the same service has to be ignored for extended periods of time which might point to some bigger issue we would like to inform those external teams about.

The back-off strategy will probably have to be fine tuned because we don't want to lose out on potentially better prices for the user because we backed off way longer than required.

**Comment by vkgnosis** [comment]
If we consider let's say 5 seconds healthy and longer unhealthy, then another solution would be to set this as a time out on the estimators. We have an implicit time out on them already through our http client timeout (10 seconds iirc) but it isn't very accurate as an estimator might make multiple http requests or doing something else that is weird. So we definitely want some kind of time out and a metric to keep track of it.

The advantage of the timeout solution is that it is simpler and feels more intuitive than applying rate limiting terminology to it.

The advantage of the rate limiting solution is that we **A** actually back off on requests, meaning we take load of the estimator and that **B** by disabling the estimator we reduce the response times of our api by more than just with a timeout.

A: For the external estimators I expect that we are not causing their slowness so rate limiting based on response time is not needed. (Rate limiting based on them telling us we're getting rate limited through a status code still makes sense.) For our own estimators (baseline going to our nodes, Quasimodo) it might make sense but baseline is heavily cached and for Quasimodo we probably want to ensure that it can handle the load it is getting.

B: Assuming a slow (unhealthy) price estimator, with the timeout strategy a combined price estimator would always be as slow as the timeout. On the other hand with the rate limit we disable the whole estimator so it doesn't make the combined response time slower.

Is the extra complexity of the rate limit compared to plain time out worth the better response times? I feel yes. But I had to type up this whole thing to make up my mind :) .

**Comment by MartinquaXD** [comment]
Glad we arrived at the same conclusion. I feared a different outcome while reading the long post. 😅
