### ISSUE TITLE
feat: Allow external solvers to withhold fees

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2440]
### Problem
Solvers raised interest in doing the fee computation and withholding themselves even if they are using the CoW provided driver logic. This means they would return trades with all fees incorporated (network and protocol fees) and require the driver to skip any further adjustments

### Suggested solution
- allow a per solver config flag describing whether the driver should apply fees or not
- forward all fee policies to the solver

### Alternatives considered
Don't implement this and instead use this as an argument for solvers to switch to full co-location

### Additional context
This should only be implemented for the new solver engine interface (not legacy http solver) as the latter will be discontinued in less than one month.

### Acceptance criteria
Solvers that use private liquidity can withhold the protocol fee by offering a slightly worse quote.

**Comment by sunce86** [comment]
Note that this would cause gas cost fees to be shown as 0 for these orders as we wouldn't have a way to calculate them (on the autopilot side).

If we want this, I assume we first need to make a long term plan how we want to show the gas fees to the user.

**Comment by sunce86** [comment]
I also think the solver accounting needs to refactor their fees calculation to not use autopilots calculation in this case (at least until solvers run their own driver and are paying for their submission).

**Comment by fleupold** [comment]
As far as I understand protocol fees are computed based on the executed amounts and fee policies from the auction (not based on the adjusted clearing price vector as this one includes both protocol as well as gas fees). @fhenneke can you confirm if this is the case?

As to how we show fees to the user, I think this challenge is not related to allowing solvers to withhold protocol fees. We can compute the protocol fees regardless of the solver specified fees and display those to the user. As for network fees, with "rank by surplus" solvers can already "price in" the network fee (and e.g. charge you 0 for a limit order if they settle it with own inventory at a slightly worse price).

**Comment by fhenneke** [comment]
> As far as I understand protocol fees are computed based on the executed amounts and fee policies from the auction (not based on the adjusted clearing price vector as this one includes both protocol as well as gas fees). @fhenneke can you confirm if this is the case?

This is correct. Protocol fees are computed from executed amounts and fee policies.
There is one subtle exception for the volume cap of out-of-market sell orders. But I would not worry about that and potentially it is changed with the initial implementation of CIP-38 anyways.

**Comment by Mateo-mro** [comment]
Done in https://github.com/cowprotocol/services/pull/2544
