### ISSUE TITLE
bug: OneInchSpotPrice estimator returning bogus native prices

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2444]
We noticed an issue with at least one native price estimation, namely this token

`0x48Fb253446873234F2fEBbF9BdeAA72d9d387f94`

that was often reported by OneInchSpotPrice estimator to be worth ~79M ETH.

see logs [here](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:now-30d%2Fd,to:now))&_a=(columns:!(log),filters:!(),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'%220x48fb253446873234f2febbf9bdeaa72d9d387f94%22%20AND%20%22price%20estimate%22%20AND%20%2279071526.21036524%22%20AND%20%22estimator%3D%5C%22OneInchSpotPriceApi%22'),sort:!(!('@timestamp',desc))))

There was a statistical test proposed at some point, but given it is not in place yet and given that verified quotes will probably not work for native price estimates, should we maybe consider adding some very loose limits on the native price estimates?

Something like "no token has a price more than, say 100 ETH?"

Not sure if this is a rare case, and I guess one would need to search in the logs (not sure how to do a '>' test in the logs though) to find out how often we have such cases.

**Comment by fleupold** [comment]
Fixed by #2603
