### ISSUE TITLE
chore: Allow configuring contracts which are exempt from protocol fees

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2461]
### Background
Our CoW AMM experiment is placing a lot of limit orders, some of which are being classified as out of market orders (mainly because they are partially fillable and usually a bit larger than what is currently fillable at the specified price).
It therefore pays significant protocol fees, impacting it's own PnL (cf. https://cowservices.slack.com/archives/C067ZLV8U13/p1709148518771459). In the next phase of the experiment, we want solvers to settle CoW AMM orders as JIT liquidity (thus not paying any protocol fee) and will think about monetizing this type of order separately.

### Details
While it would be nice to index all CoW AMM orders automatically and exempt them from fees, I think the easiest and most pragmatic way for now would be to allow for a list of exempt traders (possibly with a discount factor).
In the future, we may have on-chain registries and more complicated logic for fee discounts (e.g. holding X CoW token results in X fee discount), but we can cross that bridge when we get there.

### Acceptance criteria
https://explorer.cow.fi/address/0xBEEf5aFE88eF73337e5070aB2855d37dBF5493A4 no longer pays any protocol fees.

**Comment by sunce86** [comment]
Does this mean using Liquidity orders type? This would make us move further from actually deprecating this type of order.

**Comment by fleupold** [comment]
In the current phase, these orders are placed via the API as limit orders, which should be exempt from protocol fees (but subject to surplus). I don't suggest to use liquidity orders for this, but instead have a list of owners which are exempt from fees.

In the next phase solvers are supposed to compute the optimal executed amounts just-in-time. However, the orders will still capture surplus. For this, we need to ammend the JIT fulfillment subtype. Note, the JIT orders are never passing through the API (they are created on the solver side and part of the solution), so I think we should still deprecate the Liquidity order type in the Orderbook and API as soon as possible.
