### ISSUE TITLE
chore: Remove exhaustive e2e tests for surplus fee

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2468]
### Background
We spend about 20% of our time in the e2e tests for protocol fees. This is too long for a single fee policy. We do now have faster driver integration tests which should be used to test different behaviors. e2e should be reserved for the basic check that protocol fees work (but not all permutations of possible cases)

![Image](https://github.com/cowprotocol/services/assets/1200333/929ef348-31e2-4eb0-ae19-2803fe8da493)

### Acceptance criteria
Have a single test case for protocol fees which combines different fee policies in their most commonly used path

**Comment by squadgazzz** [comment]
> Have a single test case for protocol fees which combines different fee policies in their most commonly used path

Is it really possible to create a single case for all the policies? For different policies we have to start autopilot with different configurations.

**Comment by fleupold** [comment]
I think we should have one test per fee policy (surplus, price improvement, volume) that tests a single instance, maybe the most interesting one. Testing the whole matrix (sell/buy, partial/non-partial, etc) can be left up to the driver tests.

**Comment by squadgazzz** [comment]
A refactoring for simplification is also required: https://github.com/cowprotocol/services/pull/2539/commits/65fd0ab9c9b9aaac82b6b5b60106e23a2bcaaada#r1532938688
