### ISSUE TITLE
chore: Remove all paths of Market orders

### ISSUE THREAD

**Issue by Mateo-mro** [cowprotocol/services#2500]
### Background
Since Markets orders based on the fee will be deprecated, we need to remove all the logic associated with the `market` order class.

### Details
Remove all path executions related to `market` order class.

### Acceptance criteria
There is no code path execution linked to the `market` order class, and all the tests have been adapted successfully.

**Comment by sunce86** [comment]
One note is that we still need to support "legacy" Market orders in the database and backend API, for backward compatibility. But in the autopilot, driver, solvers I think we are safe to remove all code paths for market orders.
