### ISSUE TITLE
feat: Forbid fee policies with factor = 1.0

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2501]
### Problem
We need to add a protection against sending the fee policies with factor = 1.0.

Here it is explained why this is not allowed.
https://github.com/cowprotocol/services/pull/2497#discussion_r1517443337

### Suggested solution
Do not attach fee policy in autopilot if the factor is 1.0.

### Alternatives considered
On autopilot startup?

**Comment by MartinquaXD** [comment]
An error during start up seems more appropriate. Otherwise we might be running quite some time without collecting fees without noticing.

**Comment by fleupold** [comment]
I think with integration specified volume fees we need to also assume a UI could set invalid factors (however I believe the max fee we will allow is 1%).

Also, doesn't this task already apply to price improvement and surplus based fees as they also have a volume factor component?
