### ISSUE TITLE
feat: Parse partnerFee to appData

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2505]
### Problem
Implement parsing of partnerFee to `OrderAppData`.

Schema here: https://github.com/cowprotocol/app-data/blob/main/src/schemas/partnerFee/v0.1.0.json
Example here: https://dev.explorer.cow.fi/orders/0x018c5760dc6d2caf5fae9968fe80371d6a17edd4d4cbe30f42b0b47de6f9dda479063d9173c09887d536924e2f6eadbabac099f565df6d2b?tab=overview

This is a precondition for for https://github.com/cowprotocol/services/issues/2502

**Comment by sunce86** [comment]
Two solutions here to make the appdata partnerFee available to autopilot AFAIS:

1. Add new field `fee_policies` to `model::Order` and forward as such to `autopilot`
2. Add parsing of `model::order::full_app_data` on autopilot side

WDYT?

**Comment by fleupold** [comment]
I think autopilot already needs to have app data parsing for native eth flow orders.
