### ISSUE TITLE
bug: Gnosis solvers not receiving /notify

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2514]
### Problem
For some reason, all notify requests to gnosis solvers are failing. Although not super problematic, for completeness, i believe we should fix this and eliminate errors.

### Impact
Low impact. Gnosis solvers are not reacting to notify calls.

### Screenshots/logs
https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/r/s/ELvUY

**Comment by fleupold** [comment]
The /notify endpoint is not implemented in the gnosis solvers repo.
