### ISSUE TITLE
chore: Add driver tests for CIP38 scoring

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2522]
### Background
Driver tests need to be added for CIP38 scoring. Test for all variants of protocol fee should be added:
1. Surplus
2. PriceImprovement
3. Volume

**Comment by fleupold** [comment]
I think this could be part of the test suite in https://github.com/cowprotocol/services/blob/b8c8ebef41cb73c1f20c44791c72120dba560cbc/crates/driver/src/tests/cases/protocol_fees.rs
