### ISSUE TITLE
chore: Rank by surplus tests

### ISSUE THREAD

**Issue by squadgazzz** [cowprotocol/services#2525]
Implemented rank by surplus should be covered with tests for all the policy fee types.

**Comment by squadgazzz** [comment]
In general, driver's integration tests could be used. But I think unit tests are still required to make sure both `native_surplus` and `native_protocol_fee` return correct results.

**Comment by fleupold** [comment]
I think we should just add an assert for each test case in https://github.com/cowprotocol/services/blob/b8c8ebef41cb73c1f20c44791c72120dba560cbc/crates/driver/src/tests/cases/protocol_fees.rs that ensure the final solution has the correct score.

**Comment by squadgazzz** [comment]
Duplicates #2522
