### ISSUE TITLE
bug: driver not sending liquidity data from uniswap-v3 and constant product pools anymore

### ISSUE THREAD

**Issue by tokenwood** [cowprotocol/services#2549]
### Problem
My solver in the shadow auction doesn't receive liquidity data from concentrated pools or constant product pools since this morning 10AM. 

### Impact
I am not sure whether this affects production or not, but it severely hinders solver's ability to find trade routes if they rely on the driver's liquidity data.

### Screenshots/logs

I tried to reproduce by running the driver locally. I get the following error for uniswap-v3: (this was working before)
`WARN init{source="uniswap-v3"}: shared::subgraph: failed to query subgraph: invalid GraphQL response`

For constant-product pools, I log each solve request the amount of pools, and the number of pools goes down progressively then hovers around 0 or a few:

> Liquidity:{'CONSTANT_PRODUCT': 936, 'STABLE': 11, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 602, 'STABLE': 11, 'WEIGHTED_PRODUCT': 133}
> [...]
> Liquidity:{'CONSTANT_PRODUCT': 275, 'STABLE': 11, 'WEIGHTED_PRODUCT': 124}
> Liquidity:{'CONSTANT_PRODUCT': 277, 'STABLE': 11, 'WEIGHTED_PRODUCT': 131}
> Liquidity:{'CONSTANT_PRODUCT': 281, 'STABLE': 11, 'WEIGHTED_PRODUCT': 131}
> Liquidity:{'CONSTANT_PRODUCT': 275, 'STABLE': 11, 'WEIGHTED_PRODUCT': 130}
> [...]
> Liquidity:{'CONSTANT_PRODUCT': 16, 'STABLE': 13, 'WEIGHTED_PRODUCT': 132}
> Liquidity:{'CONSTANT_PRODUCT': 15, 'STABLE': 13, 'WEIGHTED_PRODUCT': 132}
> Liquidity:{'CONSTANT_PRODUCT': 10, 'STABLE': 11, 'WEIGHTED_PRODUCT': 131}
> Liquidity:{'CONSTANT_PRODUCT': 2, 'STABLE': 11, 'WEIGHTED_PRODUCT': 131}
> Liquidity:{'STABLE': 11, 'WEIGHTED_PRODUCT': 134}
> Liquidity:{'STABLE': 11, 'WEIGHTED_PRODUCT': 134}
> Liquidity:{'STABLE': 10, 'WEIGHTED_PRODUCT': 134}

**Comment by fleupold** [comment]
Requires driving https://github.com/cowprotocol/services/pull/2381 home

**Comment by tokenwood** [comment]
If this is about the graph being down, why does balancer v2 liquidity work?
And it also doesn't explain the strange behavior on constant product pools. This morning it's hovering around ~5 pools per request instead of ~600. 

> Liquidity:{'CONSTANT_PRODUCT': 5, 'STABLE': 9, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 5, 'STABLE': 9, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 6, 'STABLE': 9, 'WEIGHTED_PRODUCT': 132}
> Liquidity:{'CONSTANT_PRODUCT': 6, 'STABLE': 9, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 6, 'STABLE': 10, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 6, 'STABLE': 10, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 6, 'STABLE': 10, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 5, 'STABLE': 9, 'WEIGHTED_PRODUCT': 133}
> Liquidity:{'CONSTANT_PRODUCT': 5, 'STABLE': 9, 'WEIGHTED_PRODUCT': 133}

**Comment by tokenwood** [comment]
FYI the constant product pools issue is gone, and the concentrated pools are back, but both the stable and weighted balancer liquidity pools are missing now

**Comment by MartinquaXD** [comment]
Thanks for reporting. We found the issue and deployed the fix to the shadow environment.

**Comment by tokenwood** [comment]
It all works now, thanks for fixing it!
