### ISSUE TITLE
feat: Implement cost coverage check in the driver

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2562]
Solvers have struggled a bit with pinpointing the exact gas costs of their solutions. With CIP-38, solvers need to improve their estimates so that they can collect sufficient network fees to cover gas.

One safety measure that the driver could implement is to discard a solution submitted by a solver if `fees_collected < simulated_gas_cost`.

This could be provided via a feature flag to solvers that want to opt in for such a test.

**Comment by fleupold** [comment]
If this was implemented, I would suggest reusing the `[gas](https://github.com/cowprotocol/services/blob/7bababdb2b9ce62a417f1e43a3c9713254e2937b/crates/solvers-dto/src/solution.rs#L27)` field on the `Solution` struct to indicate that your don't want your settlement to be included if it ends up using more than that amount (similar to a slippage tolerance but for gas). 

This value should then be used as gas limit to ensure a settlement doesn't use more gas than that.

**Comment by harisang** [comment]
> https://github.com/cowprotocol/services/blob/7bababdb2b9ce62a417f1e43a3c9713254e2937b/crates/solvers-dto/src/solution.rs#L27

Oh nice! That would be an elegant way to implement this.
