### ISSUE TITLE
feat: Include necessary data for simulations within the auction json sent to solvers

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2606]
Currently, solvers need to use the /auction endpoint to recover missing info, such as hooks, for orders in a batch auction in order to be able to simulate their proposed solution themselves. We could instead ensure that all necessary info is included in the auction json.

**Comment by MartinquaXD** [comment]
Data that is needed:
* all values signed as part of the order data (buy_amount, sell_amount, valid_to, etc.)
* pre- and post-hooks
* full sell and buy amounts (IIRC the driver currently reduces those amounts if an order has already been filled partially)
* signature
