### ISSUE TITLE
feat: [Solver/driver colocation] Make autopilot track for settlements and don't wait for driver to report back a hash

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2609]
Currently, the autopilot is waiting for the driver to report back the tx_hash of the settlement. In the colocated world, a driver might not report the hash right away, in which case, unnecessary delay might be caused. To fix this, the autopilot should be monitoring the blockchain and detect the tx hash itself.

**Comment by squadgazzz** [comment]
Fixed in https://github.com/cowprotocol/services/pull/2630
