### ISSUE TITLE
chore: document `validFor` in `/quote` request in swagger API

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2610]
### Background
The `/quote` endpoint not only supports setting a `validTo` but also `validFor`. This can be useful if you don't want to do math or actually set up your computers clock incorrectly.
However, this is currently not documented in the swagger API.

### Details
Related [code](https://github.com/cowprotocol/services/blob/main/crates/model/src/quote.rs#L163-L255)

### Acceptance criteria
Swagger documentation shows that you have to either set `validTo` or `validFor` and what these fields mean / what they do.

**Comment by fleupold** [comment]
Writing this issue might have taken almost as long as adding the documentation 🙈

**Comment by MartinquaXD** [comment]
Maybe as a small follow up on this. This flag was actually already documented but swagger renders the spec very weird.
This also happens with some other enum like types so I'm not sure we can do something about this.
