### ISSUE TITLE
bug: Solution merging produces a crazy number of settlements

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2617]
### Problem
It looks like sometimes the settlement merging logic results ins way more than 100 individual solutions.
When many of them fail to simulate the solver also gets spammed with `/notify` calls (which is actually how this got noticed).

context on [slack](https://cowservices.slack.com/archives/C0361CDD1FZ/p1713042974437819)
example in [kibana](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-13T20:09:00.000Z',to:'2024-04-13T20:09:30.000Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.app_kubernetes_io%2Fcomponent,negate:!t,params:(query:controller),type:phrase),query:(match_phrase:(kubernetes.labels.app_kubernetes_io%2Fcomponent:controller))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.network,negate:!f,params:(query:mainnet),type:phrase),query:(match_phrase:(kubernetes.labels.network:mainnet)))),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'log:%20%22notify%22'),sort:!(!('@timestamp',desc))))

Still unclear what is exactly happening (but wanted to open the issue already so we don't forget).
It might just be a combinatorial explosion. For example these [logs](https://production-6de61f.kb.eu-central-1.aws.cloud.es.io/app/discover#/?_g=(filters:!(),refreshInterval:(pause:!t,value:0),time:(from:'2024-04-13T20:16:01.225Z',to:'2024-04-13T20:16:03.953Z'))&_a=(columns:!(log),filters:!(('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.app_kubernetes_io%2Fcomponent,negate:!t,params:(query:controller),type:phrase),query:(match_phrase:(kubernetes.labels.app_kubernetes_io%2Fcomponent:controller))),('$state':(store:appState),meta:(alias:!n,disabled:!f,index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,key:kubernetes.labels.network,negate:!f,params:(query:mainnet),type:phrase),query:(match_phrase:(kubernetes.labels.network:mainnet)))),grid:(columns:('@timestamp':(width:164))),index:c0e240e0-d9b3-11ed-b0e6-e361adffce0b,interval:auto,query:(language:kuery,query:'log:%20%228740873%22%20and%20%22otex%22'),sort:!(!('@timestamp',desc)))) seem to indicate that 1 solver might have suggested to settle 6 orders across all its solutions. Assuming all of them are completely separate and can therefore be merged together we would end up with lots of merged solutions.

**Comment by harisang** [comment]
Ok thanks for clarifying. I was under the assumption that we were generating the same solution multiple times. If that is not the case, I agree that with 29 submissions, it is very clear that things will blow out of proportion.

Maybe we should put a cut-off threshold X, and the driver only processes the first X solutions

**Comment by ahhda** [comment]
@fleupold this caused a crashloop on the sepolia driver recently. Should we consider reopening this issue?

**Comment by fleupold** [comment]
Sure I can look into this as part of oncall this week.
