### ISSUE TITLE
feat: Store auction instances including liquidity

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#2633]
### Problem
Since switching solvers to the new auction format, auction instances from the driver (including liquidity) are not stored anymore. Since those instances have been used for EBBO testing, some EBBO checks are currently not working.

Since we want to move forward with formalizing EBBO, having auctions instances is required to get a better overview of the magnitude of EBBO violations.

### Suggested solution
Store auction instances from one of the solvers which receives liquidity, similarly to how it was done for the legacy format. Auction instances from the autopilot are not enought since they do not contain liquidity.

**Comment by fleupold** [comment]
Here is a pointer to the code where this was done in the legacy solver implementation: https://github.com/cowprotocol/services/blob/dd2fe4b6e549d63d0463bd89a1395829af5843d4/crates/solvers/src/infra/persistence.rs#L7

The `s3::Uploader` is already a shared crate and should be reusable in the driver. We should allow a per solver configuration to upload (different solvers could use different `paths` on the bucket) but in practice only enable uploading for Quasimodo.
