### ISSUE TITLE
feat: Track participation for quote requests

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2665]
Similar to how we track participation in the solver competition, it would be nice to start tracking how many valid responses we get for each quote request, so that we can see how robust the quote competition is.

Since we are frequently getting spammed with random requests, some restrictions could be put in place for such a metric; e.g., specific token pairs and specific range of sell amounts.

**Comment by fleupold** [comment]
Is it necessary to store all quotes (with buy/sell amounts) or are you mainly interested in the number of quotes that was valid (independent of quality)? How long should this information be available?

**Comment by harisang** [comment]
We could start with just number of valid responses. And it could be just for the last few hours, maybe simply a histogram, that gives an idea how strong the quote competition is.
