### ISSUE TITLE
About endpoint

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#27]
It would be nice to have an about endpoint exposed by the service

Some idea of the info that could be exposed:
* **Name**: `Gnosis Protocol API`
* **Versions**: 
    * **api**: version of the API 
    * **smartContracts**: version of the smart contract

Some nice to have is the commit hash of the API. 

> Original issue https://github.com/gnosis/gp-v2-services/issues/132 by @anxolin

**Comment by anxolin** [comment]
Cool! If you end up doing this one, we can expose this info in the fronend if it adds any value.
