### ISSUE TITLE
feat: Native fee calculation 

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2706]
### Problem
https://github.com/cowprotocol/services/pull/2701#discussion_r1593512659

Should we skip converting the total fee to sell token before converting it into native token? 

This might introduce difference in the final result, since we use different external prices to convert into native token. 

Solver team might also have some comments on this cc @harisang  @fhenneke

**Comment by fhenneke** [comment]
Are you referring to the fee solvers set to cover execution costs?
Then we would have to coordinate with solvers as they would have the change their algorithms.
In the (hopefully somewhat) near future we might change the accounting to never use the fee computed by the autopilot: protocol fees are not computed there anyways[0] and the network fee would just count towards slippage. Then it does not matter how it is computed. It would just be a way of communicating the directional price of orders to the driver.

[0]: It would be great if they were, though. E.g. as additional entry in the fee_policies table or a new table. Having code for protocol fees in the autopilot to check scores and populate protocol fees for consumption in our accounting would really help.
