### ISSUE TITLE
feat: Reject solution with violated solution quality

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2713]
### Problem
Inspired by https://github.com/cowprotocol/services/pull/2712, we should also check if the reported winning score (part of the `/solve` response) is equal to score calculated from winning calldata (part of the `/reveal` response).

This is to make sure that solvers are not reporting one score for competition and then intending to settle other score. This is a direct violation of competition rules and solver should not be allowed to settle.

The same checks should be added for reported trades and clearing prices.

### Suggested solution
Implement check at the competition time and reuse decoded settlement from https://github.com/cowprotocol/services/pull/2712.

### Alternatives considered
The check could be implemented in the postprocessing as well, but early rejection during competition makes more sense to me, as it can catch bugs with driver score calculation early and avoid circuit breaking a solver because of score violation.

### Acceptance criteria
If scores are different, solution should be rejected.
If orders are different, solution should be rejected.
If clearing prices are different, solution should be rejected.

**Comment by fleupold** [comment]
nit: I think larger score should still be allowed (as long as each order was filled at least as good as promised).

**Comment by sunce86** [comment]
With the new [plan](https://github.com/cowprotocol/services/issues/2716), where we want to completely remove `/reveal` endpoint and `score` field from `/solve` response, this issue makes no sense anymore.

However, since `/reveal` might not be removed just yet (since solver team still uses uninternalized call data), will keep this issue around as we still might want to make sure `/reveal` response is of same quality as `/solve` response.
