### ISSUE TITLE
feat: Balances of CoW AMMs in batch auction json

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#2715]
A solver team asked whether it would be possible to include up-to-date balances of (some curated list of) CoW AMMs in the auctions the autopilot sends out. Would that be easy to do, or should we leave it up to the solvers to do that?

**Comment by fleupold** [comment]
It would be easy but prone to race conditions and I don't think we should put it in the autopilot. If at all it could be considered part of the liquidity fetching in the driver, but I'm not sure we want to invest ressources for that (solver teams are welcome to contribute a PR)

**Comment by marcovc** [comment]
Question: if the driver is not providing the cow amms, I suppose it is also not providing the external prices for those cow amms. If that is the case, how is the surplus for cow orders computed?

**Comment by fleupold** [comment]
@harisang correct me if I'm wrong, but I think plan is to provide a list of contract addresses that represent CoW AMMs and make sure that there are external prices for their assets in the auction.

**Comment by marcovc** [comment]
You mean this list of addresses is going to be part of the instance json, or is it somehow implicit what the list is, and the driver will make sure its traded tokens are listed there?

**Comment by fleupold** [comment]
cc @Mateo-mro since you worked on this. How do solvers know which addresses are allowed to have surplus capturing JIT created by them?

**Comment by marcovc** [comment]
Great, thank you!
