### ISSUE TITLE
Add autopilot configuration to define observable solver addresses

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2722]
Context provided https://github.com/cowprotocol/services/issues/2667

> Since the barn and production environment operate on separate auction but share the same settlement contract instance, we probably cannot simply audit all settlement events that are emitted and ban if a settlement is emitted "out of competition". If we did, the prod autopilot would have to check the barn autopilot if a settlement satisfied its competition and vice versa. Moreover, there are some legit out of competition settlements (e.g. for periodic fee withdrawals). I'd suggest configuring each driver with a set of allow-listed solver addresses it tracks settlements for (and ignores all other settlements).

This issue captures adding the configuration parameter where for each environment autopilot is given a list of solver addresses the settlement update needs to monitor. Once we have this list of addresses, OnSettlementEvenUpdater needs to be updated to skip checking all other senders.

**Comment by MartinquaXD** [comment]
> OnSettlementEvenUpdater needs to be updated to skip checking all other senders

One thing to note is that we can run into issues when we have to re-index solutions of solvers that have been deprecated since the transaction happened. I think this is a very minor edge case but IMO we still need to be aware that it exists.
