### ISSUE TITLE
chore: CurrentBlockStream with websockets

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2740]
### Background
It looks like sometimes new blocks appear on arbitrum outside of the regular block interval. To not miss those blocks we might have to make the `CurrentBlockStream` use websockets and let it subscribe to new blocks.
The CurrentBlockStream is the heartbeat of the backend and many tasks are synchronized to it. If this is not reliable enough we could completely miss on-chain events that need to be indexed leaving the DB in an inconsistent state.

### Details
Unfortunately there are a few caveats:
1. AFAIK no web3 library currently implements automatic reconnects on websockets so we'd have to do it ourselves :/
2. AFAIK you can only subscribe to incoming block headers but not fully processed blocks. There have been issues in the past where we saw a new block header and tried to fetch the block immediately but it wasn't there. The implementation probably needs to be resilient to that node client implementation quirk.

### Acceptance criteria
CurrentBlockStream can also be ran with websockets (second mode) without having to specify a poll interval.

**Comment by fleupold** [comment]
>If this is not reliable enough we could completely miss on-chain events that need to be indexed leaving the DB in an inconsistent state.

Can you provide a concrete example of how this could happen? In my mind the worst thing would be we learn about the new block 1s later and run the reindexing with a slight delay, but I don't see how we can get into inconsistent state.

**Comment by MartinquaXD** [comment]
> Can you provide a concrete example of how this could happen? In my mind the worst thing would be we learn about the new block 1s later and run the reindexing with a slight delay, but I don't see how we can get into inconsistent state.

After opening this issue I looked more into the event indexing logic and it actually does not need to see every new block (indexes from where it left of to the new block). So this the current block stream missing blocks is indeed not an issue.
