### ISSUE TITLE
feat: Create database table `auction_orders`

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#2745]
### Problem
Related to https://github.com/cowprotocol/services/pull/2688#discussion_r1592236055

This table is supposed to be used as part of the reconstruction of all the auction and competition data to be at disposal to `OnSettlementEventUpdater` and `CircuitBreaker` as suggested in https://github.com/cowprotocol/services/pull/2734#discussion_r1603049428

We shouldn't rely on SolverCompetition table but rather extract data that we need into separate tables.

**Comment by fleupold** [comment]
This only needs to be a mapping of <auction_id, order_uid> or is there anything else?

**Comment by sunce86** [comment]
I think that's it for this task. We probably need a separate table to save competition solutions (see https://github.com/cowprotocol/services/pull/2734/files#diff-2aa96c62abd5673078cf88346c59920ddf3563f6e6b2a8644dd3871c6431576dR258-R260)
