### ISSUE TITLE
chore: Index native prices of tokens traded by CoW AMMs

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2755]
### Background
To incentivize solvers to rebalance CoW AMM pools these rebalancing orders need to count towards surplus of the solution to improve its score and therefore increase the likelihood of winning the competition.
In order to compute the surplus a CoW AMM order generates denominated in ETH we need to have a native price for the surplus token in the auction. At the moment the watch tower still indexes "template orders" for each known CoW AMM which we automatically try to fetch the native prices for.
Eventually we would like to stop indexing these template orders and instead only rely on solvers suggesting trades on their own as JIT orders. For this to happen we need to ensure that we have all the required native prices as part of the auction.

### Acceptance criteria
We automatically keep track of all the deployed CoW AMMs and their traded tokens. We keep the native prices of these tokens up to date and add them to the auction.
Whenever a solver wants to rebalance a CoW AMM it's their responsibility to check the native prices contained in the auction to determine for which CoW AMM it would be advantageous to rebalance (in order to improve their solution).

**Comment by Mateo-mro** [comment]
Done in https://github.com/cowprotocol/services/pull/2790
