### ISSUE TITLE
chore: Automatically index CoW AMMs

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2774]
### Background
Currently we have to maintain a list of existing CoW AMMs. This is error prone and also just annoying.
Instead we should add have a single `CLI` argument to pass the CoW AMM factory contract and "listen" for [Deployed](https://github.com/cowprotocol/cow-amm/blob/main/src/ConstantProductFactory.sol#L39) events.
That way we automatically know about any new pool that gets deployed.

As the first step I would simply refetch all such events since contract deployment on every restart (to get the ball rolling). If this takes too much time we can consider persisting these events in our DB like we do with other events.
For related code check the `EventHandler` and `EventUpdater`.

**Comment by MartinquaXD** [comment]
Pre-requisite for https://github.com/cowprotocol/services/issues/2774

**Comment by fleupold** [comment]
I wouldn't suggest doing that for the soon legacy CoW AMM pools (that are created via the factory) but instead focus on the Balancer created CoW AMM. At least the code should allow to easily add new types of creating CoW AMMs that get indexed.

**Comment by MartinquaXD** [comment]
Absolutely. But overall I don't expect the infra to be built to change in any meaningful way when we have to switch over to balancer developed cow amms. This issue is intended to make us ready from day one to include these pools instead of scrambling to add support after they get launched officially and until then we might as well index the current version of cow amms.
