### ISSUE TITLE
[explorer] API for stats in Home page

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#28]
Hi!

I'm starting to make some spec documents to break down some of the features for the Explorer. 
I started describing the home page of the Explorer, where we want to include some basic stats and a top traded tokens ranking.

* Specs home page: https://docs.google.com/document/d/1m1h_0v5uLAqwOoDPZj5_ib8JmjzRcPWOY08pyqGhvjA/edit#
* Overview of Explorer App: https://docs.google.com/presentation/d/1a6H06zN4m6eMFpMR4eV2gAtJxW8LB0bb/edit#slide=id.p1

![image](https://user-images.githubusercontent.com/2352112/106632287-df80a700-657d-11eb-9f11-09cd3c256b84.png)

In the document, you'll find some early draft on the APIs that would allow to build that. 
I'd love to get your input and ideas on what's best to show in this first home page.

DISCLAIMER: Note that although the image posted here looks pretty good, the design is still ongoing. I would find extremely value to discuss this functionally, so we discuss what is a good information to users in the home page, and also in terms of API design, so we can agree on the REST endpoint name, parameters, and return data. Design feedback is welcome, although not part of this issue.

> Original issue https://github.com/gnosis/gp-v2-services/issues/265 by @anxolin

**Comment by anxolin** [comment]
we are doing this using the graph. No relevant any more
