### ISSUE TITLE
bug: Surplus of CoW AMM orders in settlement_scores table is zero

### ISSUE THREAD

**Issue by fhenneke** [cowprotocol/services#2808]
### Problem
The surplus of JIT orders is not accounted for correctly in the autopilot when populating the `settlement_scores` table. The problem is present in prod and staging. Scores from the driver, however, are correct.

### Impact
This error impacts reward computations as the reward script uses `surplus` from the `settlement_scores` table. This lead to small discrepancies in payments mostly to Quasilabs which were corrected manually. Other solvers are also affected, but the overall damage is small as of now.

Wrong data is currently uploaded to Dune.

### To reproduce
This is easiest to see in examples of settling only one order in a batch as for [this settlement](https://etherscan.io/tx/0x9576afc86073c3aae89628072b521c37e748aa36afcf8ca1ac4e004ffea22769) (staging, auction id 10859238, block number 20261350)
The query `select * from settlement_observations where block_number = 20261350` gives a surplus of `0`, while the query `select * from settlement_scores where auction_id = 10859238` gives a winning score of `57387933137402` which equals the surplus of that order since there are no protocol fees. The score (and surplus) are double checked using the circuit breaker which contains an independent implementation of  scores (and surplus).

The problem is less obvious for other settlement (e.g. [this settlement](https://etherscan.io/tx/0x1f596aad7aaf4eac5deded7c5a398983fe02d154a0ec09368a7edc8497add164), auction id: 20272499, block number: 9116222), but the same arguments apply: surplus is stored as `46523400998314531` but the score suggests a surplus of `46624022071370740` which is larger by the surplus of the CoW AMM order.

### Alternative solutions
I think that the rewards script could get by with just using the winning score directly instead of recomputing it from surplus and protocol fees. The correctness of the scores themselves is checked by the circuit breaker (with the next release).
We do upload surplus to Dune and for that it would be convenient to have a correct surplus computation in the autopilot. This is almost required since surplus for JIT orders cannot be directly computed from the database except by parsing the stored calldata.

cc @harisang

**Comment by fleupold** [comment]
cc @Mateo-mro is this on your radar (as far as I know you are finishing up CoW AMM integration work)?

**Comment by Mateo-mro** [comment]
> cc @Mateo-mro is this on your radar (as far as I know you are finishing up CoW AMM integration work)?

@MartinquaXD and I worked on the CoW AMM. I can definitely take a look into this, I am doing some CoW AMM related tasks so I can add it to the pile. The only thing is I can only start working full on it from next week, is that is ok @fhenneke .

**Comment by fleupold** [comment]
Also cc @sunce86

**Comment by sunce86** [comment]
Since cow amm orders are no longer part of the autopilot `Auction`, the code assumes decoded cow amm orders are not eligible for surplus: https://github.com/cowprotocol/services/blob/main/crates/autopilot/src/on_settlement_event_updater.rs#L215

To fix this, we need https://github.com/cowprotocol/services/issues/2793 implemented, so that we have a mechanism how to differentiate between cow amm orders and jit liquidity orders in the autopilot.
