### ISSUE TITLE
feat: executed surplus fee for individual fills in partial orders

### ISSUE THREAD

**Issue by pata-eth** [cowprotocol/services#2811]
### Problem
As a solver, I need to easily calculate the cashflows in a settlement. currently, the executed fee for partial fills is not included in the api. The /orders endpoint does report the cumulative fees for an order:

https://api.cow.fi/arbitrum_one/api/v1/orders/0xd727cd2346ddec6ef6f9e392cf880cadd4c2ab8842dcd1bd1ba5da28276f24295c14b77037efda27f3676655e97957e1f29fe255677cc009

And the /trades endpoint, where I'd suggest to report the fee for each fill , there's not enough info to calculated it.

https://api.cow.fi/arbitrum_one/api/v1/trades?orderUid=0xd727cd2346ddec6ef6f9e392cf880cadd4c2ab8842dcd1bd1ba5da28276f24295c14b77037efda27f3676655e97957e1f29fe255677cc009

### Alternatives considered
@harisang suggested to compute it from the info provided in the competition endpoint, but I have not been able to get close to the actual value. At any rate, even if this could be done accurately, I don't see a reason why this info would not be posted in the api.

**Comment by fleupold** [comment]
@squadgazzz did your changes last week address this issue? If so can you close it or otherwise specify what's left to be done?
