### ISSUE TITLE
chore: Attach quoting solver to the order

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2813]
### Background
I have seen for a bunch of "slow to solve" orders that they were quoted by a Gnosis solvers (e.g. 1Inch) which later on didn't attempt to settle them thus making them expire or take a long time to settle.

### Details
Single order solvers sort orders in the auction instance by "likelihood" of being executed based on the external price vector that is part of the auction file. They then try to settle as many orders as possible based off that list until time runs out or the upstream API starts rate limiting them

It is a known fact that the external price vector tends to be inaccurate. Yet the orderbook is quite large, which may lead to bad prioritisation.

In particular, if a solver just quoted an order a couple of seconds earlier it should prioritise re-solving for that oder as it's likely going to be solvable given the same route that was obtained in the quote.

### Acceptance criteria
- Attach information about the winning quoter on each order
- Inside the single order solver, keep sorting orders by likelihood but also put orders that were quoted in the last couple of minutes by the current solver ahead of the queue, as they are likely going to execute.

**Comment by fleupold** [comment]
https://explorer.cow.fi/orders/0xd916d75dbe461f52e5a757c3d343030fc08b40e2ad71347baeef28a0b1c5d3f2a4c39bc895e380e0b54f9b1c952c3bc151cf6fb266a0c77e?tab=overview is an example for which 1Inch quoted a route that was executable for the entire time of the order (7 minutes). 

In the first auction that the order was valid ([9177561](https://api.cow.fi/mainnet/api/v1/solver_competition/9177561)) no solutions were proposed so it could have easily been settled. The 1Inch solver never tried to match this order.

**Comment by squadgazzz** [comment]
> that were quoted in the last couple of minutes

Just to make sure I didn't miss anything. This requirement implies adding a creation timestamp column to the `quotes` table, and the same timestamp should be reflected in the `order_quotes` table(to avoid adding `quote_id` and SQL joins), correct?

**Comment by fleupold** [comment]
No, I think we should use the order creation timestamp to decide on recency (quotes are only valid for a very short time anyways).
