### ISSUE TITLE
chore: Experiment with different order prioritisation schemes in the driver

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#2832]
### Background
We currently "prioritise" the order of orders in the auction sorted by "likelihood" of being matchable according to the external price vector. It's very much possible that this is not optimal (cf. #2813 for an example)

### Details
We could envision different strategies of sorting (time based, orders that were quoted by the current solver first, etc) and should implement one or two of those to see if time to happy moo improves significantly.

### Acceptance criteria
Different per-driver configurable prioritisation strategies:
1. By price (status quo)
2. By time
3. Interlaced (alternating price and time sorting)

Related to #2813

**Comment by MartinquaXD** [comment]
Closed by the `stale issue` bot but this was actually implemented.
