### ISSUE TITLE
[explorer] Top traded tokens API

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#29]
![image](https://user-images.githubusercontent.com/2352112/106738840-bb25d880-6618-11eb-855d-f9b1149e5626.png)

One very important page in the block explorer will be the "Top traded tokens". Actually, our idea is to include them in the home page.

It will show the volumes and prices for the most traded tokens. It will allow the user to quickly understand what they can do in Gnosis Protocol, and get an idea of the expected volumes and prices for the active tokens.

Details about this page can be found in the spec: https://docs.google.com/document/d/1at2Vb8iZMxAKxUkBMR_HaMn6UjYhTD7dE9mxy_xaJP0/edit#

## API
In this issue I would like to discuss a suitable API for supporting thing use case. In the spec document there's already a detailed proposal which we could use for iterating and shaping the API.

> Original issue https://github.com/gnosis/gp-v2-services/issues/267 by @anxolin

**Comment by anxolin** [comment]
@nlordell closing this one since it will be done using the graph
