### ISSUE TITLE
chore: Precheck token quality before it gets evicted from the cache

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#2929]
### Background
We already have a background task for the bad token test that updates expired tokens which improved the performance somewhat.
However, it still does not re-check and update the cache slightly **before** the items expire (similar to native token cache). This should resolve the last few problematic outliers in terms of runtime.

**Comment by fleupold** [comment]
Likely similar logic is applied for the native price estimator [here](https://github.com/cowprotocol/services/blob/4f0f946264e27c0c3e94b5b4698d99d95e381774/crates/shared/src/price_estimation/native_price_cache.rs#L191) (under the concept "prefetch")

**Comment by m-lord-renkse** [comment]
Implemented in: https://github.com/cowprotocol/services/pull/2936
