### ISSUE TITLE
chore: Extend `/quote` response with pre-interactions and Jit orders

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#3027]
### Background
Currently CoW Protocol is in an awkward spot because it can not be the only source of liquidity yet. If all liquidity for a token rests in CoW Protocol's orderbook or some CoW AMM solvers would have no way of using it to quote a price for a given token.

### Details
To fix that we should allow solvers to return pre-interactions and JIT orders with their quote. That way solvers could quote with CoW AMMs (require JIT orders and pre-interactions). They could also index the orderbook and return resting limit orders as JIT orders.

### Acceptance criteria
* update `driver -> autopilot` `/quote` reponse to pass a list of `pre-interactions` and a list of `JIT` orders (format of jit orders should ideally be the same as in the `/solve` endpoint)
* updated the openapi spec

**Comment by squadgazzz** [comment]
Closed in favor of https://github.com/cowprotocol/services/issues/3082
