### ISSUE TITLE
chore: Extend quote verification for quoting with limit orders

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#3028]
### Background
https://github.com/cowprotocol/services/issues/3027 updates the `/quote` response to return enough data to quote with resting limit orders or JIT orders.
The next step is to use the new data in the quote verification logic to check that whatever the solver proposes would actually work onchain.

### Details
This requires the `ExternalTradeFinder` to parse the new data (`pre-interactions`, `JIT orders`) from the JSON response and pass it to the simulation logic via the `Trade` struct. `trade_verifier::encode_settlement()` would also have to encode the new interactions and orders. AFAIK the underlying simulation logic would not have to be adjusted since it's using the actual settlement contract under the hood so it should automatically do the right thing with the new interactions and orders.

### Acceptance criteria
e2e test verifying that a cow amm can be used to provide a quote.
This requires:
* setting up the cow amm
* using the mock solver to return a hardcoded solution with it (example [here](https://github.com/cowprotocol/services/blob/main/crates/e2e/tests/e2e/cow_amm.rs#L301-L337))
* producing the required native prices somehow. With https://github.com/cowprotocol/services/pull/3009 the easiest way is probably to store the necessary `auction_prices` in the DB before starting the `autopilot`
* assert that the generate quote has `verified: true`

**Comment by squadgazzz** [comment]
Will be implemented in https://github.com/cowprotocol/services/issues/3082
