### ISSUE TITLE
Setup easy way to store large amount of data outside of logs

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#334]
For example in https://github.com/cowprotocol/services/pull/325 there is some data we would like to access later and logging is the easiest way to implement this. But logging is not the best tool for this because we aren't interested in reading this text live and it puts more pressure on Kibana etc.

It would be better if we had some sort of network storage that we could upload files to. This would be one way. We don't need to interact with anything afterwards (no edit, delete, read). This should be easy to setup with an FTP server, or simple service we host that accepts files to put on disk through some POST route.

Traditionally we have used S3 for this. Marco felt it didn't work well for this job. I feel cloud services like this might be overkill because we don't need all the extra guarantees they give us. I would be fine with a self hosted ftp server somewhere. On the other hand since our other infrastructure is "cloudy" it can make sense to keep using it.

**Comment by nlordell** [comment]
We can just host some FTP pod with a mounted volume and periodic cleaning that we expose with `kubectl port-forward`.

I think we should be able to do this without involving DevOps as well.

**Comment by josojo** [comment]
I would prefer if this data is stored in a real database, such that we can efficiently run queries on it. From a data-analytics point of view, it would be a hassle to download single files and parse them, just to receive the prices that we need for price calculation. It would be more convenient to just download the "right" SQL rows fetched via a custom query.

cc: @bh2smith

**Comment by vkgnosis** [comment]
That doesn't make sense to me with regards to the example I mentioned at the start of the post.

**Comment by vkgnosis** [comment]
Using S3 is a good enough solution.
