### ISSUE TITLE
Database smaller details

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#34]
While reviewing #313, since it was the first PR I review of the database structure, I notice a few things that I wanted to mention. But they were unrelated to the PR, so I breing my comment https://github.com/gnosis/gp-v2-services/pull/313#pullrequestreview-590742597 here. 

* there's a few indexes missing: like sell token
* The FKs are missing, like from trade to its order
* Ideally we would save already the denormalized short id
* I would consider adding a FK in the trades to the settlement, I would make sure there is a tx hash (that would be important for us in the FE), and I would consider to move those "block_number". Maybe you want to even use this FK+log_index as the PK.

I wouldn't do this one, until we see we have performance issues, but, one thought I had is, If we expect issues with having many orders, you can set a flag for the orders that are final:

- expired
- canceled
- fully executed
For these order you know u'll never need them again (for the ones considered by the solver).
If we have too many orders, an index in this field would basically allow us to quickly filter out most of the orders. As I said, this one, better to wait for the real need

> Original issue https://github.com/gnosis/gp-v2-services/issues/319 by @anxolin

**Comment by anxolin** [comment]
This issue is super old, i guess the model changed a lot. I will close, unless someone find it still relevant
