### ISSUE TITLE
Unique order IDs on auction data forwarded by driver to the solvers

### ISSUE THREAD

**Issue by felixjff** [cowprotocol/services#346]
Order IDs in auction instances are not unique. The same order is given different order IDs across multiple auctions. In some cases it would be useful for solvers to have access to the unique ID from an order. Hereby, two practical use cases:

1. Currently, as a solver I may be storing the solutions I generated on my own database. If I do not have a unique order ID, then I will need to generate one myself. Unique order IDs will help me easily query the solutions I generated for a specific order. The main issue arises when I would like to compare my solution with the winning clearing prices for the order. Say the order was settled within a specific auction, then without an order ID I would need to match buy_token, sell_token, buy_amount, sell_amount, etc and hope the match is realiable and uniqe. Having a unique order ID would make this easier and safe. 

2. As a solver I may want to track order across auctions. In the past we have seen orders that were troublesom. Having a unique ID would help us manage how orders are taken into account across auctions. Say if we find a solution to the order, but it is not settled across different auctions, then we might decide to flag it and potentially ignore it the next auction.

**Comment by nlordell** [comment]
I think this issue is specific to the `instance.json` model we give to HTTP solvers, where the order "IDs" are just indices assigned at random (and not related to the order UID).

**Comment by felixjff** [comment]
@MartinquaXD the example I have in mind was an order mentioned in this issue:

https://github.com/cowprotocol/services/issues/243

The order was being assigned a solution, but settlements would not go through. This would lead to failed settlements for any solver that would include the order in the solution. The unique ID would be an easy way for solvers to gather stats about orders and ignore them if they consider something is not right. As solvers we can also create some  "unique ID" ourselves (with some combination of str(auction_id) + str(buy_token) + str(sell_token) + str(sell_amount) + ...) but I thought the best woud be to get the unique ID from COW. Since the auction IDs are non-unique, we would not get 100% certainty that our unique IDs are truely unique.  

@nlordell thats correct. We only receive random indices as order IDs.

**Comment by fleupold** [comment]
Just to clarify, the concrete ask here is to use the order uid as the key in the `instance.json` order dict rather than indices that don't persist between auctions, right?

**Comment by felixjff** [comment]
@fleupold correct.

**Comment by tbosman** [comment]
Just thought of another reason to have this in the solutions file: right now batches consisting of non-mature orders are not valid. If we knew which orders are immature it would be helpful, also for the purpose of getting eg signed orders.

**Comment by felixjff** [comment]
Agree with @tbosman. With the solvers getting more complex, it is good to know which orders are mature. This will also help reduce the number of orders we need to solve for in a given auction and potentially allow for deeper liquidity search for mature orders (without risking timeout).

**Comment by fleupold** [comment]
Another potential solver team asked today on telegram if it would be possible to use more descriptive identifiers (in particular for the AMMs) as keys in the dictionary.

**Comment by sunce86** [comment]
Implemented https://github.com/cowprotocol/services/pull/721
