### ISSUE TITLE
Add `gasAmount` to quote response

### ISSUE THREAD

**Issue by adamazad** [cowprotocol/services#370]
Hi @fleupold, 

I would like to sugggest to break down the `feeAmount` further:

- `feeAmount`: protocol or LP fee of the trade.
- `gasAmount`: the network gas amount.

And in order to get the full fee amount: those above numbers can be summed. This will help CoW's implementation on Swapr. In the Eco Router, we sort trades using `executionPrice` which is the `outputAmount` WITHOUT gas fees. However, the `outputAmount` from CoW's quote includes gas fees too. 

<img width="505" alt="image" src="https://user-images.githubusercontent.com/1926216/179480522-75c2f56d-1ff1-43b4-897e-44dc798481f0.png">

**Comment by fleupold** [comment]
Hi @adamazad, thanks for creating the issue. The thing is that `gasAmount` on CowSwap will always be 0. Users place orders off-chain (no charge) and then "the fee" (which is roughly equivalent to the gas costs on other venues) is taken from the user in the sell token.
