### ISSUE TITLE
Allow HTTP solvers to specify native CoW liquidity orders in result.json

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#372]
In order for external solvers to implement private liquidity in a gas efficient, yet trustless way it is likely best if we allow them to create and sign native CoW orders while they compute the solution and return those in the `result.json`. 

In order to not skew the competition, those "private" orders should not contribute to surplus and should therefore be treated as liquidity orders for the objective value (ie. matched at limit price). They don't need to include a fee.

Some more context on alternative options for adding private liquidity and why this is likely the best tradeoff can be found here: https://forum.cow.fi/t/implementing-a-solver-using-private-liquidity/

**Comment by felixjff** [comment]
As a solver-market-maker, I will most probably have to quote well above the limit price of an order to actually win an auction. Specially, if quotes from other solvers (e.g. 1inch or 0x) do contribute to surplus on the objective value function. How is an RFQ to a market maker during the auction timespan different to an RFQ to 0x or 1inch? Why would those quotes be allowed to contribute towards surplus and those of a private market maker not? In some cases 1inch and 0x also embed quotes from MMs on their solutions.

**Comment by fleupold** [comment]
> Why would those quotes be allowed to contribute towards surplus and those of a private market maker not?

Sorry, my communication must have been unclear. The user order you are matching is of course accruing surplus just like in the case when it's settled against 1Inch liquidity. What doesn't accrue surplus is the order you place in your name to match that user order. That PMM order has to be matched at its limit price (just like we match AMMs at their limit price). This is to ensure that orders which can accrue surplus are visible to all solvers.

Here is an example of what is obviously not allowed:
- User sells 1 ETH for limit 1000 USDC
- PMM buys 1 ETH for limit 1300 USDC (this order wasn't part of the instance.json)

Clearing price 1200 USDC and you claiming a total surplus of 300$

**Comment by fleupold** [comment]
> Why would those quotes be allowed to contribute towards surplus and those of a private market maker not?

Sorry, my communication must have been unclear. The user order you are matching is of course accruing surplus just like in the case when it's settled against 1Inch liquidity. What doesn't accrue surplus is the order you place in your name to match that user order. That PMM order has to be matched at its limit price (just like we match AMMs at their limit price). This is to ensure that orders which can accrue surplus are visible to all solvers.

Here is an example of what is obviously not allowed:
- User sells 1 ETH for limit 1000 USDC
- PMM buys 1 ETH for limit 1300 USDC (this order wasn't part of the instance.json)

Clearing price 1200 USDC and you claiming a total surplus of 300$

**Comment by fleupold** [comment]
@nlordell this has been implemented right?

**Comment by nlordell** [comment]
Implemented in #422
