### ISSUE TITLE
Add a prometheus counter for the number of RPC calls

### ISSUE THREAD

**Issue by ahhda** [cowprotocol/services#389]
As we move our infrastructure away from Gnosis, we would like to start hosting our own nodes soon.

A bunch of partners offer RPC node endpoints, and we might use them as a fallback.

We make two types of RPC calls: batch calls and non-batch calls. We would like to keep a track of the total number of RPC calls that we make. So if there are 3 RPC calls within a batch call, that should count as 3 RPC calls.

Currently, we keep a track of batch and non-batch calls but do not count the sub calls within a batch call.

Note from Felix:

> Maybe we can add a Prometheus counter in the RPC abstraction? Might be good to keep track of this metric anyways if we start paying per request

**Comment by fleupold** [comment]
> A bunch of partners offer RPC node endpoints, and we might use them as a fallback.

I'd even considering using some partner as a primary node provider (assuming they have good SLA guarantees) and use Gnosis as a fallback. Judging from Gnosis DevOps, it seems very challenging to run your own node infrastructure.

**Comment by sunce86** [comment]
> I'd even considering using some partner as a primary node provider (assuming they have good SLA guarantees) and use Gnosis as a fallback. Judging from Gnosis DevOps, it seems very challenging to run your own node infrastructure.

Relying on partners would move us away from the idea of having customized nodes implementation (node + our own project specific extensions), that eventually will be needed, right?

**Comment by fleupold** [comment]
@sunce86 can you give an example of a "project specific extension" you are envisioning?
