### ISSUE TITLE
Make it easier run autopilot, driver, orderbook main functions from other code

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#400]
Currently we directly create and use some components in the e2e tests. It might be better to expose "the main function" with enough granularity that we can test it on the whole rather than the individual components. 

This would also help if we want to make a single "local test" binary in the future that internally runs all of the components.

In the autopilot we have some code going into this direction by exposing a "main" function in `lib.rs` however this does not give enough control as for example the e2e tests need to pass in custom contract addresses.

This change is not urgent. I'm creating this issue to be reminded of it in the future.

**Comment by nlordell** [comment]
We can also use docker-compose or something equivalent to accomplish a similar thing.
