### ISSUE TITLE
Gelato Submission Strategy

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#407]
Gelato provides a service for executing transactions on-chain with a good "target submission time" of 30-90 seconds. Additionally, you don't pay for failed transactions (so their incentives of only executing transactions that don't revert) aligns with our requirements as well.

We should try and integrate with them by having a submission strategy that uses Gelato instead of manually submitting transactions ourselves.

**Comment by MartinquaXD** [comment]
Can this be closed?
