### ISSUE TITLE
Split out some modules from the shared crate

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#408]
I mentioned this in some of the autopilot discussions already but wanted an issue to remember.

Originally we had two binaries, the orderbook and driver. At that time it made sense to have one shared crate for functionality needed by both. Now we have several more binaries and shared has become bloated with modules needed only by a subset. This forces binaries to include dependencies they don't need because they need to depend on shared all-or-nothing.

We should refactor out some modules where it makes sense. This improves code separation and compile times.

On the other hand if we go too fine grained it could be annoying too, to effectively have one crate per module so we could also have a orderbook-autopilot-shared crate. I'm not sure about this yet.

**Comment by sunce86** [comment]
https://github.com/cowprotocol/services/issues/395 is closely related to this issue. https://github.com/cowprotocol/services/issues/395 is extracting all liquidity sources and also, lets say, 50% of the shared crate also goes with the liquidity sources. Therefore, I would pause this task until https://github.com/cowprotocol/services/issues/395 is done.
