### ISSUE TITLE
Account for Fees in EIP-1271 Orders

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#420]
EIP-1271 is very much implementation specific. This means it is possible for there to be huge variance in the amount of gas required to verify signatures (i.e. different wallets require different amount of gas for verifying signatures **and** gas at order placement != gas at auction time).

In order to account for this we should start adding an additional gas amount (on top of `shared::price_estimation::Estimate::gas`) for EIP-1271 orders.

### Naive Implementation

For an initial implementation, it would make sense to simulate the `isValidSignature` and then add some "gas buffer" (this is needed because gas at order placement != gas at auction time) to account for the general case, giving us a `maxSignatureValidationGas`. The `SignatureValidating` logic would then have to not only check that the `isValidSignature` returns the expected magic value, but also that the gas cost of calling `isValidSignature` is less than this upper bound.

Once this is implemented, we should be able to enable EIP-1271 signatures in production.

### More Advanced Implementation

Since EIP-1271 is extremely implementation specific, it could be that:
- The amount of gas is constant in all cases, so the buffer would be unnecessarily over-paying
- The amount of gas has a higher than normal variance (traversal through a linked list in storage for a convoluted example - but one that is legitimate because the Safe stores owners in a linked list for example, so its conceivable that signature verification may depend on this traversal). Then the client should be able to specify a higher upper bound so that they don't get excluded from auctions.

To account for this, the client would be able to provide a `maxSignatureValidationGas` (defaulting to the computed one from the naive implementation if none is provided).

### Solver Considerations

Since the gas price plays a role in the objective value, we need to communicate the `currentSignatureValidationGas` as part of the `HttpSolver` instance, this is so a solver doesn't try and include an EIP-1271 order because of its naturally higher fee amounts (which would increase the solution's overall objective value) without knowing the additional gas that it will end up using (i.e. the HTTP solvers might think that EIP-1271 orders are more attractive than they actually are).

Since we plan on removing fees from the objective value, this additional change might not be needed. I also don't think its a requirement for enabling this in production.

**Comment by josojo** [comment]
I will try to implement the naive version as part of the ethflow order package.

**Comment by elpiel** [comment]
@josojo we had a call today with @nlordell and I'll continue the development this week.
If it's ok for you, let's wait a bit to see what happens with the PR this week and we can't finish it up, I you can proceed with the naive version?

**Comment by josojo** [comment]
Oh, I was not aware. Yeah, I am happy, if you take it over, especially, if you started already.

**Comment by elpiel** [comment]
We should close this now.

Also, where is the deployed staging? We'd like to test this

**Comment by josojo** [comment]
It's live in the barn enviroment. 
https://barn.cow.fi/#/swap. and 
https://barn.api.cow.fi/docs/#/
