### ISSUE TITLE
Add some form of authentication to the new driver

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#421]
While working on #419 it occurred to me that the driver should have some form of authentication discarding requests which don't come from the real `autopilot`.
A possible attack vector was discussed [here](https://github.com/cowprotocol/services/pull/419#issuecomment-1206597813).

**Comment by sunce86** [comment]
@MartinquaXD Do you think this becomes more important with full colocation that we should include it in the colocation tasks?

**Comment by fleupold** [comment]
I think this is a nice to have (we can potentially use the circuit breaker key to sign the auction). Drivers can use api keys in their URLs and filter requests by IPs in the meantime to make sure they only get requests from legit autopilots.
