### ISSUE TITLE
Don't Filter Out Disconnected Orders for HTTP Solvers

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#454]
We should not, in the general case, filter out orders that aren't connected to the "fee token" for HTTP solvers.

Specifically, we had special logic for filtering out orders that aren't connected to the fee token through AMMs that is specific to the MIP and Quasimodo HTTP solvers (since they only use liquidity provided in the HTTP solver `instance.json`):

https://github.com/cowprotocol/services/blob/45d38ae6c43704c5f70a804efad871e3cda575c0/crates/solver/src/solver/http_solver.rs#L229-L233

This, however, does not make sense for external solvers since they use their own liquidity and should themselves decide whether or not an order is "sufficiently connected".

We should also stop sending AMM liquidity to solvers while we are at it.

**Comment by MartinquaXD** [comment]
> This, however, does not make sense for external solvers since they use their own liquidity...

I think continuing development with this assumption makes the barrier of entry for new solvers very high because they would have to reimplement all the basic liquidity sources.
Also the premise of the issue no longer makes that much sense when we have the solver + driver co-location. Then we can collect all the liquidity in the world without the need to filter anything and send it because it no longer has to go over the network.

**Comment by nlordell** [comment]
> I think continuing development with this assumption makes the barrier of entry for new solvers very high because they would have to reimplement all the basic liquidity sources.

This is a valid point. Currently no external solvers use our liquidity sources, but it is true that future solvers may want to.

With that in mind, it is totally possible to have a command line flag per external solver to include/exclude baseline liquidity if the need should arise in the future.

My point here was more that filtering orders that aren't connected with baseline liquidity to the fee token is incorrect for solvers that use their own liquidity. And since all external solvers that we have integrated with use their own liquidity, it means that they can't solve orders that they would otherwise be able to solve.

> Also the premise of the issue no longer makes that much sense when we have the solver + driver co-location

I disagree. Specifically, if these solvers don't use the baseline liquidity then they are "wasting" solving time collecting it. Also, assuming that the solvers require a "baseline liquidity connection" to the fee token from the traded tokens seems wrong to me (since they use their own liquidity).

**Comment by MartinquaXD** [comment]
After some offline discussion it turned out that I misunderstood the issue. Filtering out orders just because **we** are not aware of liquidity for it indeed doesn't makes sense and should be handled differently. Collecting the liquidity is unrelated to that issue.

**Comment by vkgnosis** [comment]
Current state:
Quasimodo still uses the order filtering from Rust. (MIP doesn't run anymore except to upload instances.)
Other http solvers do not.
