### ISSUE TITLE
Inaccurate prices reported for certain tokens?

### ISSUE THREAD

**Issue by raster21** [cowprotocol/services#462]
since ~2 days I've noticed that the prices of some tokens as reported by the backend are quite off. 

Take for example the price of [LDO](https://etherscan.io/token/0x5a98fcbea516cf06857215779fd812ca3bef1b32) in [solver_competiton 22017](https://api.cow.fi/mainnet/api/v1/solver_competition/22017)

Backend reports a price of `1401454850313722` while in reality it is ~5% lower when the competition happened.
This is a pretty liquid token, so I don't think it is connected to liquidity.

I noticed this with a few other tokens as well (e.g., CVX, AAVE).
Might there be a regression somewhere causing this?

**Comment by nlordell** [comment]
Our current observation is that the native token price estimates computed by the `autopilot` (which cuts the auction) doesn't match up with the native prices in the `orderbook`. This is likely the source of the issue and we are investigating.

**Comment by raster21** [comment]
@nlordell please let me know if there's anything else I can provide to debug this.

**Comment by nlordell** [comment]
Hey @raster21, an update on this:

We found that the `autopilot` native token price estimation was configured differently than its `orderbook` counterpart. This lead to slightly different prices between the two. We double checked and made sure that all price-related configurations are now the same between the two components, so it _should_ no longer be getting prices that are too far off.

That being said, given the configuration differences, I would expect the LDO price to be **below** market price (and not above market price). We're still looking into exactly why that happened.

In the meantime, are you observing price issues with any other tokens?
