### ISSUE TITLE
Improve EventHandler performance

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#478]
`EventHandler` is a generic struct that allows working with blockchain events, mainly retrieving events from blockchain and storing events in in-memory storage.
This becomes a bit tricky, because of the possible reorgs. At this moment, each time new block is detected on blockchain, maintenance is ran on an `EventHandler` and, instead of retrieving and storing only events from the last received block, `EventHandler` erases last 24 block history of events and retrieves 24+1 block of events and stores them into in-memory storage.

This is problematic in two ways:
- `eth_getLogs` is much slower when retrieving 25 blocks compared to retrieving only one block.
- Storing is slower since all searching/filtering algorithms need to iterate on a longer event list.

In order to handle reorgs better, we need `EventHandler` to work with `<block_number, block_hash>` pair instead of only `block_number`. This way, on each new received `block`, we can search for `block.parent_hash` in our storage. Three situations can happen: 

- [x] 1. `block.parent_hash` is actually `last_handled_block` in our storage, meaning no reorg happened, so we just ask the chain for events from the latest block and store them.
- [ ] 2. `block.parent_hash` is found in our storage (but different from `last_handled_block`), meaning reorg happened, so we need to replace >=1 blocks of events (this is where the 1 block deep reorg (most common one) is detected).
- [ ] 3. `block.parent_hash` not found in our storage, meaning deeper reorg happened. In this case we would need to ask the blockchain for block hashes, iteratively using the `parent_hash` field, until we come to the hash that exist in our storage, then do (2)

Since (1) and (2) will happen in 99% of newly mined blocks, I think (3) can be skipped, especially since additional and non-parallel `eth.block()` calls need to be done.

Based on a benchmark tests done on UniswapV3 pools, this improvement should reduce the time needed for events update by 3x - 4x.

**Comment by nlordell** [comment]
<details><summary>One other thing we can do is use a contract and <code>eth_call</code> with state overrides to <strong>atomically</strong> get reorg depth.</summary

```solidity
// SPDX-License-Identifier: MIT
pragma solidity ^0.8;

contract Blocks {
    uint256 private constant NOT_FOUND = type(uint256).max;

    error ReorgTooDeep();

    function latestBlock() private view returns (uint256 latest) {
        // The block transactions get simulated on is "incomplete". This means
        // that their is no block hash available for `block.number`. So, this
        // contract only looks at "final" blocks. Effectively, this means that
        // you should always simulate on the "pending" block so that the the
        // value of `latestBlock` actually represents the latest mined block
        // that the node knows about.
        latest = block.number - 1;
    }

    function blocks(uint256 depth) external view returns (uint256 latest, bytes32[] memory hashes) {
        latest = latestBlock();
        hashes = getHashes(depth);
    }

    function newBlocks(uint256 last, bytes32[] calldata chain) external view returns (uint256 latest, bytes32[] memory hashes) {
        uint256 commonAncestor = NOT_FOUND;
        for (uint256 i = chain.length; i > 0;) {
            unchecked {
                uint256 blockNumber = last - (chain.length - i);
                if (blockhash(blockNumber) == chain[--i]) {
                    commonAncestor = blockNumber;
                    break;
                }
            }
        }

        if (commonAncestor == NOT_FOUND) {
            revert ReorgTooDeep();
        }

        latest = latestBlock();
        unchecked {
            hashes = getHashes(latest - commonAncestor);
        }
    }

    function getHashes(uint256 depth) private view returns (bytes32[] memory hashes) {
        hashes = new bytes32[](depth);
        unchecked {
            uint256 startBlock = latestBlock() - depth + 1;
            for (uint256 i = 0; i < depth; ++i) {
                hashes[i] = blockhash(startBlock + i);
            }
        }
    }
}
```

</details>

@sunce86 also suggested to implement this as a Node "plugin" to avoid needing to maintain additional Solidity code.

**Comment by vkgnosis** [comment]
> * `eth_getLogs` is much slower when retrieving 25 blocks compared to retrieving only one block.
> 
> * Storing is slower since all searching/filtering algorithms need to iterate on a longer event list.

I agree that these things are slower but I'm not sure that this is problematic. It can be a relative speed up of x3 but an absolute speed up of a microsecond. Looking at the parent hash is a good idea and probably a better solution if we designed this from scratch but it might not be worth doing it now. Another advantage of this change (if 3. was implemented) is that we no longer need to hardcode the 25 blocks as the reorg limit. A disadvantage is that the event logic is slightly more complicated.

I like it overall and you already have an implementation.

**Comment by sunce86** [comment]
One thing to notice is that under POS, blocks are "finalized" after two epochs, meaning 64 blocks AFAIK, meaning we would need to change the hardcoded value from 25 to 64 and degrade performance.

> I agree that these things are slower but I'm not sure that this is problematic. It can be a relative speed up of x3 but an absolute speed up of a microsecond.

Yes, Storing is not that problematic, since everything is done in-memory, but `eth_getLogs` call on 25 blocks gives ~15k - 20k non-filtered events (I expect this to go even higher in high volatility periods when we have consecutive full blocks) and lasts for quite some time (up to 2s). Also, multiple `eth_getLogs` calls are possible since the chunk size is limited to 10k events per call.

**Comment by sunce86** [comment]
Closing with https://github.com/cowprotocol/services/pull/535
