### ISSUE TITLE
Improve current block stream when PoS arrives

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#487]
A few components currently use the [`current_block_stream()`](https://github.com/cowprotocol/services/blob/main/crates/shared/src/current_block.rs#L14-L63) to get notified when a new block was created. The current implementation polls in a constant interval (I believe 5s) to see the new block. That means in the worst case we might not see the new block for 4.9s.

When the merge happens new blocks appear every 12s. With that information we could let the background task looking for new blocks sleep for 11s and then poll for the new block with a higher frequency until it arrives.
This would give all the components using the `current_block_stream` way better block updates without changing any interfaces.

**Comment by vkgnosis** [comment]
Do blocks not need to propagate through the network with PoS like in PoW? I'm not sure about the details. In PoW we also have an expected block interval but this doesn't help you predict when your node will see any specific new block.

**Comment by vkgnosis** [comment]
If we want to lower delay we can easily change the poll interval to 1 second btw. I don't think there is a good reason to have it at 5.

**Comment by sunce86** [comment]
> Do blocks not need to propagate through the network with PoS like in PoW? I'm not sure about the details. In PoW we also have an expected block interval but this doesn't help you predict when your node will see any specific new block.

I think the block propagation time << 1s << block time, so I would just ignore it in this equation. 1s also seems like the `good enough` solution (and easiest), but I would be also in favor of implementing this improvement - sleep for 11s after the latest block timestamp, and then polling extensively next 2s, if no block is found fallback to 1s regular polling until block is seen.

**Comment by sunce86** [comment]
One thing I did not consider in my solution is support for other networks, where other rules apply for block creation. Therefore, changing the value to 1 is probably the simplest and safest.
