### ISSUE TITLE
Add contract pool addresses and liquidity fetching block to input json

### ISSUE THREAD

**Issue by harisang** [cowprotocol/services#494]
I believe it would be useful for solvers to know which pool each entry corresponds to, and also which block the information of each pool was fetched from. This should be very easy to implement, and I would suggest one entry in the metadata part of the input for the block number (since all baseline liquidity was fetched from the same block, right?), and one entry per AMM looking like:

`"address": "0x6033368e4a402605294c91CF5c03d72bd96E7D8D"`

This would help solvers to have a better understanding of what pools they might potentially use, and how up-to-date is this information. It would also help solvers that use the provided liquidity to more easily debug potential simulation failures, slippage etc.

**Comment by sunce86** [comment]
This is kind of related to the https://github.com/cowprotocol/services/pull/547
So, how problematic for solvers would be to receive liquidity that is fetched on different blocks? For example, UniswapV2 liquidity fetched on block N, Balancer liquidity fetched on block N, UniswapV3 liquidity fetched on block N-1?

That said, I would propose to expand input json with block_number per liquidity type, not just single one for all liquidity.

**Comment by harisang** [comment]
> This is kind of related to the #547 So, how problematic for solvers would be to receive liquidity that is fetched on different blocks? For example, UniswapV2 liquidity fetched on block N, Balancer liquidity fetched on block N, UniswapV3 liquidity fetched on block N-1?
> 
> That said, I would propose to expand input json with `block_number` per liquidity type, not just single one for all liquidity.

Yeah, that makes sense, and I think it's fine!

**Comment by jeff-liang** [comment]
Yeah want to second this for sure, especially having the pool address. I was just asking Haris if this could be included as it would be very helpful!
