### ISSUE TITLE
Year and Name in License?

### ISSUE THREAD

**Issue by bh2smith** [cowprotocol/services#506]
Should we be filling these out?
https://github.com/cowprotocol/services/blob/5b57e71f98ade3b232c4203b93e3cff5f1d63da4/LICENSE-APACHE#L189

**Comment by nlordell** [comment]
No, this is part of the appendix of the license where:
>       To apply the Apache License to your work, attach the following
>       boilerplate notice, with the fields enclosed by brackets "[]"
>       replaced with your own identifying information.

For example, the Rust project just doesn't include the appendix in their `LICENSE` file:

https://github.com/rust-lang/rust/blob/9353538c7bea6edb245457712cec720305c4576e/LICENSE-APACHE#L176

And the Apache HTTP server (the license's namesake), also leaves this without filling it out:

https://github.com/apache/httpd/blob/e4d01cf5e2ece98313e932c1799ab0ab7d938db1/LICENSE#L189
