### ISSUE TITLE
Check that some integers given to the mip solver are strictly positive

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#51]
Some numbers like the uniswap balances must be strictly positive (> 0). On the rust side we should make sure of this in order to not give invalid data to the solver.

> Original issue https://github.com/gnosis/gp-v2-services/issues/700 by @vkgnosis

**Comment by MartinquaXD** [comment]
Probably no longer relevant and seems like something that should be fixed in the solver anyway since a balance of `0` sounds like a perfectly reasonable value.
