### ISSUE TITLE
Block-2-Block Auctions

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#545]
Creating an issue to start a discussion on block-2-block auctions.

Now that we have PoS, block delay is very deterministic. This means we can do a few things:
```
          d       f                 s                 p
time ---+-------+-------+---------------------------+-------+--->
        |       |       |                           |       |
        block   |       |                           |       |
                block seen by node                  |       |
                        |                           |       |
                        liquidity fetched           |       |
                                                    transaction submitted
                                                            |
                                                            next block
d = block propagation delay
f = liquidity fetching delay
s = solve time
p = transaction propagation delay
```

Ideally, we would be able to re-work our services to be able to achieve ☝️ (trying to maximize `s`, minimize `f` and while fitting in within typical block and transaction propagation delays).

**Comment by vkgnosis** [comment]
Is there a way we can measure how deterministic block delay is? I feel it's plausible but I am not sure how predictable it really is.

**Comment by nlordell** [comment]
AFAIU, block delay/timestamps in PoS are deterministic in that they are set by the protocol (you get assigned a slot which has a specific block timestamp - one slot every 12 seconds, meaning you sometimes get 24 seconds between blocks because a validator misses proposing a block).
