### ISSUE TITLE
Retrieve block specific on chain state through hash instead of number

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#551]
@nlordell mentioned this in a PR. I agree that it makes more sense. We use a block number when for example fetching liquidity so that we get a consistent view. By using a block hash we are closer to that goal.

**Comment by sunce86** [comment]
I don't fully understand how the fetching with block hash instead of block number would circumvent the issue with multiple node infrastructure?

**Comment by nlordell** [comment]
To me, its a small change that helps in two small ways:
- It prevents issues (not PoS-specific, but on other networks) where the same block number represents different blocks at the same height
- Nethermind-specific on PoS, there are weird errors where getting block by number finds the block header but not the block state. This way we get slightly more consistent errors in those cases.

**Comment by sunce86** [comment]
Some liquidity fetchers use `eth_call` that does not support block hash as a parameter :( although I agree with your points

**Comment by nlordell** [comment]
`eth_call` should support fetching by block hash... At least it does in all the nodes we use:
- [Geth](https://github.com/ethereum/go-ethereum/blob/8ade5e6c144afb7ac389ae28b50cb68a0dbec7b8/internal/ethapi/api.go#L1040)
- [Erigon](https://github.com/ledgerwatch/erigon/blob/05df5a473961c3597a8f0731ac76dcf4ab4d6e25/cmd/rpcdaemon/commands/eth_call.go#L32)
- [Nethermind](https://github.com/NethermindEth/nethermind/blob/6d0409c2c98c3a311c29fd90491666f33e7d5f0d/src/Nethermind/Nethermind.JsonRpc/Modules/Eth/EthRpcModule.cs#L371)

**Comment by sunce86** [comment]
My bad, I did not check the code, only the official docs. Then I guess only node services are questionable (infura for example I think does not allow sending block hash)

**Comment by nlordell** [comment]
I just double checked and Infura does let you use block hashes for simulations:
```
% curl -s  -X POST "https://mainnet.infura.io/v3/$INFURA_PROJECT_ID" -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":0,"method":"eth_call","params":[{},"0x190034daf98391e5caa35b715a4af2f03c2e9ad53dc365035a228b31c0b00814"]}' | jq
{
  "jsonrpc": "2.0",
  "id": 0,
  "result": "0x"
}
```

**Comment by sunce86** [comment]
> I just double checked and Infura does let you use block hashes for simulations:
> 
> ```
> % curl -s  -X POST "https://mainnet.infura.io/v3/$INFURA_PROJECT_ID" -H "Content-Type: application/json" --data '{"jsonrpc":"2.0","id":0,"method":"eth_call","params":[{},"0x190034daf98391e5caa35b715a4af2f03c2e9ad53dc365035a228b31c0b00814"]}' | jq
> {
>   "jsonrpc": "2.0",
>   "id": 0,
>   "result": "0x"
> }
> ```

That's weird, I got an error using Postman. Will check again.
