### ISSUE TITLE
Multiple node infrastructure - Summary

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#554]
With multiple node infrastructure in action, our RPC requests end up at different nodes having possibly different view of the blockchain state. 
Here, we need to differentiate two situations:

1. All node instances are healthy, meaning only block propagation delay is in play. We need to support cases where one of the nodes is slower at receiving the newest block, meaning usually one of the nodes is at block N, while the other is at the block N+1.
2. One of the nodes is out of sync, meaning is either stuck or more than 1 block away from others (I would expect `dshackle` to handle this and exclude the node, although I am not sure this is true).

So, we need to handle (1). Currently identified issues are:

1. `NativeGasEstimator` https://github.com/cowprotocol/gas-estimation/issues/9
2. `current_block_stream` - probably not problematic in most cases because it polls every 5s and already handles the receival of the same block https://github.com/cowprotocol/services/blob/82321ca2b6ef9337de0cb6b04cdf7aad1f6a991a/crates/shared/src/current_block.rs#L51
Also related: https://github.com/cowprotocol/services/pull/566
3. `LiquidityCollector` - problematic because it works with specific block numbers. One possible fix is https://github.com/cowprotocol/services/pull/547
4. `RecentBlockCache` - already resolved with ?https://github.com/cowprotocol/services/blob/82321ca2b6ef9337de0cb6b04cdf7aad1f6a991a/crates/shared/src/recent_block_cache.rs#L184
5. `Web3BalanceFetcher` - alert https://cowservices.slack.com/archives/C0371SB243E/p1663295508295349
Here, I think we tried to get the balance of not existing `owner` - meaning our node under web3 instance at the moment of fetching the balance is delayed (not 100% sure)
6. `HttpSolver` - alert https://cowservices.slack.com/archives/C0371SB243E/p1663285012386209
Here, one of the batch request failed (if batched request are also loadbalanced to different nodes then this is also another issue).
Logs: https://logs.cow.fi/goto/e1008300-3689-11ed-803a-9f8784480050
This could be partially solved with `Multicall`: https://github.com/cowprotocol/services/issues/452. What we still need to handle is the case when all requests fail.
7. `error retrieving current auction` - alert https://cowservices.slack.com/archives/C0371SB243E/p1663338705180459
https://github.com/cowprotocol/services/blob/82321ca2b6ef9337de0cb6b04cdf7aad1f6a991a/crates/orderbook/src/orderbook.rs#L283
This one is probably caused by a stuck node rather than a delayed node, so should not be fixed in code?
8. `EventHandler` might skip the newest block if it not seen by some of the nodes. (no alert for this, we currently skip instead of raising the maintenance error)

**Comment by MartinquaXD** [comment]
Since this issue was created we migrated to a setup without load balancing where 1 node handles all the traffic and can be replaced by a hot spare if it goes down. This should resolve all state inconsistency issues (except maybe when we switch to the hot spare but that's okay IMO).
