### ISSUE TITLE
Risk-adjusted solver rewards

### ISSUE THREAD

**Issue by marcovc** [cowprotocol/services#556]
There is a CIP in the making that will change the way we reward solvers, from the current scheme where a more or less fixed reward is issued per auction (50 COW per batch + 35 COW per order), to a scheme where the reward is a function of network volatility.

The blog post describing this is [here](https://forum.cow.fi/t/cip-draft-risk-adjusted-solver-rewards/1132).

From the services perspective, we will have to send a new key "rewards" in each user order in the instance.json we send to solvers. This rewards key will be filled from the result of a simple formula that contains:

1. the current gas price
2. the estimated gas cost of the order (or more precisely the gas cost of a settlement with just that order in). **
3. two constants that are obtained from regression

We already have everything we need to compute the rewards, except 3, which in the most basic implementation could be supplied by command line parameters (these parameters would be updated periodically, say once a month, when we run the regression outside of the driver code).

Finally, these rewards per order should be recorded on the solver_competitions endpoint or some db so that the data team can compute the weekly payouts.

** note: currently the estimated gas cost for an order is the same for every user order, so that would imply that the rewards is also the same in the proposed (simplistic) rewards model. But since we've went with a per order cost, I'd suggest going with a per order rewards for coeherence.

**Comment by marcovc** [comment]
For future reference, [here](https://github.com/cowprotocol/risk_adjusted_rewards) is the repo that contains the code for computing the ~two~ three constants from regressing on past data.

**Comment by vkgnosis** [comment]
captured by https://github.com/cowprotocol/services/issues/606
