### ISSUE TITLE
EIP1271 gas estimations

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#576]
I wanna propose and discuss here one possible implementation for eip1271 order fee estimations.

Currently, we only validate the signatures like this:
```
async fn validate_signature(                       
 16         &self,                                       
 15         check: SignatureCheck,  
 14     ) -> Result<(), SignatureValidationError> {
 13         let instance = ERC1271SignatureValidator::at(&self.web3, check.signer);
 12         let result = instance                                                    
 11             .is_valid_signature(Bytes(check.hash), Bytes(check.signature))     
 10             .gas(40_000.into())                                             
  9             .call()                                                       
  8             .await;            
  7                      
  6         parse_is_valid_signature_result(result)
  5     }  
```

Instead of using an `eth_call` under the hood, we could use an `eth_estimateGas` and return the estimated gas during order creation. 
This estimated gas amount could be appended to the estimated gas for the overall settlement of the eip1271 order. 

However, this approach would not consider the changes in the gas required for calling `is_valid_signature`. I would argue that this is okay, as also the same is true for all our interactions. There we are also estimating the gas beforehand, but actually, in the block the gas consumptions for gas estimates could be quite different. (Sure the risk for eip1271 orders to change their gas amount is bigger, as the simulation is shortly before submitting, but fundamentally, we have the same issue).

Ideally, we would use a gas profiler and see in the settlement simulation that the gas-amount has not changed. But I think it's okay if we only add this later, as this would add another dependency for us.

Would you guys be okay with going into production with eip1271 orders without the gas profiler check?

**Comment by vkgnosis** [comment]
Is this same issue as https://github.com/cowprotocol/services/issues/420 ? If yes let's move discussion there.
