### ISSUE TITLE
Try testing archer network with mocks

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#60]
I want to continue integrating this and then come back to adding a test with mocks. From my pov I don't feel they will add much confidence in that this is correct and they make the code more complicated because of extra traits. If we mocked web3 on a transport level the test set up would probably be very annoying so I think an extra trait for our specific high level logic is better.

_Originally posted by @vkgnosis in https://github.com/gnosis/gp-v2-services/issues/825#issuecomment-880706897_

> Original issue https://github.com/gnosis/gp-v2-services/issues/864 by @vkgnosis

**Comment by MartinquaXD** [comment]
Completely outdated and no longer in use.
