### ISSUE TITLE
Record solution calldata with internalizable interactions for solution comparison

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#604]
The calldata we currently expose in our solution competition endpoint only contains the final transaction payload after removing internalized transaction. For debugging and comparing different solver solutions externally, it is necessary to also record the interactions that have been internalized somehow.

Maybe we can expose both the "optimised" and "unoptimised" calldata as part of the solution competition struct.

**Comment by nlordell** [comment]
Related to #635
