### ISSUE TITLE
Filter by owner OR recipient for /account endopoint

### ISSUE THREAD

**Issue by anxolin** [cowprotocol/services#607]
> Not too important issue, but I just don't want it to be lost, so I will document in Github

The Explorer uses the endpoint `/account/<address>` to display the orders for a given account. 

I can see we return only the `owner` who created the order.

**Question**
* Should we return also the orders if the address matches the `recipient` (`WHERE owner = address OR recipient = address`).

From a user point of view, it makes sense to me. If so, is this something we can add? 

**Example**
Here is an example, this [order](https://explorer.cow.fi/rinkeby/orders/0xe2b9d49d8760fcaf776b3603b74319a4ed3fd57a95722207c03b611104d7c9c879063d9173c09887d536924e2f6eadbabac099f5633aeca4) it’s only displayed for the [owner](https://explorer.cow.fi/rinkeby/address/0x79063d9173C09887d536924E2F6eADbaBAc099f5), but not for the [receiver](https://explorer.cow.fi/rinkeby/address/0x424a46612794dbb8000194937834250Dc723fFa5).

**Context**
https://cowservices.slack.com/archives/C0375NV72SC/p1664804650550349

**Comment by vkgnosis** [comment]
On the other hand it could be confusing if you see orders created by someone else who set the recipient to your address.

**Comment by nlordell** [comment]
I think this makes sense once you start adding smart orders (and specifically EIP-1271) to the mix.

I would expect this to be either a separate route or a query parameter though.

**Comment by josojo** [comment]
>I think this makes sense once you start adding smart orders (and specifically EIP-1271) to the mix.

yes, please

>I would expect this to be either a separate route or a query parameter though.

why a separate route? For the front-end it is the easiest if we just have one order table and they don't have to merge all the data from different API requests. 
IMO, if the db performance will be okay, then we can keep it all behind one API route. Sure, we can add a parameter for sure...

I made a draft PR [here](https://github.com/cowprotocol/services/pull/610), where I think the performance is still good enough to provide it all through 1 API endpoint. But probably, we need a little bit more thorough testing...
happy to hear your opinions

**Comment by nlordell** [comment]
> why a separate route?

Mostly for compatibility, as API clients may expect `api/v1/orders` to only return orders for which they are an owner. Don't get me wrong, I don't think we should have route for **just** orders with receivers set to an address, but rather a separate route (or query parameter) for orders by owner+receiver and the current route for orders by owner.
