### ISSUE TITLE
Refund service for ethflow orders

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#626]
**Background:** 
ethflow orders are placed via an onchain transaction that locks ETH into a separate contract - the ethflow contract. If the orders are settled, the ETH is taken out of the contract and exchanged. But if the order is not settled, we need to get the ETH back into the user's wallet. This will be done by an on-chain transaction sent by the refunding service.
In order to prevent abuse of our refunder service, we will only refund "reasonable" orders. Orders will be reasonable if they had at least 2% slippage and were valid for more than 5 minutes since mining.

**Specification:** 
I imagine the refunding service working in the following way:
- We add a new db entry for ethflow orders that signals whether an order is already refunded `is_refunded`.
- The refunder service should run a loop that checks every 10 secs, whether a new ethflow order is
    * Non-refunded
    * Non-settled
    * Invalided by the user_valid_to
    * Had a reasonable user_valid_to (validity_duration := order.valdiity - order.creation_timestamp > VARIABLE)
    * Had a reasonable slippage
- The refunder service will collect all eth-orders that are fulfilling this condition
- The service will check one more time, whether the orders are not yet refunded by advanced users with batch_call to web3
- For the orders that are still to be refunded, the service sends out a transaction to refund the user's eth by calling the `deleteOrders` functionality in the smart contract. The tx is sent out with a small tip, but a high gas price - 50% - of the current gas price
- The service waits and checks for 5 blocks, whether the tx was mined. 
   * If the transaction was successful, the "is_refunded status" is being updated in the db
   * If the transaction reverted, there will be an error message and we will retry the same loop.
   * If the transaction did not mine in time, the refunder will also restart the loop, do a new gas estimate and send out the tx again with same nonce
   * If there are no new blocks, the service will wait much longer than the expected mining time for the 5 blocks, but eventually throw an error and start the loop again.

- After 10 secs, it starts the next loop

I think the logic is quite separate from all the other services and hence, a new crate seems to be the right place. This will allow us long-term to isolate the logic of the refunder service.

Regarding the variables: 

`duration_validity` -> 
- I think that if we make a query that has to calculate the `orders.creation_time - ethflow_orders.user_valid_to` for each ethflow order, then the query will be quite slow over time. I think we should better store the validity-duration directly in the table and get an index on it. 
I think there are two ways:
     - Method1:  Make the autopilot parse the block-timestamp at the creation and then calculate the order validity-duration. PR is here:
https://github.com/cowprotocol/services/pull/632
     - Method 2: Or make the refunder query for new eth_orders that have not yet a calculated validity-duration, then calculate the validity-duration and put it into the data-table. Then the refunder service is more isolated.

PS: I think it would be better to set it as the timestamp of on-chain order placement - the block timestamp instead of user the timestamp of the event parsing. (Then a lagging behind of our autopilot is not influencing the timestamp of the order creation) 

`slippage` ->
- Since the slippage is always calculatable from the raw data: `order_quote` + `order`, but again I think over time it would benefit us to have an index on this difference. Since indexes can not be created over serval tables, we should insert a new slippage field in the database.
Again there are two different ways to do it:
   - Method 1: Autopilot does it: https://github.com/cowprotocol/services/pull/632
   -  Method 2: Refunder queries periodically for orders that don't have a slippage value in the database, and then calculates the slippage value and store it.
 

expected PR structure:

- [x] Database schema update for ethflow orders
- [x] DB operations for reading “ethflow_orders_to_refund”
- [x] DB operations for updating the “refunded” variable
- [x] Empty new crate for refunder within the service repo - the refunding service for ethflow orders
- [x] Empty worker functionality: 	 loop for checking for refundable ethflow orders
- [x] Adding the ethflow contract abi
- [ ] Transaction initiating PR to refund ethflow-orders
- [ ] Transaction lookup PR: Whether it was mined in time
- [x] Updating the refund status.

**Comment by vkgnosis** [comment]
You can create a new crate. Could also consider whether autopilot should do this. I'm not sure.

**Comment by vkgnosis** [comment]
Did you think about new crate vs in autopilot? (Sorry if already explained somewhere.) The idea for autopilot that it runs all the background tasks that only need to happen once so this fits. On the other hand I could see that ethflow things are not related to the rest of the system but then we do store events etc in the same database. Overall there is probably a little less code/config overhead from putting it into autopiloit.

**Comment by vkgnosis** [comment]
If we want more decoupling then why have autopilot handle ethflow events at all? Couldn't the ethflow specific crate also insert these events? It feels weird that autopilot has to store data that is only needed for the refunder.

I don't have a strong opinion on whether ethflow should have a separate crate. We can decide it based on your intuition.

> I think that if we make a query that has to calculate the orders.creation_time - ethflow_orders.user_valid_to for each ethflow order, then the query will be quite slow over time. 

It's just a join. It's not obvious to me that that is slow. It depends on what the query is doing and how many ethflow orders there are. For example in order to get solvable orders we currently join a bunch of tables including the `trades` to see whether the order has been filled. This hasn't been too slow.

**Comment by josojo** [comment]
>I think that if we make a query that has to calculate the orders.creation_time - ethflow_orders.user_valid_to for each ethflow order, then the query will be quite slow over time.

>It's just a join. It's not obvious to me that that is slow. 

It's a join that also needs to calculate the difference + time conversion every time. 
But yes, even in an optimistic case, I think we will not have more than 1000 ethflow orders per month. And most of them can be sorted out by the join immediately, as their transaction status will hopefully be "settled".

Let me create a realistic benchmark. I will share it here. Thanks for your input!

**Comment by josojo** [comment]
Nice @vkgnosis you were right.https://github.com/cowprotocol/services/pull/674
Performance is okay. With that, we don't need any additional DB operations for slippage and min_validity_duration. Great.
> Couldn't the ethflow-specific crate also insert these events? It feels weird that autopilot has to store data that is only needed for the refunded.
This is then cleared, as the autopilot stores, just general on-chain order information and they are sufficient for the refunder service.

With that, we can have a cleaner separation. Hence, I would put the refunder into its own crate.

**Comment by vkgnosis** [comment]
> With the new insight, this is cleared, as the autopilot stores just general on-chain order information

But there is still code that is called "ethflow" in the autopilot, right? So it seems it is doing something that is only needed for ethflow. Again, this isn't a big problem it just feels a little inconsistent with the other goal of separating them as much as possible.
