### ISSUE TITLE
Find more robust way to match auction IDs to settlement transactions 

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#634]
Comes from https://github.com/cowprotocol/services/issues/606#issuecomment-1268259834

It is important that can we associate auction ids to settlement transaction hashes. Currently this is possible through the competition database table. This doesn't work perfectly. If the solver is restarted at the wrong moment or we have node problems we might not observe the transaction completing. We should improve this.

**Comment by sunce86** [comment]
How about saving the relation between `auction_id` and `(sender, nonce)` pair whenever we enter submission. Later we can connect `(sender, nonce)` with the transaction hash.

**Comment by nlordell** [comment]
This is similar to what we suggested for keeping track of driver submissions in #230.

**Comment by vkgnosis** [comment]
I was looking into this and was surprised that there doesn't seem to be a way to get a transaction (hash) from account + nonce. This doesn't exist in the node api. Nodes definitely have this information because they can give you the nonce from a transaction hash but there is no api to go in the other direction.

**Comment by sunce86** [comment]
I was thinking of getting the transaction by transaction hash and then extract nonce and sender from transaction and compare to the saved set of `(sender, nonce)` pairs?

**Comment by vkgnosis** [comment]
The solution I wanted was roughly this:
- We have a database table with auction id, account, none, transaction hash.
- When the driver decides it will submit the solution on chain we record account, none, auction id in the table.
- In autopilot there is a task that looks for rows that do not have a transaction hash associated with them yet. Based on the account and nonce we look up the transaction. If the transaction is behind the reorg interval then we add the tx hash to the row.
- TODO: Some mechanism that kicks in when we do not get a transaction at all because then we might eventually reuse the nonce.

I came up with this because it protects against all kinds of driver failures. Doesn't matter when or how the driver gets interrupted.

If there is no api to get a transaction from account and nonce then we need to do it in a more roundabout way. For example we could go through the settlement events that we already index, get those transactions and then check if the account-nonce pair is in the new table. That should still work, it's just more code to write. I guess that is what you had in mind already.

**Comment by sunce86** [comment]
What about:
- We have a database table with auction id, account, nonce, transaction hash, is mined.
- When the driver decides it will submit the solution on chain we record account, nonce, auction id, transaction hash in the table (each solution submitter builds tx hash prior sending).
- In autopilot there is a task that looks for rows with `is mined = false` and searches blockchain for it's transaction hash for those rows. If found, set `is mined = true`, else remove from table (if reorg safe).
- ~TODO: Some mechanism that kicks in when we do not get a transaction at all because then we might eventually reuse the nonce.~ we don't need this anymore IIUC

**Comment by vkgnosis** [comment]
Downside with this approach is that we need more communication between driver and DB because we have many different transaction hashes as gas price changes. With account and nonce we know everything immediately. Will mull it over more.

**Comment by vkgnosis** [comment]
relevant PRs

https://github.com/cowprotocol/services/pull/720
https://github.com/cowprotocol/services/pull/733
https://github.com/cowprotocol/services/pull/741
https://github.com/cowprotocol/services/pull/744
