### ISSUE TITLE
What should we do if risk adjusted reward computation fails?

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#650]
The risk adjusted reward calculation in `crates/autopilot/src/risk_adjusted_rewards.rs` can fail:
1. Calculation of gas price and cow price can fail. This is needed for all orders so the whole process fails.
2. Calculation for an individual order can fail because there is no quote. If an order is neither partially fillable nor a liquidity order then we expect it to have a quote and a quote is required to calculate the reward.
3. Calculation for an individual order can fail because of a bug in the math. We have a check that the end result of the calculation is a reasonable floating point number.

In 1, autopilot errors out and doesn't create the auction. This is correct IMO.

How should 2 and 3 be handled?
Currently this results in the order having a 0 reward. Assuming that solvers are aware of the reward field this seems fine. But if solvers have not updated yet it could cause them to settle orders without receiving reward for them.
Alternatively we could use a dummy reward like the previously used `37` or exclude the order from the auction. I prefer the previous solution because it gives solvers the most freedom. But if we had bug in this calculation it could be safer to use a placeholder to still incentivize settling these orders even with an inaccurate reward.

**Comment by nlordell** [comment]
> In 1, autopilot errors out and doesn't create the auction. This is correct IMO.

Agreed.

> Calculation for an individual order can fail because there is no quote.

In this case, we should use the "minimum reward" I think (i.e. assume that its 0 gas to execute the order - I think this is the same minimum that we use for completely internalized batches). Like you said, this should never happen (because all non-liquidity/non-partially-fillable orders have quotes), but we should definitely log something if this happens.

> How should [...] 3 be handled?

I think we can use the same strategy as above. We would just need to compute the "min reward" amount at startup (and we can error if that fails).

**Comment by nlordell** [comment]
**Edit**: Looks like "minimum reward" is just `37` (as defined in the CIP-14).

**Comment by MartinquaXD** [comment]
> In this case, we should use the "minimum reward" I think

Why should we return possibly wrong rewards data instead of just omitting the order from the auction if that case is expected to be rare anyway?

**Comment by MartinquaXD** [comment]
We simplified the reward scheme since the creation of this ticket so it no longer applies.
