### ISSUE TITLE
PreInteractions: Refactor simulations in autopilot

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#652]
For some orders, a pre-interaction first needs to be executed, before other validity checks like "transfer-in", or allowance checks, or balance checks become valid. One example is for the allowance check, we might first have to execute the [EIP2612 approval](https://eips.ethereum.org/EIPS/eip-2612)

In the autopilot, we could do in a single eth_call that:
- Simulates the pre-interaction
- Check the balances
- Check the allowance
- Simulate the transfer-in

This might actually be slightly less stress on our nodes than the 3 parallel calls that we do for balance checking.

**Comment by MartinquaXD** [comment]
Fixed with https://github.com/cowprotocol/services/pull/1586 and its friends.
