### ISSUE TITLE
Move away from Open Ethereum

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#67]
OE is reaching its end of life (London hardfork will be the last one supported) and therefore @giacomolicari asked us to move away from it in the mid term.

There are a bunch of alternative nodes we could look at:
- geth
- nethermind
- erigon

In particular for our API (and the bad token detector) we require `trace_callMany` to be enabled (ruling out geth). Also while nethermind implements parts of the trace api, it doesn't seem to implement `trace_call` or `trace_callMany`.(https://docs.nethermind.io/nethermind/ethereum-client/json-rpc/trace)

### Erigon

I tested Erigon in rinkeby staging a while back and it was working fine for the API. However, it wasn't working well for the solver, as it doesn't seem to implement `eth_getBlockByNumber(pending)` (it only works for latest). We use this when trying to find a pending transaction after a restart. The erigon team suggested to instead use the `txpool_content` method.

Last time I tried this one it had issues with the size of the mem-pool but those should be fixed in the most recent version.

Since EIP 1559 however, the `trace_callMany` is complaining unless we set a gasPrice on our requests that exceeds the base fee. It doesn't seem to check the funds of the from account (thus we can use U256::max as a dummy value), however that value doesn't seem working with OE (they check funds, but are fine with a 0 gas price). [I asked in their discord](https://discord.com/channels/687972960811745322/789381905958699018/869941597943529552) and am waiting for a suggestion.

Maybe in the worst case, we could estimate the current gas price in the BadToken Detector and set a reasonable value that satisfies both OE (in terms of balance) as well as Erigon (in terms of base fee)

All in all, I think this struggle is another reason why #858 might be a better way to go than relying on non standard RPC methods. If this was implemented the need for tracing would go away as bad tokens would be detected via a single baseline solution simulation instead of a series of test calls.

> Original issue https://github.com/gnosis/gp-v2-services/issues/909 by @fleupold

**Comment by sunce86** [comment]
Moved away long ago 😆
