### ISSUE TITLE
Race condition in solution submission leading to missing transaction hash

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#671]
I noticed this when investigating the one missing settlement transaction for the solver pay out this week.
[logs](https://logs.gnosis.io/goto/4be4fcd0-5531-11ed-b3dc-b32b223fac1c) (prod mainnet, auction{id=2599877 run=51228}, around 2022-10-23T11:16:25.723Z).

I believe what happened here is that in `Submitter::submitter` we see the nonce increase first before we add the potential tx hash to `transactions`. This happens because in `PublicMempoolApi::submit_transaction` the call to `send_raw_transaction` did not return yet but the node actually already broadcasted the transaction.

We should add the transaction hash to the transactions vector even before making the call so that this cannot happen.

**Comment by MartinquaXD** [comment]
Switched to a different submission logic since then so this no longer applies.
