### ISSUE TITLE
[onchain orders] Invalid onchain orders

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#676]
Some orders that are parsed via the onchain order indexer might be "illegal".
E.g. it could be that the valid_to is too high or they might use "bad tokens" or their quote might no longer be valid.

These illegal orders should always be prevented, as users spend gas for orders that we will not settle. Hence, we should try to flag them already in the quoting process as illegal. 
But since users might not go through the quoting procedure, they could still create illegal orders via on-chain parsing, or it could happen simply because the quote is no longer valid.

Now, we have two requirements:
- We should still show the users that we indexed their orders and did not forget about it. Hence, illegal orders should be created and put into the database
- Showing this information is quite important as this will be the entry point for the users of the refunds
- Illegal orders should not affect any db-query performance and should not appear in any auction or any metric about "non-settled" orders.

Solution proposal:
- The order field: order_status gets a new enum entry: `Invalid order`. 
- On db, level, we give each onchain_order a new optional enum entry in the `onchain_order_placed` table: `reason_for_invalid_order_placement` with the enum fields: `valid_to`, `bad_token`,  `no quote`, 'invalid_order_class' ...

The logic would then be that illegal orders are being parsed but get the flag `reason_for_invalid_order_placement="reason"`.
Whenever an order has this field set(!=null), we would derive the order status as `Invalid order`, but still serve it via API, such that users can see their order as being parsed.
Orders with `valid_at_order_placement!=null` are excluded from the solvable_orders.

wdyt?

**Comment by MartinquaXD** [comment]
The idea looks reasonable to me. Just a few questions:

> But since users might not go through the quoting procedure, they could still create illegal orders via on-chain parsing.

This can only happen if the user interacts with the smart contract themselves instead of going through our frontend, right?
Would refunding those illegal orders work out of the box or is there some additional work to be done?

**Comment by josojo** [comment]
> Would refunding those illegal orders work out of the box or is there some additional work to be done?

I think we should not refund illegal orders. If DAO use this functionality of placing orders without a quote, they should check beforehand how they are placing the orders. They can always refund orders themselves.

>Do we really want to support orders that weren't created through the frontend for this?
I think long-term the DAO -treasury management use case would need this. But yes, for ethflow orders, it's not needed right now.

>Intuitively I think we can index illegal orders into the onchain orders table but we shouldn't create an entry in the full orders table.
Agreed.

**Comment by vkgnosis** [comment]
> > Intuitively I think we can index illegal orders into the onchain orders table but we shouldn't create an entry in the full orders table.
> 
> Agreed.

In this case we don't need the new invalid status and column reason_for_invalid_order_placement. We just don't turn them into full orders. But I'm not sure how it works out with other queries.

**Comment by anxolin** [comment]
Nice! I think is a good idea. 
Could we add the proposal to swagger? Also, an example on the proposed JSON result would help.
