### ISSUE TITLE
Add a status service for GPv2

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#72]
It would be nice to have a status page to inform users about potential outages. We would to setup a way to get some basic status information to users.

> Original issue https://github.com/gnosis/gp-v2-services/issues/966 by @nlordell

**Comment by MartinquaXD** [comment]
FYI we have this [beauty](https://github.com/cowprotocol/uptime) where the uptime of the `/quote` API is equated to the uptime of the entire backend. So it's not perfect but overall a pretty good solution IMO.
