### ISSUE TITLE
Pagination on trades and orders calls

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#73]
Add pagination to API for both trades and orders calls:

GET /api/v1/orders
GET /api/v1/trades

API should accept an optional parameter `pageSize` stating how many results should be returned at a time. Defaults to `10`.
API should accept an optional parameter `page` stating which is the current page being requested. Defaults to `0`.

## Proposal

`pageSize` must be an integer within the range (inclusive) from 1 - 100
When not set, set to a value outside of the range or an invalid value (undefined, 1.3, `gibberish`, etc), it should default to `10`

The API - to protect itself - should not allow to force-request all db values at once.

The response will probably have to change to include metadata regarding the pagination.
Instead of returning a flat list of results, it'll have to change to something like:

```json
{
  "results": 2123,
  "page": 3,
  "pageSize": 50,
  "results": [{}, ...]
}
```

**Discussion:** 
- We could allow higher `pageSize`, 100 is a conservative proposal
- We could set a higher default `pageSize`, no strong reason to keep it at 10
- The change in the response is a breaking change. Any suggestions to make the transition smooth? Deploy an extra endpoint, alter the response based on a request flag, etc.
- I based the pagination "design" in the most common pattern, but I'm not entirely sure how that would work given that the primary keys are non sequential. Instead of an integer could the page be a sort of db "cursor"?

> Original issue https://github.com/gnosis/gp-v2-services/issues/969 by @alfetopito

**Comment by alfetopito** [comment]
I believe this issue has been covered already and could be closed
