### ISSUE TITLE
Compute Surplus Fees for N Most-Favourably Priced Orders

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#765]
> One additional step we could consider is to have an upper limit on orders in an auction. Then we could take the n most favorably priced orders in case there are too many orders we consider reasonable.

_Originally posted by @MartinquaXD in https://github.com/cowprotocol/services/pull/752#pullrequestreview-1175196132_

**Comment by MartinquaXD** [comment]
Closing since auction size is not a big concern anymore.
