### ISSUE TITLE
Investigate unsupported yearn tokens

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#773]
Alex V told me that the following yearn related tokens aren't supported but he expects them to and this is important for an announcement in a couple of days. We should investigate what is going on.

- `0x19D3364A399d251E894aC732651be8B0E4e85001`
- `0x5f18c75abdae578b483e5f43f12a39cf75b973a9`
- `0x5533ed0a3b83f70c3c4a1f69ef5546d3d4713e44`

**Comment by nlordell** [comment]
Turns out these tokens are actually unsupported because of a Vyper compiler bug.

Closing the issue.
