### ISSUE TITLE
[Ethflow] Make ethflow orders unique

### ISSUE THREAD

**Issue by josojo** [cowprotocol/services#804]
Motivation:
the ethflow contract does not allow distinct orders with the same orderhash. Hence, we wanna make each order unique by changing the quoted fee_amount a little bit, such that the orderhash is different.

- create a new index sell_amount on the data-table quote, in order to access db
- build DB operation to look up an existing quote with the same values as the newly computed quote
- if the quote has a sell_token == weth and if the quote is for EIP1271 orders , then we should check for duplication
-  Modify the quote, if the quote already exists by increasing the feeAmount by 1 Wei.

**Comment by MartinquaXD** [comment]
Modifying the `fee_amount` seems a bit hacky. Would it be possible to include a random value in the `app_data` to make an order unique instead? Not sure if that makes sense in the context of eth flow orders.

**Comment by josojo** [comment]
> Would it be possible to include a random value in the app_data to make an order unique instead?

Yes that would work as well. But we said that we don't wanna bloat the number of app_data's too much, (data-uploads to dune might be limited and we have to pay for ipfs pinning.)

One more thought I had: We need to make sure that no caching of quote requests is going on, otherwise, the proposed solution will not work

**Comment by fedgiac** [comment]
[Rediscussing](https://cowservices.slack.com/archives/C049GSMCTMW/p1669650559687129) our available options, we opted for a frontend-only solution because this can easily solve the issue of two orders of the same user colliding. Our internal data analysis determined that the multi-user case is very uncommon (never happened for WETH) and can be ignored.
