### ISSUE TITLE
Include Balancer Pools in Price Estimation Service

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#81]
As a final step to #733. Currently we do not pass Balancer Liquidity on to the price estimation service. This issue is to adapt price_estimate to include these sources.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1075 by @bh2smith

**Comment by MartinquaXD** [comment]
`BalancerSor` is one of the supported price estimators and `BalancerV2` is part of the baseline sources by now.
@nlordell can this be closed?

**Comment by nlordell** [comment]
I think this issue might still technically be open. Specifically, we don't include Balancer liquidity to the Baseline and Quasimodo price estimators but should.

I agree its not as critical (since the pools are represented in our DEX aggregator nad Balancer SOR price estimators), but it is a code-smell that we should address.
