### ISSUE TITLE
Allow solvers to specify if their solution should be submitted via flashbots

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#812]
Eventually we want the solver-driver co-location to enable solvers to submit their solutions however they want but work on this was paused.
However, solver maintainers are already [asking](https://cowservices.slack.com/archives/C0375NV72SC/p1668749776267779) for a way to signal that a solution should only be submitted via flashbots to avoid getting MEV attacked in the public mempool.
Until we actually finalize the solver-driver co-location adding a flag `submit_with_flashbots` in the solver response seems like a reasonable compromise.
In case we still want to take advantage of other private mempools (e.g. eden network) a more generically named flag `enforce_private_submission` might make more sense.

**Comment by sunce86** [comment]
So, it seems to me that the best way is to add something like:

```
/// Settlement can override submission strategy
#[derive(Debug, Clone, Default)]
pub enum SettlementSubmitter {
    #[default]
    ProtocolDefault,
    Flashbots,
}

#[derive(Debug, Clone, Default)]
pub struct Settlement {
    pub encoder: SettlementEncoder,
    pub submitter: SettlementSubmitter,
}
```

Settlement is built using the solution received from http searcher, while `SolutionSubmitter` also works with the `Settlement`. Once we enter the submission, we would combine the default enabled strategies of protocol with the preferences of the winning settlement being submitted. 

WDYT

**Comment by MartinquaXD** [comment]
The idea looks good to me. I would just call it `SubmissionStrategy`. I believe that naming would fit better with the existing terminology around solution submission.

**Comment by nlordell** [comment]
Sounds very reasonable. I would call it "SubmissionPreference".

The other question is, "what happens if they choose a submitter that isn't configured?". I think we should reject the solution, the alternative would be to fallback to `ProtocolDefault`.

**Comment by MartinquaXD** [comment]
> The other question is, "what happens if they choose a submitter that isn't configured?". I think we should reject the solution, the alternative would be to fallback to ProtocolDefault.

I guess we could let them control that with another flag like `required: bool`. If they specify `flashbots` is `required` but we currently don't have it enabled for some reason we would discard the solution.
We could also send the currently configured strategies in the metadata of the `/solve` request and they could pick and choose from those. Seems a bit overkill for this case but I just wanted to mention it.

**Comment by poolpitako** [comment]
> Sounds very reasonable. I would call it "SubmissionPreference".
> 
> The other question is, "what happens if they choose a submitter that isn't configured?". I think we should reject the solution, the alternative would be to fallback to `ProtocolDefault`.

Driver moved from flashbots to mempool without any change of the api. If `SubmissionPreference` is not available, it should fallback to `ProtocolDefault`.

**Comment by poolpitako** [comment]
Have you discussed impact of using different `SubmissionPreference`s?
Would it be the same for a solver to do fb than mempool?

Also, shouldn't `SubmissionPreference` be:
 - ProtocolDefault
 - Private submission
 - Public mempool
 
Adding public mempool in case ProtocolDefault ends up being private submission.

**Comment by vkgnosis** [comment]
From a game theoretic point of view, does does it ever make sense for a solver to not request flashbots settlement? We currently don't adjust the solver reward based on the speed of execution so is there any downside to it? If the answer is that a rational solver should always request flashbots then this feature is flawed.

**Comment by sunce86** [comment]
I think the point is to request Flashbots ONLY, so it would override if for example, protocol defines public mempool + flashbots.

**Comment by vkgnosis** [comment]
If you imagine you are a solver, is there ever a reason to not request only flashbots? That's my question.

**Comment by sunce86** [comment]
Probably in cases when `flashbots only` does not perform super well/fast, then I would set `ProtocolDefault` to prevent being punished for too long settlement time / timeout.
