### ISSUE TITLE
Dynamically submit to flashbots or public mempool depending on the block proposer compability

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#813]
Before the merge submitting via flashbots seemed to be the only reasonable option. But after the merge adoption of mev-boost was not that overwhelming so we decided to only submit to the public mempool to keep transaction submission times short.

But since the merge we actually know in advance who will be the block proposer for a given block. With that information we would be able to determine whether we should submit a transaction to the public mempool or via flashbots for a given block.

This should reduce our transaction submission times while protecting solvers from MEV attacks for every block we submit via flashbots.

**Comment by fleupold** [comment]
No longer relevant
