### ISSUE TITLE
Non-mature Orders

### ISSUE THREAD

**Issue by felixjff** [cowprotocol/services#826]
Some orders cannot be executed unless they have matured. I assume thy maturity is being set as a specific date (timestamp). This is creating a mismatch across the solutions being submitted for a specific auction, whereby solvers that take longer to submit a response (this coul also be due to the asynchronous nature of responses) have a higher change of actually getting their solution processed by the Driver. In the example below, OTEX submitted a solution but the callback indicated the order was not mature. If we see which solvers took part of the auction, we can see that only 0x and Paraswap "submitted" a solution. I think what happened in reality was that these two solvers just happened to take a bit longer to submit a response to the Driver and they just happened to submit the response exactly after the order matured. 

https://etherscan.io/tx/0xf3432cacb23cd729b2edbdcb50b7dbc1b94ece49de2aa3a96eed429bca772f9c

It would be better if non-mature orders are treated as such for a specific auction to avoid the differences that arise from the response time across solvers.

**Comment by sunce86** [comment]
Thanks for notifying us about this.
Not sure if you are aware, but from the next week release, we will have this improvement: https://github.com/cowprotocol/services/pull/763

This PR (together with better understanding of order maturity handling in driver) solvers should be able to avoid `NoMatureOrder` error.

**Comment by felixjff** [comment]
Wasn't aware of that improvement. Will move there.

**Comment by felixjff** [comment]
Wasn't aware of that change. Having read the comments, it seems similar concerns were raised. The non-mature flag should indeed prevent solvers from including these orders in the solutions. However, less smart solvers (those that are not necessarily maintained) will keep on including the orders in the solutions and will end up winning a settlement, because by the time the solution is assessed by the dirver, the order is mature. 

Will the logic in the driver to assess non-mature orders also change? Say, instead of using the timestamp, will it directly check the non-mature flag?

**Comment by sunce86** [comment]
> Say, instead of using the timestamp, will it directly check the non-mature flag?

No, because this would mean we would eliminate a valid solution (turned to valid by the time driver evaluates it). I believe there is a task in our roadmap to enable solvers to submit more than one solution per `Auction`, that would basically eliminate this weird case because solver would be able to continuously submit solutions.

Also, AFAIC, maturity is checked for all settlements at the same time and not at the time we receive each settlement from each individual solver. So, I will need to double check if there is an issue of this type actually.

**Comment by felixjff** [comment]
Ok. I agree that multiple solution submission will handle this situation. 

I would be surprised if you do verify all solutions at the same time as opposed to when you receive them (specially if you are collecting the responses asynchronously). I can tell from my logs that for some solutions I get the nonMature callback eventhough the settlement took place for that same order, which could only happen if the solution of another solver was evaluated at a different point in time (this is what happenede for the tx shared above).
