### ISSUE TITLE
Balancer Weighted Pool Output Calculation Error

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#859]
Currently, we have settlements failing to execute because the following require is failing for Balancer weighted pools with shallow liquidity:
```
        // Cannot exceed maximum out ratio
        _require(amountOut <= balanceOut.mulDown(_MAX_OUT_RATIO), Errors.MAX_OUT_RATIO);
```

We should account for this in the baseline solver.

**Comment by fleupold** [comment]
Balancer pools have been fixed
