### ISSUE TITLE
Autopilot shadow mode

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#861]
We need to be able to run our autopilot in shadow mode so that we can test new solvers without submitting anything onchain or disrupting the existing auction. This shadow mode should allow the autopilot to fetch auctions from e.g. staging or production without affecting them in any way. It also needs to fetch the solutions generated by other solvers on staging or production and run those solutions though the ranking process, along with the solutions of the new solver being tested.

1. Add a `--shadow <URL>` flag to autopilot. This flag is only valid if the submission strategy is `DryRun`.
2. Do not cut batches, instead get batches from `<URL>/api/v1/auction`.
3. When solving, wait for `<URL>/api/v1/solver_competition/{auction_id}` to return a valid response. Merge the solutions from that endpoint with the solutions of the configured solvers.
4. Do the remaining settlement rating, storing the results, etc. as usual. Note that since the strategy must be `DryRun` nothing is published onchain.

Blocked until https://github.com/cowprotocol/services/issues/862 is done.

**Comment by nlordell** [comment]
> get your auction from a URL

This refers to using the `auction` from a specified remote URL (for example <https://api.cow.fi/mainnet/api/v1/auction> for getting the current Mainnet + Production auction).

**Comment by nlordell** [comment]
Alternatively, this could be something that a `driver --dry-run` would implement. I think the requirements we have are:
1. We want to easily be able to run "shadow" solver deployment in staging that uses the production orderbook (we do this when evaluating new solvers and so we have solver competition between the various shadow solvers)
2. We want to allow 

In theory, we can accomplish 1 by using the auction from one of our deployments (like <https://api.cow.fi/mainnet/api/v1/auction>) and then comparing the inner solution result with the one the other solver's solutions from an actual solver competition (there is also a URL for fetching this information).

**Comment by nlordell** [comment]
**Edit**: I misread the title.

So, we want to be able to start-up an `autopilot` in our cluster that just connects to remote drivers and does solver competition, without ever submitting any transactions. The idea is that we want to collect statistics for new driver+solver "nodes" that are being developed as part of an "acceptance" process that we have for external solver teams.

One challenge I can think of is how do you compute and simulate calldata on the orderbook side? Do we add an additional route to the driver for this?

**Comment by nlordell** [comment]
Linking [this comment](https://github.com/cowprotocol/services/pull/875#discussion_r1036042233) from @vkgnosis

> It seems we need a new route "reveal" first, then store the info, the execute.

Essentially, it looks like we may need a `/reveal` route in the driver for providing settlement information up-front. We can use this in step 4 where:
> Do the remaining settlement rating, storing the results, etc. as usual

In the typical flow, we would call `/execute` for the winner. Instead, we should call `/reveal` for all of the settlements in order to collect things like calldata for inspection.
