### ISSUE TITLE
Set up autopilot run loop for colocation

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#862]
- [ ] #874 
- [ ] Define smaller order model
- [ ] Implement run loop, which should do the following:
    1. Take the currently cached auction from the `SolvableOrdersCache`.
    2. Store it in the database (_note_: Currently the `SolvableOrdersCache` is responsible for storing this auction in the database, so that the `orderbook` API can serve it, this should change to the run-loop).
    3. Call `/solve` for all configured drivers.
    4. Choose the winner.
    5. Call `/execute` on the winning driver.

**Comment by nlordell** [comment]
> Call /execute on the winning driver.

We should also add:
1. the call to `/reveal` on the winning driver
2. store the settlement information in the database
3. call `/execute` on the winning driver
