### ISSUE TITLE
Respect auction deadline when calling `/solve`

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#863]
When autopilot calls `/solve`, the HTTP requests need to have a timeout equal to the current auction deadline.

The deadline value also needs to be passed to `/solve`. The reason why this is necessary is because solvers care about the deadline. They often implement their `/solve` algorithms to respect the deadline (and potentially keep looking for better solutions up _until_ the deadline).

**Comment by vkgnosis** [comment]
When we run the settlement competition we get a proposed solution from all drivers (searchers) and pick the best one. A buggy driver might take forever to actually respond to the http request which would in turn prevent our system from making progress because we cannot rank solutions until we have all of them. This is why a deadline is needed.

Drivers need to know about the deadline so they can adjust their algorithm accordingly. Some drivers might run expensive algorithms that become more optimal the longer they run. If they do not know the deadline then they wouldn't know when they should stop and send back the current best solution.

**Comment by nlordell** [comment]
Looks good, but I would make this issue only be the `/solve` deadline side of things, and #880 be about the block deadline for waiting for a transaction once an `/execute` is accepted.

**Comment by fleupold** [comment]
Deadline is enforced in the autopilot here: https://github.com/cowprotocol/services/blob/0d355270030e736ce63afc04b39e1d3829a37074/crates/autopilot/src/run_loop.rs#L359

and passed as part of the auction here:

https://github.com/cowprotocol/services/blob/0d355270030e736ce63afc04b39e1d3829a37074/crates/driver/src/infra/api/routes/solve/dto/auction.rs#L177
