### ISSUE TITLE
Colocation: Keep track of in-flight orders and filter them out from following run

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#864]
Currently the driver keeps track of in flight orders after it has sent out a settlement transaction because the autopilot might not have seen the auction yet and includes orders that would be invalidated by it in the next auction.

We need a similar check when the autopilot handles the competition. If we don't want to wait for the previous /execute to mine on chain then we need to proactively exclude in flight orders. If we instead wait for the transaction to mine in the autopilot too we might not need this.

**Comment by vkgnosis** [comment]
Here is an example problematic situation:
1. Auction 1 completes with a winning a solution that settles order A.
2. The corresponding driver is told to execute the solution on chain.
3. Autopilot immediately continues with the next auction, 2.
4. In this auction we have not yet observed the settlement transaction from auction 1 so we include order A as a solvable order again.
5. The winning solution for auction 2 settles order A.
6. In the meantime the transaction settling auction 1 execute on chain.
7. Order A can no longer be settled but it was included in the winning solution. This makes the solution invalid.

**Comment by vkgnosis** [comment]
We need to pretend that in flight orders do not exist as long as they are in flight. This means when we send the auction to the drivers, we do not include in flight orders. This doesn't map to a step in my last perfectly because I didn't include "cut the auction".

**Comment by fleupold** [comment]
It's not entirely clear if a solution to this is needed before going into prod, but we should at least look into and get consensus if this is an issue or not.

**Comment by fleupold** [comment]
#1974
