### ISSUE TITLE
Colocation: Status updates to the solver competition information

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#865]
We store information about the competition so that it can be inspected by the public after-the-fact. This currently happens in the driver because that is where the competition happens. The driver sends it to the api (orderbook) which stores it in the database. When we change the competition to happen in the autopilot, the autopilot should be the one to store this information in the database.

Depends on https://github.com/cowprotocol/services/issues/862.
Dependency of https://github.com/cowprotocol/services/issues/877.

**Comment by sunce86** [comment]
Implemented with https://github.com/cowprotocol/services/pull/1741
