### ISSUE TITLE
Support multiple interactions when asking for a "binding" quote.

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#866]
Solver might require multiple interactions to settle a trade efficiently. To allow for that the `Trade` type needs to hold a `Vec<Interaction>` instead of a single one. 
Then we could turn a settlement generated by a solver into a `Trade` to use it with the trade verifying API.
This requires slight changes when we turn `0x`, `1Inch` or `Paraswap` `/swap` requests into `Trade`s as well as a tiny change in `Trade::encode()`.

**Comment by MartinquaXD** [comment]
This is the [`Trade`](https://github.com/cowprotocol/services/blob/main/crates/shared/src/trade_finding.rs#L37) in question:
```rust
/// A trade.
#[derive(Clone, Debug, Default, Eq, PartialEq)]
pub struct Trade {
    pub out_amount: U256,
    pub gas_estimate: u64,
    pub approval: Option<(H160, H160)>,
    // replace with `pub interactions: Vec<Interaction>`
    pub interaction: Interaction,
}

**Comment by nlordell** [comment]
Basically, our trade simulation code assumes a single "interaction" (domain-specific term for an EVM call from the settlement contract to an external contract as part of a settlement - typically an AMM to execute a swap) which is incorrect.

**Comment by MartinquaXD** [comment]
Was implemented at some point.
