### ISSUE TITLE
Replace `dyn Solver` with `dyn HttpSolverApi` in the new driver

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#868]
Using the `dyn HttpSolverApi` makes it clearer how the `driver` talks to solvers and gives it a crucial bit of flexibility. With that change in place it will be possible to share most of the logic between `/solve` and `/quote`.
After implementing #867 it should be simple to swap out the trait. Implementing this issues should mostly consist of setting up all the necessary types in the `main` function of the driver and using a different function of the `AuctionConverter` internally.

**Comment by fleupold** [comment]
I believe this can be closed, right @MartinquaXD ?
