### ISSUE TITLE
Build a `BatchAuctionModel` from a quote `Query`

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#870]
After #868 it should be easy to reuse a lot of logic in the `AuctionConverter` used for building `BatchAuctionModel` for an `Auction` for building a `BatchAuctionModel` from a quote `Query`. To see what has to happen check out `HttpPriceEstimator::estimate`.
Depending on whether #869 liquidity collection could already be shared between those 2 `AuctionConverter` functions.

**Comment by fleupold** [comment]
We do have a FakeAuction model for this now.
