### ISSUE TITLE
Implement quoting logic in the new driver

### ISSUE THREAD

**Issue by MartinquaXD** [cowprotocol/services#871]
With #870 and #868 in place we can implement quoting logic in the new driver by reusing the solving logic of the contained `dyn HttpSolverApi`. To see how to get an `Estimate` from a `SettledBatchAuctionModel` check out the end of `HttpPriceEstimator::estimate`.
Note that it makes sense for an external solver to support the `PriceEstimating` trait as well as the `TradeFinding` trait so logic to turn a `SolvedBatchAuctionModel` into a `Trade` is also needed.

Note that because the system doesn't have any RFQ capabilities yet it's fine to have the same logic for quoting as for trade finding.

**Comment by fleupold** [comment]
This is complete
