### ISSUE TITLE
Configurable Wait Time in `autopilot` For Settlement Mining

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#881]
Related to #880.

Currently (i.e. in the current `solver` binary), we wait for execution until starting the next batch. This does a couple important things:
* Naturally form conditions for “CoW”s in that we accumulate more orders to execute simultaneously
* Avoid AMM race conditions (consecutive batches that touch the same AMM - handling this would be a challenging problem).

This issue captures the work of adding a new configuration option to the autopilot to “wait for `$CONFUGRABLE_TIMEOUT` blocks” before moving on to the next auction. Note that this option is **different** than the execution deadline discussed in #880 (this option is for how long the `autopilot` waits, the deadline is how long the external `driver` has to get the transaction on-chain before it gets in trouble).

In terms of performance considerations, solvers should be batching orders together. So throughput should be roughly the same (as the orders/settlement bandwidth is theoretically high) at the cost of some latency (waiting for previous auction to mine before starting with your order). We can play with configuration option by:
- setting this higher to fully wait for execution most of the time
- setting it lower to start the next auction sooner (or even to 0 to start the next batch without waiting)

**Comment by sunce86** [comment]
We should probably change the title of the issue (remove `SettlementMining` since this issue relates to the whole auction process, not just the mining). Maybe `Configurable Wait Time in autopilot For Auction To Finish`.

**Comment by sunce86** [comment]
Since the block time for Gnosis Chain is lower (5s), does this means our auctions on Gnosis Chain will last less then on Ethereum or we will define this configuration in a way that we always spend the exact time for all networks?

**Comment by nlordell** [comment]
For me this issue is just about mining. Basically, once an external driver accepts the `/execute` call, this issue captures the work of implementing a "wait X amount of time until the promised solution is seen on-chain". It that regard, it is not related to the settlement as a whole.

> does this means our auctions on Gnosis Chain will last less then on Ethereum or we will define this configuration in a way that we always spend the exact time for all networks?

No, I just imagine that we will configure the following differently:
- Block deadline for auctions be mined by the `driver` (#880)
- Time that the `autopilot` waits to see the settlement (this issue).

**Comment by fleupold** [comment]
I think this is actually blocking prod as it looks like we are currently waiting 60s for a tx to be mined. In case of reverts this time will be used up fully which can significantly slow down our settlement throughput.

**Comment by fedgiac** [comment]
The timeouts right now are a bit perplexing to me. From the autopilot side we wait [max 60 seconds](https://github.com/cowprotocol/services/blob/6ac97e37eecf4bdd1e41c4efd187c0c09e921c43/crates/autopilot/src/run_loop.rs#L452) after notifying the driver.
From the driver side we [wait](https://github.com/cowprotocol/services/blob/e2ca143aa19495522a163253540f4937e7b2025b/crates/solver/src/driver.rs#L454-L456) `max_confirm_time_secs + additional_mining_deadline = 120 + 60 = 180`.
