### ISSUE TITLE
Port Existing Gnosis-Run Solvers

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#882]
Currently, the `solver` binary has a few solvers with special support that were historically run by Gnosis. These include some "internal" solvers:
- Baseline solver
- Naive solver
- DEX Aggregator solvers (0x, ParaSwap, 1Inch)

And to a lesser extent three other "special case" HTTP solvers
- Quasimodo
- CowDexAg
- MIP (deprecated)

These solvers need to be ported to the new colocated `driver` + `searcher` (with exception of the `MIP` solver which can be removed as it is only used for storing instance files ATM, and can be replaced by #888).

This will envolve taking the "internal" solvers and moving them into a binary implementing the HTTP interface defined in #830. While this should be very easy for the DEX aggregator solvers (since they don't make use of any liquidity indexed by the `driver`), there might be some additional challenges for porting the Baseline and Naive solver (as they use the driver indexed liquidity and would need some refactoring).

**Comment by MartinquaXD** [comment]
We also have the `cowdexag` solver (albeit in another [repo](https://github.com/gnosis/cow-dex-solver)). Also AFAIK the `MIP` solver is currently only used to store the `instance.json` (the request solvers get from us) persistently. With that in mind it could be easier to write a new mechanism to store the file if it's less work than adapting `MIP` completely (we should do that at some time anyway).

**Comment by nlordell** [comment]
> With that in mind it could be easier to write a new mechanism to store the file if it's less work than adapting MIP completely (we should do that at some time anyway).

Yes. This should be specified by https://github.com/cowprotocol/services/issues/888.

> Since MIP is deprecated, maybe this is the time to get rid of it entirely?

Yes. Will clarify in the issue description.
