### ISSUE TITLE
Add Simple Authentication Scheme to Driver Routes.

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#883]
Drivers are run externally and need to be called by the `autopilot`. Since routes like `/execute` (and in the future `/reveal`) will be signed by an `autopilot` secret (https://github.com/cowprotocol/services/issues/887), there is limited damage that can be done by malicious third parties pretending to be `autopilot`s.

However, providing drivers with some basic form of authentication would be a nice-to-have. This can provide some basic protection from malicious third parties "bombarding" `driver`s with `/solve` requests for example. In theory this can be configured at an ingress level (by, for example, setting up an Nginx reverse-proxy in front of the `driver` + `searcher` infrastructure), but this would just be an easy feature to help reduce barrier to entry.

Implementing this can be delayed until requested by an external solver team.

**Comment by ennmichael** [comment]
Closing in favor of https://github.com/cowprotocol/services/issues/885.
