### ISSUE TITLE
Verify `autopilot` Signature In `driver`

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#887]
The `/reveal` and `/execute` routes contain an `autopilot` signature to prove that it was called by the protocol. The driver needs to verify this signature before acting on those requests because:

- The `/reveal` route returns "sensitive" information (i.e. trade secrets about how a specific settlement would execute). If called by a malicious third party, this can be used to extract a solver's settlement and gain information from it (an example of what could happen is solver A just waits for solver B to have a solution and then calls `/reveal` on solver B's driver so that they can replay the exact same solution and win some of the time).
- The `/execute` route causes a driver to execute a settlement on-chain. This means that both these routes, if called by a malicious third party, it could cause a driver to execute settlements outside of the protocol (which would mean reduced protection for user orders and slashing for the solver).

Again, for this issue the signature scheme is undefined. For the same reasons outlined in #885, I would propose EIP-712 signatures of structured data (the data being what is included as part of the requests).

**Comment by ennmichael** [comment]
Closing in favor of https://github.com/cowprotocol/services/issues/885. Both sides of communication are described there.
