### ISSUE TITLE
`driver` crate

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#892]
Tracking issue for all tasks needed to implement the `driver` crate.

- [x] https://github.com/cowprotocol/services/issues/893
- [x] https://github.com/cowprotocol/services/issues/895
- [x] https://github.com/cowprotocol/services/issues/896
- [x] https://github.com/cowprotocol/services/issues/899
- [x] https://github.com/cowprotocol/services/issues/898
- [x] https://github.com/cowprotocol/services/issues/897
- [x] https://github.com/cowprotocol/services/issues/894
- [ ] https://github.com/cowprotocol/services/issues/888
- [x] https://github.com/cowprotocol/services/issues/914
- [ ] https://github.com/cowprotocol/services/issues/930
- [x] https://github.com/cowprotocol/services/issues/1009
- [ ] https://github.com/cowprotocol/services/issues/1044
- [ ] https://github.com/cowprotocol/services/issues/1071
- [x] https://github.com/cowprotocol/services/issues/1091
- [x] https://github.com/cowprotocol/services/issues/1095
- [x] https://github.com/cowprotocol/services/issues/1105
- [ ] https://github.com/cowprotocol/services/issues/1122
- [x] https://github.com/cowprotocol/services/issues/1130
- [ ] https://github.com/cowprotocol/services/issues/885
- [x] https://github.com/cowprotocol/services/issues/1304
- [x] https://github.com/cowprotocol/services/issues/1311

**Comment by fleupold** [comment]
Closing in favor of higher level tracking task
