### ISSUE TITLE
`/solve` endpoint for `driver`

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#895]
The `/solve` endpoint is used to calculate the solution to an auction. This endpoint should calculate the objective value (score) for each solution and return it in the response.

#### Input

```js
{
  "id": u64, // The auction ID
  "block": u64, // The current block
  "orders": [Order],
  "prices": Map<token address, big number>,
}
```

Where `Order` is defined as all of the fields on [`Order`](https://github.com/cowprotocol/services/blob/ed3529408a2ba2a252da974bfc93fe70b8103298/crates/model/src/order.rs#L43), with only the following taken from `metadata`:

```js
  "full_fee_amount": big number, // For objective value (score) computation
  "is_mature": bool, // Used by the solvers
  "class": "market" | "limit" | "liquidity", // For objective value (score) computation
  "surplus_fee": big number, // For effective limit price computation
  "executed_amount": big number // For partially fillable orders
  //  The following two fields are needed for settlement encoding
  "interactions": [
    {
      "to": string, // Address to call
      "value": string, // Value to use for the EVM call
      "data": string, // Hex-encoded call data (for the eth_call RPC, this is the input field)
    }
  ],
  "accessList": [
    {
      "address": string, // The smart contract address
      "storage_keys": [string], // Addressed storage keys
    }
  ]
```

#### Output

The response from the `/solve` endpoint should be the objective value (score) of the best solution. If the solver lies about its score, its rewards will be slashed by the DAO.

```js
{
  "score": rational,
}
```

Related: https://github.com/cowprotocol/services/issues/894.

**Comment by vkgnosis** [comment]
It's not clear to me how the id is chosen. I get the main point of the id idea. We can store it in the database before calling /execute so we can later associate the transaction with the auction.

That relies on IDs being unique. But if solvers choose the id then how can this be guaranteed? And how it can be guaranteed that another id wasn't randomly part of some calldata. The longer the id is the more expensive it is to include it.

**Comment by MartinquaXD** [comment]
Why is it necessary that the id is already part of the `/solve` request? Wouldn't it be enough to generate a single random id in the `autopilot` when the winner is chosen and put that in the `/execute` request instead?

**Comment by vkgnosis** [comment]
If autopilot can choose the id then we can even guarantee that it is unique. We can use an auto incrementing integer in Postgres like what we do for auction ids. Actually, we can just reuse the auction id.

**Comment by vkgnosis** [comment]
Martin's comment makes sense to me too. We can choose it in /execute.

**Comment by vkgnosis** [comment]
It sounds like the attack model is that another solver could maliciously use an id that we didn't tell them to. I don't think this is a reasonable attack model.

1. We would still know which solver did this as we can see its address. So a solver-address and id pair still uniquely identifies a solver.
2. Transactions in ethereum are public before they are mined. If this was a serious vulnerability then another solver could still learn of the secure id and quickly submit their own transaction copying it.

**Comment by vkgnosis** [comment]
> I thought it might be needed for objective value calculation? Also I thought that the solvers need to know exactly what they will be publishing on the blockchain? Am I incorrect?

It matters for the objective value insofar that the objective value includes gas use and adding 8 bytes uses more gas. However the change in gas is negligible (?) and it is the same for all solvers so it doesn't matter. There were also plans of removing the gas use from the objective value. Not sure what the state of that is.

**Comment by MartinquaXD** [comment]
I think it's important that the new id is secret and therefore has to be unpredictable. As I see it a whoever owns (or rather won) the secret key will be made responsible for the associated on-chain settlement. So if all is good then the solver who got the key from us earns rewards but if the solution is bad they get slashed. That means a malicious solver has no reason to steal or guess the key from the actual winning solver and submit a good solution itself (because it wouldn't get the rewards) but it might try to impersonate the winning solver and submit a bad solution to get the actual winner slashed.
