### ISSUE TITLE
Single Order Solver merge logic requires exchange rates to exactly equal

### ISSUE THREAD

**Issue by fleupold** [cowprotocol/services#912]
When a single order solver (e.g. Paraswap, 1Inch, Matcha) finds solutions to more than 1 orders, it attempts to merge multiple solutions into a single one (in order to increase its chance to win the auction).

However, the logic under which this is done is very naive and has two problems (both of them can be observed in the logs attached [here](https://github.com/cowprotocol/services/files/10154621/Untitled.discover.search.csv)):

1. Price violation errors (#503)
2. Price Scaling checks for exact price equivalence (described in the following)

In the attached logs we can see many orders selling sUSD for sEUR at slightly different amounts but all using the same route and pretty much the same exchange rate. E.g.:
- clearing_prices: {0x57ab1ec28d129707052df4df418d58a2d46d5f51: 49669339774861718822095, 0xd71ecff9342a5ced620049e616c5035f1db98620: 49968813311413145968640}
- clearing_prices: {0x57ab1ec28d129707052df4df418d58a2d46d5f51: 49665397004506029793436, 0xd71ecff9342a5ced620049e616c5035f1db98620: 49964846768738606309376}

While not exactly the same (difference at a precision level beyond normal floating point representation) those solutions should still be combined (at the worse of the two prices). A slightly more sophisticated merge-logic could also combine solutions up to a certain divergence tolerance.

**Comment by MartinquaXD** [comment]
This is the same issues as #503, right?

**Comment by fleupold** [comment]
Thanks for the reference, 🤦 I used search but couldn't find this issue. Let me rewrite it and only make it about the exact matching then

**Comment by fleupold** [comment]
Probably not going to fix as we are trying to reduce the amount of logic we add to the gnosis solvers (and this wouldn't be something we want to do on behalf of external solvers)
