### ISSUE TITLE
Solver multiplexing

### ISSUE THREAD

**Issue by sistemd** [cowprotocol/services#914]
When the driver is configured with multiple solvers, it will need to expose all of them at different endpoints. Assuming that the solvers are configured with names `solver1`, `solver2`, ..., `solverN`, the most elegant way to do this is the following:

```
Forward to solver1:
POST /solver1/solve
POST /solver1/quote
POST /solver1/execute

Forward to solver2:
POST /solver2/solve
POST /solver2/quote
POST /solver2/execute

...

Forward to solverN:
POST /solverN/solve
POST /solverN/quote
POST /solverN/execute
```

Then, the autopilot can be conveniently configured as if `<DRIVER_URL>/solver1/`, `<DRIVER_URL>/solver2/`, etc. were all exposing individual APIs.

**Comment by MartinquaXD** [comment]
Description looks good but I'm not sure about the requirement that the request forwarding should behave differently when only a single solver is configured. Seems like it could be surprising for users and unnecessarily complex to implement.
