### ISSUE TITLE
HTTP compression for http-solver interface

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#916]
The auction requests from driver to http-solver are starting to become big because there are many orders, liquidity and json is an inefficient format. We should look into whether its worth it to force a specific compression scheme. We can't auto detect what the server supports because we're initiating the request.

**Comment by fleupold** [comment]
Solvers now request the json without liquidity to save on size. We actually have a gzip flag on the solver API which we could set on a per solver config basis if we wanted (currently set to false always)

**Comment by fleupold** [comment]
Pointer to where this would have to get configured: https://github.com/cowprotocol/services/blob/c70090e31af0a90e4c481dd3dd3cc93a1c6a3919/crates/solvers/src/boundary/legacy.rs#L56
