### ISSUE TITLE
API Price Estimates Can Lead To Untradable Orders

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#92]
It is my understanding, that adding ParaSwap price estimator to the API increases the amount of tokens the API supports by taking advantage of more liquidity.

The issue, however, is that the the solution objective value is computed using baseline price estimates, therefore (at least to my understanding), it would ignore solutions that trade tokens for which the baseline price estimator cannot find a path.

This might cause some UX issues where a user is able to create an order, but we can never execute the trade because there is no price estimate for the objective value computation.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1253 by @nlordell

**Comment by MartinquaXD** [comment]
Closing as price estimator landscape has been diversified and objective values are now independent of the baseline price estimator.
