### ISSUE TITLE
Make it possible to adjust log level while pod is running

### ISSUE THREAD

**Issue by vkgnosis** [cowprotocol/services#940]
There is a trade off when deciding how much to log. Too much logging adds noise and makes identifying meaningful logs harder and strains the logging backend. Too little logging makes it hard to debug issues. It can be hard to know in advance what the log level should be.

At the moment, we can adjust the log level through a command line argument. This works but has the downside that the pod needs to be restarted.

It would be nice if we could adjust the log level in a running pod without restarting it. I'm not sure what the best way to do this is. Some ideas are: linux process signal, watch over a file, network request, database. We also need to check that the tracing subscriber we use can adjust the log level in the first place.

**Comment by fleupold** [comment]
Actually done
