### ISSUE TITLE
Should we filter out settlements that include only liquidity orders / PMMs ?

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#95]
We treat some orders special when we set is_liquidity_order to true. This excludes them from the objective value which in turn causes solutions to be preferred that also include "normal" orders.
However there is no explicit check for the case where a settlement contains only liquidity orders. So we could run into a situation where such a solution still gets picked as the highest objective value if there is no better solution.

Should we add such a check? Alternatively excluding negative objective value solutions should also fix this because these orders do not add any surplus but cost.

> Original issue https://github.com/gnosis/gp-v2-services/issues/1307 by @vkgnosis

**Comment by MartinquaXD** [comment]
Closing because a check preventing solutions with only liquidity orders has been added.
