### ISSUE TITLE
Change Auction ID Format

### ISSUE THREAD

**Issue by nlordell** [cowprotocol/services#973]
This issue captures the work to:
- [ ] Propose and find some consensus on what we should use for an action ID (some proposals are UUID, so that they are unique across deployments, and [ULID](https://github.com/ulid/spec) so that they are probabilistically unique and lexicographically sortable).
- [ ] Implement the required changes to the code to reflect this change.

_Originally posted by @ennmichael in https://github.com/cowprotocol/services/pull/962#discussion_r1049867772_:

> This might be a good opportunity to start using something like a [UUID](https://en.wikipedia.org/wiki/Universally_unique_identifier) for auctions. I believe this would be beneficial, since auctions would no longer suffer from not having unique IDs across different chains, and instead be truly, globally, unique.
> 
> (Of course I propose doing this only if it's technically possible, i.e. the settlement contract allows it and so on.)

**Comment by fleupold** [comment]
Currently auctionID seems to be the primary key of the auctions table
