### ISSUE TITLE
Send `solve` request to SeaSolver as gzip

### ISSUE THREAD

**Issue by sunce86** [cowprotocol/services#998]
Compress request body when sending `solve` request to `SeaSolver`.
Response from `SeaSolver` is already gzipped right now (need to double check).

It should be relatively easy to:
1. Set the header `Content-Encoding = gzip`
2. Compress request body

Also, the change should be configurable `per external solver`.

**Comment by vkgnosis** [comment]
We should do this for all solvers. It is unnecessary configuration overhead to keep track of it per solver.  (We might have an issue or a slack thread about this already.) We would document that we are going to send requests gzipped and inform solvers about this. Then we can manually test that they support. Then switch every solver to gzip.

**Comment by vkgnosis** [comment]
This could be more important than expected. Checking the api pod's network stats through `iftop` I see that 100mbit/s upload can spike to quasimodo from price estimates. This can be reduced a lot with some form of compression.

**Comment by vkgnosis** [comment]
My plan for this is the following: Check with all existing http solvers whether they support gzipped request bodies. If they do, then we can unconditionally enable this and make it a requirement for solvers to support this. If they don't, then try to autodetect whether the solver supports it on start up by sending two test requests, one with gzip and one without.
